// Auto-generated from Google Sheet through Apps Script.
// Source: Admit Cards
// Do not edit manually when sync is enabled.

window.GovJobUpdatesAdmitCards = [
    {
        "id": "admit-sheet-0052-20260707221234-e88453dd",
        "title": "UPPSC Assistant Teacher LT Grade Mains Admit Card 2026 Music, Hindi Subject",
        "organization": "Uttar Pradesh Public Service Commission",
        "department": "UPPSC",
        "category": "State Government",
        "year": "2026",
        "examDate": "2026-07-06",
        "examEndDate": "2026-07-21",
        "releaseDate": "2026-06-26",
        "status": "available",
        "tags": [],
        "downloadLink": "https://uppsc.up.nic.in/CandidatePages/Advertismentwise_DownloadDocument.aspx?inptprmtr=ac",
        "detailPage": "../AdmitCard_Details/HTML/UPPSC-LT-Grade-Biology-Main-Exam-Admit-Card-2026.html",
        "updatedAt": "2026-07-07",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0046",
        "title": "UP Police Home Guard DV Admit Card 2026",
        "organization": "Uttar Pradesh Police Recruitment & Promotion Board",
        "department": "UPPRPB",
        "category": "State Government",
        "year": "2026",
        "examDate": "2026-07-13",
        "examEndDate": "2026-08-07",
        "releaseDate": "2026-07-04",
        "status": "available",
        "tags": [],
        "downloadLink": "https://uppbpb.gov.in/",
        "detailPage": "../AdmitCard_Details/HTML/UP-Police-Homeguard-DV-PST-Notice-2026.html",
        "updatedAt": "2026-07-05",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0047",
        "title": "RPSC Rajasthan Police SI, Platoon Commander Interview Letter 2026",
        "organization": "Rajasthan  Public Service Commision",
        "department": "RPSC",
        "category": "State Government",
        "year": "2026",
        "examDate": "2026-07-08",
        "examEndDate": "2026-07-17",
        "releaseDate": "2026-07-04",
        "status": "available",
        "tags": [],
        "downloadLink": "https://rssbasonline.com/Interview/Index",
        "detailPage": "../AdmitCard_Details/HTML/RSSB-Rajasthan-Platoon-Commander-Interview-Letter-2026.html",
        "updatedAt": "2026-07-05",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0048",
        "title": "SSB Head Constable Admit Card 2026",
        "organization": "Sashastra Seema Bal",
        "department": "SSB",
        "category": "Defence",
        "year": "2026",
        "examDate": "2026-07-07",
        "examEndDate": "",
        "releaseDate": "2026-07-04",
        "status": "exam-over",
        "tags": [],
        "downloadLink": "https://cdn.digialm.com//EForms/configuredHtml/1258/101413/login.html",
        "detailPage": "../AdmitCard_Details/HTML/SSB-Head-Constable-Ministerial-Exam-Date-2026.html",
        "updatedAt": "2026-07-05",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0049",
        "title": "MPESB ADDET Animal Husbandry Admit Card 2026",
        "organization": "Madhya Pradesh Employees Selection Board (MPESB)",
        "department": "MPESB",
        "category": "State Government",
        "year": "2026",
        "examDate": "2026-07-10",
        "examEndDate": "",
        "releaseDate": "2026-07-04",
        "status": "available",
        "tags": [],
        "downloadLink": "https://esb.mp.gov.in/tacs/tac_2026/ADDET_TAC26/default_tac.htm",
        "detailPage": "../AdmitCard_Details/HTML/MPESB-ADDET-Animal-Husbandry-Admit-Card-2026.html",
        "updatedAt": "2026-07-05",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0050",
        "title": "MPESB PNST Pre Nursing Admit Card 2026",
        "organization": "Madhya Pradesh Employees Selection Board (MPESB)",
        "department": "MPESB",
        "category": "State Government",
        "year": "2026",
        "examDate": "2026-07-10",
        "examEndDate": "",
        "releaseDate": "2026-07-04",
        "status": "available",
        "tags": [],
        "downloadLink": "https://esb.mp.gov.in/tacs/tac_2026/PNST_TAC26/default_tac.htm",
        "detailPage": "../AdmitCard_Details/HTML/MPESB-PNST-Pre-Nursing-Admit-Card-2026.html",
        "updatedAt": "2026-07-05",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0029",
        "title": "UPPSC Assistant Town Planner Admit Card 2026",
        "organization": "Uttar Pradesh Public Service Commission (UPPSC)",
        "department": "UPPSC",
        "category": "State Government",
        "year": "2026",
        "examDate": "2026-07-07",
        "examEndDate": "",
        "releaseDate": "2026-06-29",
        "status": "exam-over",
        "tags": [],
        "downloadLink": "https://uppsc.up.nic.in/CandidatePages/Advertismentwise_DownloadDocument.aspx?inptprmtr=ac",
        "detailPage": "../AdmitCard_Details/HTML/06-UPPSC-Assistant-Town-Planner-Admit-Card-2026.html",
        "updatedAt": "2026-07-02",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0030",
        "title": "UPHESC Assistant Professor Interview Letter 2026 for 981 Post",
        "organization": "UP Higher Education Services Commission",
        "department": "UPHESC",
        "category": "State Government",
        "year": "2026",
        "examDate": "2026-07-21",
        "examEndDate": "2026-08-13",
        "releaseDate": "2026-06-29",
        "status": "available",
        "tags": [],
        "downloadLink": "https://www.upessc.net/ap2022callletter/Login.aspx",
        "detailPage": "../AdmitCard_Details/HTML/51-UPESSC-Assistant-Professor-Interview-Admit-Card-2026.html",
        "updatedAt": "2026-07-02",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0031",
        "title": "SBI Apprentice Admit Card 2026 for 7150 Post",
        "organization": "State Bank of India",
        "department": "SBI",
        "category": "Banking",
        "year": "2026",
        "examDate": "2026-07-11",
        "examEndDate": "",
        "releaseDate": "2026-06-30",
        "status": "available",
        "tags": [],
        "downloadLink": "https://ibpsreg.ibps.in/sbiaapr26/oecla_jun26/login.php?appid=42f888ad90671cdf0f66feefc29b82ec",
        "detailPage": "../AdmitCard_Details/HTML/04-SBI-Apprentice-Admit-Card-2026.html",
        "updatedAt": "2026-07-02",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0032",
        "title": "Railway RRB NTPC Graduate Level CBT II Exam City Details 2026 | CEN 06/2025",
        "organization": "Railway Recruitment Board",
        "department": "RRB",
        "category": "Central Government",
        "year": "2026",
        "examDate": "2026-07-10",
        "examEndDate": "",
        "releaseDate": "2026-06-30",
        "status": "available",
        "tags": [],
        "downloadLink": "https://rrb.digialm.com/EForms/configuredHtml/33128/98228/login.html",
        "detailPage": "../AdmitCard_Details/HTML/06-2025-RRB-NTPC-Graduate-CBT-2-Admit-Card-2026.html",
        "updatedAt": "2026-07-02",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0033",
        "title": "UPCISB UP Cooperative Bank Various Post Exam Date 2026 for 116 Post",
        "organization": "UP Cooperative Bank",
        "department": "UPCISB",
        "category": "Banking",
        "year": "2026",
        "examDate": "2026-07-20",
        "examEndDate": "2026-07-22",
        "releaseDate": "2026-07-01",
        "status": "available",
        "tags": [],
        "downloadLink": "https://upcisb.upsdc.gov.in/",
        "detailPage": "../AdmitCard_Details/HTML/UPCISB-Co-operative-Banking-Exam-Admit-Card-2026.html",
        "updatedAt": "2026-07-02",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0034",
        "title": "CBSE Group A B C Skill Test Exam City 2026 for 124 Post",
        "organization": "Central Board Of Secondary Education",
        "department": "CBSE",
        "category": "Education",
        "year": "2026",
        "examDate": "2026-07-18",
        "examEndDate": "2026-07-26",
        "releaseDate": "2026-07-01",
        "status": "available",
        "tags": [],
        "downloadLink": "https://examinationservices.nic.in/recSys2025/root/CandidateLogin.aspx?enc=Ei4cajBkK1gZSfgr53ImFSuabJtfdyH7GsL2cij2dPKFqA5XsHH8yMmK+6SEPU/E",
        "detailPage": "../AdmitCard_Details/HTML/CBSE-DRQ-Skill-Test-Admit-Card-2026.html",
        "updatedAt": "2026-07-02",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0035",
        "title": "Rajasthan RSSB LDC, Jr Assistant Admit Card 2026",
        "organization": "RSSB",
        "department": "RSSB",
        "category": "State Government",
        "year": "2026",
        "examDate": "2026-07-05",
        "examEndDate": "",
        "releaseDate": "2026-06-26",
        "status": "exam-over",
        "tags": [],
        "downloadLink": "https://recruitment.rajasthan.gov.in/rectlogingetadmitcard",
        "detailPage": "../AdmitCard_Details/HTML/RSMSSB-Clerk-Grade-II-Junior-Assistant-Admit-Card-2026.html",
        "updatedAt": "2026-07-02",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0036",
        "title": "Bihar BPSC Auditor Admit Card 2026 for 102 Post",
        "organization": "Bihar Public Service Commission",
        "department": "BPSC",
        "category": "State Government",
        "year": "2026",
        "examDate": "2026-07-05",
        "examEndDate": "",
        "releaseDate": "2026-07-01",
        "status": "exam-over",
        "tags": [],
        "downloadLink": "https://bpsconline.bihar.gov.in/candidate/login",
        "detailPage": "../AdmitCard_Details/HTML/BPSC-Auditor-Admit-Card-2026.html",
        "updatedAt": "2026-07-02",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0037",
        "title": "NTA ICAR AIEEA PG & Phd Admit Card 2026",
        "organization": "National Testing Agency",
        "department": "NTA",
        "category": "Central Government",
        "year": "2026",
        "examDate": "2026-07-04",
        "examEndDate": "",
        "releaseDate": "2026-07-01",
        "status": "exam-over",
        "tags": [],
        "downloadLink": "https://examinationservices.nic.in/AdmitCardService/Admitcard/Login?enc=y4cMoXShddrjVCWgrykM85f7JaXFXY4HVEJI6IyyUic=",
        "detailPage": "../AdmitCard_Details/HTML/NTA-ICAR-AIEEA-PG-Admit-Card-2026.html",
        "updatedAt": "2026-07-02",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0038",
        "title": "BSNL Senior Executive Trainee SET Admit Card 2026 for 120 Post",
        "organization": "Bhartiya Sanchar Nigam limited",
        "department": "BSNL",
        "category": "Public Sector",
        "year": "2026",
        "examDate": "2026-07-05",
        "examEndDate": "",
        "releaseDate": "2026-07-01",
        "status": "exam-over",
        "tags": [],
        "downloadLink": "https://ibtexamination.com/secuAdmitcard/bsnlAdmitcard03/",
        "detailPage": "../AdmitCard_Details/HTML/03-BSNL-Senior-Executive-Trainee-SET-Admit-Card-2026.html",
        "updatedAt": "2026-07-02",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0039",
        "title": "HTET Admit Card 2026 | Syllabus | Haryana Teacher Eligibility Test",
        "organization": "Haryana Teacher Eligibility Test",
        "department": "HTET",
        "category": "Education",
        "year": "2026",
        "examDate": "2026-07-04",
        "examEndDate": "2026-07-05",
        "releaseDate": "2026-07-02",
        "status": "exam-over",
        "tags": [],
        "downloadLink": "https://htet.eapplynow.com/HTETApp25/Pages/Admit01Login7.aspx",
        "detailPage": "../AdmitCard_Details/HTML/BSEH-HTET-Haryana-Admit-Card-2026.html",
        "updatedAt": "2026-07-02",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0040",
        "title": "RPSC Senior Teacher Grade II TGT Exam City 2026 for 6500 Post",
        "organization": "Rajasthan Public Service Commission",
        "department": "RPSC",
        "category": "State Government",
        "year": "2026",
        "examDate": "2026-07-12",
        "examEndDate": "2026-07-18",
        "releaseDate": "2026-07-01",
        "status": "available",
        "tags": [],
        "downloadLink": "https://sso.rajasthan.gov.in/",
        "detailPage": "../AdmitCard_Details/HTML/RPSC-Senior-Teacher-Admit-Card-2026.html",
        "updatedAt": "2026-07-02",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0041",
        "title": "RRB Railway ALP Assistant Loco Pilot CBT II Exam Date 2026 | CEN 01/2025",
        "organization": "Railway Recruitment Board",
        "department": "RRB",
        "category": "Central Government",
        "year": "2026",
        "examDate": "2026-07-28",
        "examEndDate": "",
        "releaseDate": "2026-07-18",
        "status": "upcoming",
        "tags": [],
        "downloadLink": "https://www.rrbpatna.gov.in/pdf/Notice%20on%20Tentative%20date_CBT-2_English.pdf",
        "detailPage": "../AdmitCard_Details/HTML/01-RRB-ALP-CBT-2-Admit-Card-2026.html",
        "updatedAt": "2026-07-02",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0042",
        "title": "CBI Apprentice Exam Date 2026 for 4500 Post",
        "organization": "Central Bank  of India",
        "department": "CBI",
        "category": "Banking",
        "year": "2026",
        "examDate": "2026-07-05",
        "examEndDate": "",
        "releaseDate": "2026-07-02",
        "status": "exam-over",
        "tags": [],
        "downloadLink": "https://beep.bfsissc.com/candidate_login",
        "detailPage": "../AdmitCard_Details/HTML/03-Central-Bank-Apprentice-Admit-Card-2026.html",
        "updatedAt": "2026-07-02",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0043",
        "title": "Rajasthan RIICO Various Post Admit Card 2026",
        "organization": "RIICO",
        "department": "RIICO",
        "category": "State Government",
        "year": "2026",
        "examDate": "2026-07-08",
        "examEndDate": "2026-07-09",
        "releaseDate": "2026-07-02",
        "status": "available",
        "tags": [],
        "downloadLink": "https://ibpsreg.ibps.in/riicosep25/oecla_jun26/login.php?appid=2599483d1ccf65d6f7f814ab9ce00705",
        "detailPage": "../AdmitCard_Details/HTML/04-RIICO-Various-Posts-Admit-Card-2026.html",
        "updatedAt": "2026-07-02",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0044",
        "title": "UPSSSC Assistant Boring Technician Exam City 2026 for 402 Post",
        "organization": "Uttar Pradesh subordinate Services Selection Commission",
        "department": "UPSSSC",
        "category": "State",
        "year": "2026",
        "examDate": "2026-07-12",
        "examEndDate": "",
        "releaseDate": "2026-07-02",
        "status": "available",
        "tags": [],
        "downloadLink": "https://upsssc.gov.in/upssscadvdistinti/AdmitCard_wc.aspx?ID=MAIN&L=ac",
        "detailPage": "../AdmitCard_Details/HTML/05-UPSSSC-Main-Exam-Admit-Card-2026.html",
        "updatedAt": "2026-07-02",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0045",
        "title": "BPSC Prosecution Officer Exam Schedule 2026 for 300 Post",
        "organization": "Bihar Public Service Commission",
        "department": "BPSC",
        "category": "State Government",
        "year": "2026",
        "examDate": "2026-07-15",
        "examEndDate": "",
        "releaseDate": "2026-07-02",
        "status": "available",
        "tags": [],
        "downloadLink": "https://bpsconline.bihar.gov.in/candidate/login",
        "detailPage": "../AdmitCard_Details/HTML/06-BPSC-Prosecution-Officer-Admit-Card-2026.html",
        "updatedAt": "2026-07-02",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0028",
        "title": "RRB JE Junior Engineer CBT II Admit Card 2026 for 2569 Post CEN 05/2025",
        "organization": "Railway Recruitment Board",
        "department": "RRB",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-07-02",
        "examEndDate": "",
        "releaseDate": "2026-06-29",
        "status": "exam-over",
        "tags": [],
        "downloadLink": "https://rrb.digialm.com//EForms/configuredHtml/33128/97996/login.html",
        "detailPage": "../AdmitCard_Details/HTML/05-RRB-JE-Junior-Engineer-CBT-II-Admit-Card-2026.html",
        "updatedAt": "2026-06-29",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0027",
        "title": "CG Police SI 2024 Admit Card for 341 Post",
        "organization": "Chhattisgarh Public Service Commission (CGPSC)",
        "department": "CGPSC",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-07-12",
        "examEndDate": "",
        "releaseDate": "2026-06-26",
        "status": "available",
        "tags": [
            "CGPSC",
            "CG Police",
            "SI"
        ],
        "downloadLink": "https://online.ecgpsconline.in/",
        "detailPage": "../AdmitCard_Details/HTML/01-CGPSC-Subedar-SI-Platoon-Commander-Admit-Card-2026.html",
        "updatedAt": "2026-06-27",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0022",
        "title": "Bihar Police BPSSC ASI Operation AdmitCard / Exam Date 2026 for 462 Post",
        "organization": "Bihar Police Subordinate Services Commission (BPSSC)",
        "department": "BPSSC",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-07-22",
        "examEndDate": "",
        "releaseDate": "2026-07-22",
        "status": "upcoming",
        "tags": [
            "BPSSC",
            "Bihar Police",
            "ASI"
        ],
        "downloadLink": "https://bpssc.bihar.gov.in/Notices/Notice%20E-Admit%20Card%20on%20website%203.pdf",
        "detailPage": "../AdmitCard_Details/HTML/07-BPSSC-Bihar-Police-ASI-Operator-Admit-Card-2026.html",
        "updatedAt": "2026-06-26",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0023",
        "title": "UPSSSC Various Post UP Pollution Admit Card 2026 for 115 Post",
        "organization": "Uttar Pradesh Subordinate Services Selection Commission",
        "department": "UPSSSC",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-06-29",
        "examEndDate": "",
        "releaseDate": "2026-06-25",
        "status": "exam-over",
        "tags": [
            "UPSSSC",
            "UP Pollution"
        ],
        "downloadLink": "https://upsssc.gov.in/upssscadmitcard/admitCard.aspx?ID=MAIN",
        "detailPage": "../AdmitCard_Details/HTML/04-UPSSSC-Pharmacist-Admit-Card-2026.html",
        "updatedAt": "2026-06-26",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0024",
        "title": "UPSSSC Pharmacist Admit Card 2026 for 560 Post",
        "organization": "Uttar Pradesh Subordinate Services Selection Commission",
        "department": "UPSSSC",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-06-29",
        "examEndDate": "",
        "releaseDate": "2026-06-25",
        "status": "exam-over",
        "tags": [
            "UPSSSC",
            "Pharmacist"
        ],
        "downloadLink": "https://upsssc.gov.in/upssscadmitcard/admitCard.aspx?ID=MAIN",
        "detailPage": "../AdmitCard_Details/HTML/03-UPSSSC-UP-Pollution-Various-Post-Admit-Card-2026.html",
        "updatedAt": "2026-06-26",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0025",
        "title": "UPSSSC BCG Technician Admit Card 2026 for 255 Post",
        "organization": "Uttar Pradesh Subordinate Services Selection Commission",
        "department": "UPSSSC",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-06-29",
        "examEndDate": "",
        "releaseDate": "2026-06-25",
        "status": "exam-over",
        "tags": [
            "UPSSSC",
            "BCG Technician"
        ],
        "downloadLink": "https://upsssc.gov.in/upssscadmitcard/admitCard.aspx?ID=MAIN",
        "detailPage": "../AdmitCard_Details/HTML/05-UPSSSC-BCG-Technician-Admit-Card-2026.html",
        "updatedAt": "2026-06-26",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0026",
        "title": "PGCIL Non Executive Admit Card 2026 for 670 Post",
        "organization": "Power Grid Corporation of India Limited",
        "department": "PGCIL",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-07-01",
        "examEndDate": "",
        "releaseDate": "2026-06-25",
        "status": "exam-over",
        "tags": [
            "PGCIL",
            "Non Executive"
        ],
        "downloadLink": "https://cdn.digialm.com//EForms/configuredHtml/1258/101292/login.html",
        "detailPage": "../AdmitCard_Details/HTML/06-POWERGRID-Officer-Trainee-CS-Admit-Card-2026.html",
        "updatedAt": "2026-06-26",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0021",
        "title": "ICFRE Various Post Admit Card 2026 for 91 Post",
        "organization": "ICFRE – Forest Research Institute",
        "department": "ICFRE",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-06-29",
        "examEndDate": "2026-06-30",
        "releaseDate": "2026-06-25",
        "status": "exam-over",
        "tags": [
            "ICFRE",
            "Forest Research Institute"
        ],
        "downloadLink": "https://friexam.in/",
        "detailPage": "../AdmitCard_Details/HTML/03-ICFRE-FRI-Various-Post-Admit-Card-2026.html",
        "updatedAt": "2026-06-25",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0020",
        "title": "UPTET Exam City 2026 | UP TET Teacher Eligibility Test",
        "organization": "Uttar Pradesh Education Service Selection Commission (UPESSC)",
        "department": "UPESSB",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-07-02",
        "examEndDate": "2026-07-04",
        "releaseDate": "2026-05-22",
        "status": "exam-over",
        "tags": [
            "UPTET",
            "UPESSC",
            "Teacher"
        ],
        "downloadLink": "https://admitcards.upessc.org/",
        "detailPage": "../AdmitCard_Details/HTML/01-UPTET-Admit-Card-2026.html",
        "updatedAt": "2026-06-23",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0017",
        "title": "UPPSC APO Mains Admit Card 2026 for 182 Post",
        "organization": "UPPSC Assistant Prosecution Officer",
        "department": "uppsc",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-06-28",
        "examEndDate": "2026-06-30",
        "releaseDate": "2026-06-19",
        "status": "exam-over",
        "tags": [
            "UPPSC",
            "APO",
            "Mains"
        ],
        "downloadLink": "https://uppsc.up.nic.in/CandidatePages/AdmitCard/AdmitCard_New.aspx?/8bFzGHgwwQekRCuzX8myYgXeumKuaEdRUSHoDKMVpNo7ipUM5Umm/B6TkvaNJ4jtfCXcIGTdVBq1kfENS1QM2x/lFXCHcndJKOngbu5r70z1Yz+WgYUkLhAqSRXqlbkqNpUeiQfOT8BoNbyeAz77Q==",
        "detailPage": "../AdmitCard_Details/HTML/1106-UPPSC-APO-Mains-Admit-Card-2026.html",
        "updatedAt": "2026-06-19",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0018",
        "title": "Bank of Baroda Apprentice Admit Card 2026 for 5000 Post",
        "organization": "Bank of Baroda",
        "department": "bob",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-06-21",
        "examEndDate": "",
        "releaseDate": "2026-06-19",
        "status": "exam-over",
        "tags": [
            "Bank of Baroda",
            "Apprentice"
        ],
        "downloadLink": "https://bankofbaroda.bank.in/",
        "detailPage": "../AdmitCard_Details/HTML/1107-Bank-of-Baroda-Apprentice-Admit-Card-2026.html",
        "updatedAt": "2026-06-19",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0019",
        "title": "RSSB Forester Admit Card/Exam City Details 2026 for 259 Post",
        "organization": "RSSB",
        "department": "RSSB",
        "category": "Admit card",
        "year": "2026",
        "examDate": "2026-06-28",
        "examEndDate": "",
        "releaseDate": "2026-06-24",
        "status": "exam-over",
        "tags": [
            "RSSB",
            "Forester"
        ],
        "downloadLink": "https://rssb.rajasthan.gov.in/admitcards",
        "detailPage": "../AdmitCard_Details/HTML/1105-RSSB-Vanpal-Admit-Card-2026.html",
        "updatedAt": "2026-06-19",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0016",
        "title": "CSBC Bihar Police Constable GD Special Branch Admit Card 2026",
        "organization": "Central Selection Board of Constable CSBC",
        "department": "State Police",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-06-24",
        "examEndDate": "",
        "releaseDate": "2026-06-17",
        "status": "exam-over",
        "tags": [
            "CSBC",
            "Bihar Police",
            "Constable",
            "Special Branch"
        ],
        "downloadLink": "https://apply-csbc.com/csbc_12026_weadmitcard/searchApplication",
        "detailPage": "../AdmitCard_Details/HTML/01-CSBC-Bihar-Police-Constable-Admit-Card-2026.html",
        "updatedAt": "2026-06-18",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0015",
        "title": "CSBC Bihar Police Constable Operator Exam City / Admit Card 2026 | 993 Post",
        "organization": "Central Selection Board of Constable CSBC",
        "department": "State Police",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-06-28",
        "examEndDate": "",
        "releaseDate": "2026-06-22",
        "status": "exam-over",
        "tags": [
            "CSBC",
            "Bihar Police",
            "Constable",
            "Operator"
        ],
        "downloadLink": "https://apply-csbc.com/csbc_2_2026_weadmitcards/applicationIndex",
        "detailPage": "../AdmitCard_Details/HTML/02-CSBC-Bihar-Police-Constable-Driver-Admit-Card-2026.html",
        "updatedAt": "2026-06-15",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0007",
        "title": "UP Police Constable Admit Card 2026",
        "organization": "Uttar Pradesh Police Recruitment & Promotion Board",
        "department": "State Police",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-06-08",
        "examEndDate": "2026-06-10",
        "releaseDate": "2026-05-31",
        "status": "exam-over",
        "tags": [
            "UPPRPB",
            "Police",
            "Constable"
        ],
        "downloadLink": "https://upcons2025-com.translate.goog/upcondiad2025/loginpage.aspx?_x_tr_sl=en&_x_tr_tl=hi&_x_tr_hl=hi&_x_tr_pto=tc",
        "detailPage": "../Job_Details/HTML/2033-UP-Police_Constable-2026.html",
        "updatedAt": "2026-06-01",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0014",
        "title": "BSNL Senior Executive Trainee",
        "organization": "Bharat Sanchar Nigam Limited",
        "department": "Telecom",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-07-05",
        "examEndDate": "",
        "releaseDate": "2026-05-27",
        "status": "exam-over",
        "tags": [
            "BSNL",
            "Senior Executive Trainee",
            "Telecom"
        ],
        "downloadLink": "https://ibtexamination.com/secuAdmitcard/bsnlAdmitcard03/",
        "detailPage": "../Job_Details/HTML/2395-BSNL-SeniorExecutive-Trainee-2026.html",
        "updatedAt": "2026-05-31",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0013",
        "title": "Indian Army Agniveer CEE Admit Card 2026 – Out",
        "organization": "Join Indian Army",
        "department": "Defence",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-06-01",
        "examEndDate": "2026-06-15",
        "releaseDate": "2026-05-15",
        "status": "exam-over",
        "tags": [
            "Army",
            "Defence",
            "Agniveer"
        ],
        "downloadLink": "https://cdn.digialm.com/EForms/configuredHtml/1258/2000519/login.html",
        "detailPage": "../Job_Details/HTML/2048-Indian-Army-Agniveer-CEE-Admit-Card-2026.html",
        "updatedAt": "2026-05-27",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0012",
        "title": "UKSSSC Group C Driver Admit Card 2026",
        "organization": "Uttarakhand Subordinate Service Selection Commission",
        "department": "UKSSSC",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-06-21",
        "examEndDate": "",
        "releaseDate": "2026-05-25",
        "status": "exam-over",
        "tags": [
            "Driver",
            "Uttarakhad",
            "UKSSSC"
        ],
        "downloadLink": "https://test2.safedotesolution.com/",
        "detailPage": "../Job_Details/HTML/2047-UKSSSC-GroupC-Driver-Admit-2026.html",
        "updatedAt": "2026-05-26",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0010",
        "title": "MPESB Van Rakshak, Jail Prahari Admit Card 2026 for 1679 Post",
        "organization": "Madhya Pradesh Employee Selection Board",
        "department": "Forest Department",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-06-04",
        "examEndDate": "2026-06-19",
        "releaseDate": "2026-05-28",
        "status": "exam-over",
        "tags": [
            "Police",
            "MPESB"
        ],
        "downloadLink": "https://esb.mp.gov.in/tacs/tac_2026/JAIL_VAN_TAC26/default_tac.htm",
        "detailPage": "../Job_Details/HTML/2045-MPESB-Van-Rakshak,-Jail-Prahari-2026.html",
        "updatedAt": "2026-05-25",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0011",
        "title": "BPSSC Bihar Police Havildar Clerk Admit Card 2026",
        "organization": "Bihar Police Subordinate Services Commission",
        "department": "State Police",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-06-10",
        "examEndDate": "",
        "releaseDate": "2026-05-25",
        "status": "exam-over",
        "tags": [
            "Bihar Police"
        ],
        "downloadLink": "https://apply-bpssc.com/bpssc_1_2026_we_admitcards/searchApplication",
        "detailPage": "../Job_Details/HTML/2046-BPSSC-Bihar-Police-Havildar-Clerk-Admit-2026.html",
        "updatedAt": "2026-05-25",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0001",
        "title": "SSC GD Constable Admit Card 2026",
        "organization": "Staff Selection Commission",
        "department": "SSC",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-04-27",
        "examEndDate": "2026-05-30",
        "releaseDate": "2026-04-24",
        "status": "exam-over",
        "tags": [
            "SSC",
            "GD Constable",
            "Admit Card"
        ],
        "downloadLink": "https://ssc.gov.in/login",
        "detailPage": "../Job_Details/HTML/1104-SSC-GD-Constable-2026.html",
        "updatedAt": "2026-05-20",
        "telegramStatus": "draft",
        "telegramReady": "no",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0006",
        "title": "UPSC Civil Services IAS IFS Admit Card 2026",
        "organization": "Union Public Service Commision",
        "department": "UPSC",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-05-24",
        "examEndDate": "",
        "releaseDate": "2026-05-17",
        "status": "exam-over",
        "tags": [
            "UPSC",
            "IAS",
            "IPS",
            "IFS",
            "Central"
        ],
        "downloadLink": "https://upsconline.nic.in/login",
        "detailPage": "../Job_Details/HTML/2032-UPSC-IAS-IFS.html",
        "updatedAt": "2026-05-18",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "admit-sheet-0005",
        "title": "Uttar Pradesh Lekhpal Admit Card 2026",
        "organization": "Uttar Pradesh Subordinate Services Selection Commission",
        "department": "UPSSSC",
        "category": "Admit Card",
        "year": "2026",
        "examDate": "2026-05-21",
        "examEndDate": "",
        "releaseDate": "2026-05-16",
        "status": "exam-over",
        "tags": [
            "upsssc",
            "lekhpal",
            "uttar pradesh"
        ],
        "downloadLink": "https://upsssc.gov.in/upssscadmitcard/admitCard.aspx?ID=MAIN",
        "detailPage": "../Job_Details/HTML/1004-UPSSSC-Lekhpal-job-detail.html",
        "updatedAt": "2026-05-16",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    }
];
