window.govJobIndAdmitCards = [
    {
        id: 1,
        title: "IBPS Clerk Admit Card 2026",
        organization: "Institute of Banking Personnel Selection",
        department: "Banking",
        category: "Admit Card",
        year: "2026",
        examDate: "2026-05-20",
        releaseDate: "2026-05-05",
        status: "upcoming",
        tags: ["IBPS", "Clerk", "Banking"],
        downloadLink: "#",
        detailPage: "../AdmitCard_Details/HTML/admitcard-details-1.html",
        updatedAt: "2026-04-28"
    },
    {
        id: 2,
        title: "SSC JE Paper 1 Admit Card 2026",
        organization: "Staff Selection Commission",
        department: "SSC",
        category: "Admit Card",
        year: "2026",
        examDate: "2026-05-12",
        releaseDate: "2026-04-29",
        status: "available",
        tags: ["SSC", "JE", "Engineering"],
        downloadLink: "https://ssc.gov.in/",
        detailPage: "../AdmitCard_Details/HTML/admitcard-details-2.html",
        updatedAt: "2026-04-30"
    },
    {
        id: 3,
        title: "RBI Grade B Admit Card 2026",
        organization: "Reserve Bank of India",
        department: "Banking",
        category: "Admit Card",
        year: "2026",
        examDate: "2026-06-02",
        releaseDate: "2026-05-18",
        status: "upcoming",
        tags: ["RBI", "Grade B", "Graduate"],
        downloadLink: "#",
        detailPage: "../AdmitCard_Details/HTML/admitcard-details-3.html",
        updatedAt: "2026-04-25"
    },
    {
        id: 4,
        title: "UPSC CDS Admit Card 2026",
        organization: "Union Public Service Commission",
        department: "UPSC",
        category: "Admit Card",
        year: "2026",
        examDate: "2026-05-08",
        releaseDate: "2026-04-24",
        status: "available",
        tags: ["UPSC", "CDS", "Defence"],
        downloadLink: "https://www.upsc.gov.in/",
        detailPage: "../AdmitCard_Details/HTML/admitcard-details-4.html",
        updatedAt: "2026-04-27"
    },
    {
        id: 5,
        title: "SSC CHSL Admit Card 2026",
        organization: "Staff Selection Commission",
        department: "SSC",
        category: "Admit Card",
        year: "2026",
        examDate: "2026-04-22",
        releaseDate: "2026-04-10",
        status: "exam-over",
        tags: ["SSC", "CHSL", "12th Pass"],
        downloadLink: "#",
        detailPage: "../AdmitCard_Details/HTML/admitcard-details-5.html",
        updatedAt: "2026-04-20"
    },
    {
        id: 6,
        title: "IBPS PO Admit Card 2026",
        organization: "Institute of Banking Personnel Selection",
        department: "Banking",
        category: "Admit Card",
        year: "2026",
        examDate: "2026-05-25",
        releaseDate: "2026-05-10",
        status: "upcoming",
        tags: ["IBPS", "PO", "Graduate"],
        downloadLink: "#",
        detailPage: "../AdmitCard_Details/HTML/admitcard-details-6.html",
        updatedAt: "2026-04-23"
    },
    {
        id: 7,
        title: "UPSC Civil Services Prelims Admit Card 2026",
        organization: "Union Public Service Commission",
        department: "UPSC",
        category: "Admit Card",
        year: "2026",
        examDate: "2026-05-15",
        releaseDate: "2026-05-01",
        status: "available",
        tags: ["UPSC", "Civil Services", "Graduate"],
        downloadLink: "https://www.upsc.gov.in/",
        detailPage: "../AdmitCard_Details/HTML/admitcard-details-7.html",
        updatedAt: "2026-04-30"
    },
    {
        id: 8,
        title: "SSC CGL Admit Card 2026",
        organization: "Staff Selection Commission",
        department: "SSC",
        category: "Admit Card",
        year: "2026",
        examDate: "2026-05-30",
        releaseDate: "2026-05-12",
        status: "upcoming",
        tags: ["SSC", "CGL", "Graduate"],
        downloadLink: "#",
        detailPage: "../AdmitCard_Details/HTML/admitcard-details-8.html",
        updatedAt: "2026-04-26"
    }
];
