window.govJobIndAnswerKeys = [
    {
        id: 1,
        title: "SSC CHSL Tier 1 Answer Key 2026",
        organization: "Staff Selection Commission",
        department: "SSC",
        category: "Answer Key",
        year: "2026",
        examDate: "2026-04-12",
        releaseDate: "2026-04-20",
        objectionLastDate: "2026-04-27",
        status: "available",
        tags: ["SSC", "CHSL", "Answer Key"],
        downloadLink: "#",
        objectionLink: "#",
        detailPage: "../AnswerKey_Details/HTML/answerkey-details-1.html",
        updatedAt: "2026-04-22"
    },
    {
        id: 2,
        title: "UPPCS Prelims Answer Key 2026",
        organization: "Uttar Pradesh Public Service Commission",
        department: "State PSC",
        category: "Answer Key",
        year: "2026",
        examDate: "2026-04-18",
        releaseDate: "2026-04-30",
        objectionLastDate: "2026-05-06",
        status: "available",
        tags: ["UPPCS", "UP", "Answer Key"],
        downloadLink: "https://uppsc.up.nic.in/",
        objectionLink: "https://uppsc.up.nic.in/",
        detailPage: "../AnswerKey_Details/HTML/answerkey-details-2.html",
        updatedAt: "2026-04-30"
    },
    {
        id: 3,
        title: "UPSC CDS Answer Key 2026",
        organization: "Union Public Service Commission",
        department: "UPSC",
        category: "Answer Key",
        year: "2026",
        examDate: "2026-05-10",
        releaseDate: "2026-05-20",
        objectionLastDate: "",
        status: "upcoming",
        tags: ["UPSC", "CDS", "Defence"],
        downloadLink: "#",
        objectionLink: "#",
        detailPage: "../AnswerKey_Details/HTML/answerkey-details-3.html",
        updatedAt: "2026-04-24"
    },
    {
        id: 4,
        title: "SSC GD Constable Answer Key 2026",
        organization: "Staff Selection Commission",
        department: "SSC",
        category: "Answer Key",
        year: "2026",
        examDate: "2026-04-02",
        releaseDate: "2026-04-15",
        objectionLastDate: "2026-04-21",
        status: "objection-closed",
        tags: ["SSC", "GD", "Constable"],
        downloadLink: "https://ssc.gov.in/",
        objectionLink: "#",
        detailPage: "../AnswerKey_Details/HTML/answerkey-details-4.html",
        updatedAt: "2026-04-18"
    },
    {
        id: 5,
        title: "UPSSSC PET Answer Key 2026",
        organization: "UP Subordinate Services Selection Commission",
        department: "State SSC",
        category: "Answer Key",
        year: "2026",
        examDate: "2026-04-28",
        releaseDate: "2026-05-08",
        objectionLastDate: "2026-05-15",
        status: "upcoming",
        tags: ["UPSSSC", "PET", "UP"],
        downloadLink: "#",
        objectionLink: "#",
        detailPage: "../AnswerKey_Details/HTML/answerkey-details-5.html",
        updatedAt: "2026-04-26"
    },
    {
        id: 6,
        title: "IBPS PO Prelims Answer Key 2026",
        organization: "Institute of Banking Personnel Selection",
        department: "Banking",
        category: "Answer Key",
        year: "2026",
        examDate: "2026-04-20",
        releaseDate: "2026-04-26",
        objectionLastDate: "2026-05-02",
        status: "available",
        tags: ["IBPS", "PO", "Banking"],
        downloadLink: "#",
        objectionLink: "#",
        detailPage: "../AnswerKey_Details/HTML/answerkey-details-6.html",
        updatedAt: "2026-04-27"
    },
    {
        id: 7,
        title: "UPSC Civil Services Prelims Answer Key 2026",
        organization: "Union Public Service Commission",
        department: "UPSC",
        category: "Answer Key",
        year: "2026",
        examDate: "2026-05-15",
        releaseDate: "2026-05-28",
        objectionLastDate: "",
        status: "upcoming",
        tags: ["UPSC", "Civil Services", "Prelims"],
        downloadLink: "#",
        objectionLink: "#",
        detailPage: "../AnswerKey_Details/HTML/answerkey-details-7.html",
        updatedAt: "2026-04-21"
    },
    {
        id: 8,
        title: "SSC CGL Tier 1 Answer Key 2026",
        organization: "Staff Selection Commission",
        department: "SSC",
        category: "Answer Key",
        year: "2026",
        examDate: "2026-04-10",
        releaseDate: "2026-04-20",
        objectionLastDate: "2026-04-27",
        status: "objection-closed",
        tags: ["SSC", "CGL", "Graduate"],
        downloadLink: "https://ssc.gov.in/",
        objectionLink: "#",
        detailPage: "../AnswerKey_Details/HTML/answerkey-details-8.html",
        updatedAt: "2026-04-30"
    },
    {
        id: 9,
        title: "RBI Grade B Phase I Answer Key 2026",
        organization: "Reserve Bank of India",
        department: "Banking",
        category: "Answer Key",
        year: "2026",
        examDate: "2026-05-04",
        releaseDate: "2026-05-12",
        objectionLastDate: "2026-05-18",
        status: "upcoming",
        tags: ["RBI", "Grade B", "Banking"],
        downloadLink: "#",
        objectionLink: "#",
        detailPage: "../AnswerKey_Details/HTML/answerkey-details-9.html",
        updatedAt: "2026-04-25"
    },
    {
        id: 10,
        title: "SSC JE Paper I Answer Key 2026",
        organization: "Staff Selection Commission",
        department: "SSC",
        category: "Answer Key",
        year: "2026",
        examDate: "2026-04-25",
        releaseDate: "2026-04-30",
        objectionLastDate: "2026-05-05",
        status: "available",
        tags: ["SSC", "JE", "Engineering"],
        downloadLink: "https://ssc.gov.in/",
        objectionLink: "https://ssc.gov.in/",
        detailPage: "../AnswerKey_Details/HTML/answerkey-details-10.html",
        updatedAt: "2026-04-30"
    },
    {
        id: 11,
        title: "IBPS Clerk Prelims Answer Key 2026",
        organization: "Institute of Banking Personnel Selection",
        department: "Banking",
        category: "Answer Key",
        year: "2026",
        examDate: "2026-04-06",
        releaseDate: "2026-04-14",
        objectionLastDate: "2026-04-20",
        status: "objection-closed",
        tags: ["IBPS", "Clerk", "Answer Key"],
        downloadLink: "#",
        objectionLink: "#",
        detailPage: "../AnswerKey_Details/HTML/answerkey-details-11.html",
        updatedAt: "2026-04-17"
    },
    {
        id: 12,
        title: "UPSC NDA Answer Key 2026",
        organization: "Union Public Service Commission",
        department: "UPSC",
        category: "Answer Key",
        year: "2026",
        examDate: "2026-05-22",
        releaseDate: "2026-06-02",
        objectionLastDate: "",
        status: "upcoming",
        tags: ["UPSC", "NDA", "12th Pass"],
        downloadLink: "#",
        objectionLink: "#",
        detailPage: "../AnswerKey_Details/HTML/answerkey-details-12.html",
        updatedAt: "2026-04-23"
    }
];
