// Auto-generated from Google Sheet through Apps Script.
// Source: Answer Keys
// Do not edit manually when sync is enabled.

window.GovJobUpdatesAnswerKeys = [
    {
        "id": "4015",
        "title": "UP Police Home Guard Final Answer Key 2026",
        "organization": "Uttar Pradesh Police Recruitment and Promotion Board",
        "department": "UPPRPB",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-04-25",
        "examEndDate": "2026-04-27",
        "releaseDate": "2026-06-28",
        "objectionLastDate": "",
        "status": "available",
        "tags": [
            "UPPRPB",
            "UP Police",
            "Home Guard",
            "Answer Key"
        ],
        "downloadLink": "https://www.hgupexam2025.com/hg2025finalkey/Login.aspx",
        "objectionLink": "",
        "detailPage": "../AnswerKey_Details/HTML/1105-UP-Home-Guard-Answer-Key-2026.html",
        "updatedAt": "2026-06-28",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "4016",
        "title": "Railway RRB NTPC 10+2 Level UG Answer Key 2026",
        "organization": "Railway Recruittment Board",
        "department": "RRB",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-05-07",
        "examEndDate": "2026-06-21",
        "releaseDate": "2026-06-27",
        "objectionLastDate": "2026-07-05",
        "status": "available",
        "tags": [],
        "downloadLink": "https://rrb.digialm.com/EForms/loginAction.do?subAction=ViewLoginPage&formId=100181&orgId=33128",
        "objectionLink": "https://rrb.digialm.com/EForms/loginAction.do?subAction=ViewLoginPage&formId=100181&orgId=33128",
        "detailPage": "../HTML/answer-key.html",
        "updatedAt": "2026-06-28",
        "telegramStatus": "draft",
        "telegramReady": "no",
        "detailPageSource": "fallback",
        "detailPageNeedsReview": "yes"
    },
    {
        "id": "4014",
        "title": "UPSC ISS Answer Key 2026 for 44 Post",
        "organization": "Union Public Service Commission",
        "department": "IES ISS",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-06-19",
        "examEndDate": "",
        "releaseDate": "2026-06-24",
        "objectionLastDate": "",
        "status": "available",
        "tags": [
            "UPSC",
            "IES ISS",
            "Answer Key"
        ],
        "downloadLink": "https://www.upsc.gov.in/sites/default/files/ProvAnsKey-Statistics-I-ISS-Examination-2026-240626.pdf",
        "objectionLink": "",
        "detailPage": "../AnswerKey_Details/HTML/1105-UPSC-ISS-Statistics-Answer-Key-2026.html",
        "updatedAt": "2026-06-24",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "4012",
        "title": "SSC Delhi Police Head Constable Ministerial Result 2026 | Marks | Final Answer Key",
        "organization": "Staff Selection Commission",
        "department": "SSC",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-01-07",
        "examEndDate": "2026-01-12",
        "releaseDate": "2026-06-22",
        "objectionLastDate": "",
        "status": "available",
        "tags": [
            "SSC",
            "Delhi Police",
            "Head Constable Ministerial",
            "Answer Key"
        ],
        "downloadLink": "https://sscexams.cbexams.com/DPCMpost2025FInalKeyndlandingpage/loginnew.aspx",
        "objectionLink": "",
        "detailPage": "../AnswerKey_Details/HTML/1105-SSC-Delhi-Police-Head-Constable-Answer-Key-2026.html",
        "updatedAt": "2026-06-22",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "4013",
        "title": "MPESB Van Rakshak, Jail Prahari Answer Key 2026 for 1679 Post",
        "organization": "Madhya Pradesh Employee Selection Board (MPESB)",
        "department": "MPESB",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-06-04",
        "examEndDate": "",
        "releaseDate": "2026-06-22",
        "objectionLastDate": "2026-06-25",
        "status": "available",
        "tags": [
            "MPESB",
            "Van Rakshak",
            "Jail Prahari",
            "Answer Key"
        ],
        "downloadLink": "https://jailvancrt2026.cbtexam.in/Home/ListofExam.aspx",
        "objectionLink": "https://jailvancrt2026.cbtexam.in/Home/ListofExam.aspx",
        "detailPage": "../AnswerKey_Details/HTML/1106-MPESB-Van-Rakshak-Jail-Prahari-Answer-Key-2026.html",
        "updatedAt": "2026-06-22",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "4011",
        "title": "UP Police Constable Answer Key 2026 for 32679 Post",
        "organization": "Uttar Pradesh Police Recruitment & Promotion Board",
        "department": "UPPRPB",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-06-08",
        "examEndDate": "2026-06-10",
        "releaseDate": "2026-06-20",
        "objectionLastDate": "2026-06-23",
        "status": "available",
        "tags": [
            "UPPRPB",
            "UP Police",
            "Constable",
            "Answer Key"
        ],
        "downloadLink": "https://upcons2025.com/con2025questionobjections/Login.aspx",
        "objectionLink": "https://upcons2025.com/con2025questionobjections/Login.aspx",
        "detailPage": "../AnswerKey_Details/HTML/1105-UP-Police-Constable-Answer-Key-2025.html",
        "updatedAt": "2026-06-20",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "4009",
        "title": "SSC CGL 2025 Graduate Level Tier II Marks 2026 & Answer Key",
        "organization": "Staff Selection Commission",
        "department": "SSC",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-01-18",
        "examEndDate": "2026-01-19",
        "releaseDate": "2026-06-18",
        "objectionLastDate": "",
        "status": "available",
        "tags": [
            "SSC",
            "CGL",
            "Tier II",
            "Answer Key"
        ],
        "downloadLink": "https://ssc.digialm.com/EForms/configuredHtml/32874/97464/login.html",
        "objectionLink": "",
        "detailPage": "../AnswerKey_Details/HTML/13059-SSC-CGL-Tier-2-Final-Answer-Key-2025.html",
        "updatedAt": "2026-06-18",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "4010",
        "title": "UPPSC GIC Lecturer Government Inter College Answer Key 2026",
        "organization": "Uttar Pradesh Public Service Commission",
        "department": "UPPSC",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-06-14",
        "examEndDate": "2026-06-17",
        "releaseDate": "2026-06-18",
        "objectionLastDate": "",
        "status": "available",
        "tags": [
            "UPPSC",
            "GIC Lecturer",
            "Answer Key"
        ],
        "downloadLink": "https://uppsc.up.nic.in/CandidatePages/Status/ViewAnswerKey.aspx?ID=5",
        "objectionLink": "",
        "detailPage": "../AnswerKey_Details/HTML/3007-UPPSC-GIC-Lecturer-Answer-Key-2026.html",
        "updatedAt": "2026-06-18",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "4005",
        "title": "SSC Delhi Police Head Constable AWO / TPO Final Answer Key with Marks 2026",
        "organization": "Staff Selection Commission",
        "department": "SSC",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-01-15",
        "examEndDate": "2026-01-22",
        "releaseDate": "2026-06-16",
        "objectionLastDate": "",
        "status": "available",
        "tags": [
            "SSC",
            "Delhi Police",
            "AWO TPO",
            "Answer Key"
        ],
        "downloadLink": "https://sscexams.cbexams.com/DPCawoPost2025finalsheetskmdlandingpage/loginnew.aspx",
        "objectionLink": "",
        "detailPage": "../Job_Details/HTML/1000-SSC-DP-AWO-TPO-2025.html",
        "updatedAt": "2026-06-16",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "4006",
        "title": "Rajasthan RSSB Lab Assistant Answer Key 2026",
        "organization": "Rajasthan Staff Selection Board",
        "department": "RSSB",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-05-09",
        "examEndDate": "2026-05-10",
        "releaseDate": "2026-06-16",
        "objectionLastDate": "2026-06-20",
        "status": "available",
        "tags": [
            "RSSB",
            "Lab Assistant",
            "Answer Key"
        ],
        "downloadLink": "https://rssb.rajasthan.gov.in/storage/answerkey_item/1781521971.pdf",
        "objectionLink": "",
        "detailPage": "../AnswerKey_Details/HTML/RSSB-Lab-Assistant-Answer-Key-2026.html",
        "updatedAt": "2026-06-16",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "4004",
        "title": "SSC GD Constable Answer Key 2026 for 25487 Post",
        "organization": "Staff Selection Commission",
        "department": "SSC",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-04-27",
        "examEndDate": "2026-05-30",
        "releaseDate": "2026-06-15",
        "objectionLastDate": "2026-06-20",
        "status": "available",
        "tags": [
            "SSC",
            "GD Constable",
            "Answer Key"
        ],
        "downloadLink": "https://ssc.gov.in/",
        "objectionLink": "https://ssc.gov.in/",
        "detailPage": "../AnswerKey_Details/HTML/1104-SSC-GD-Constable-Answer-Key-2026.html",
        "updatedAt": "2026-06-15",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "4007",
        "title": "UPSSSC Junior Assistant Revised Answer Key 2026 | Advt No 12-Exam/2024",
        "organization": "Uttar Pradesh Subordinate Services Selection Commission",
        "department": "UPSSSC",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-02-01",
        "examEndDate": "",
        "releaseDate": "2026-06-13",
        "objectionLastDate": "",
        "status": "available",
        "tags": [
            "UPSSSC",
            "Junior Assistant",
            "Revised Answer Key"
        ],
        "downloadLink": "https://rojgarresult.com/wp-content/uploads/2026/06/UPSSSC-Revised-Answer-Key-26.pdf",
        "objectionLink": "",
        "detailPage": "../AnswerKey_Details/HTML/UPSSSC-Junior-Assistant-Revised-Answer-Key-2026.html",
        "updatedAt": "2026-06-15",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "4003",
        "title": "UP TGT Answer Key",
        "organization": "UP Secondary Education Service Selection Board",
        "department": "Education",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-06-03",
        "examEndDate": "2026-06-04",
        "releaseDate": "2026-06-07",
        "objectionLastDate": "2026-06-12",
        "status": "avalilable",
        "tags": [
            "UPSESSB UP TGT"
        ],
        "downloadLink": "https://www.upessc.net/tgtqsobj2026/Login.aspx",
        "objectionLink": "#",
        "detailPage": "../AnswerKey_Details/HTML/UP-TGT-2022-Answer-Key-2026.html",
        "updatedAt": "2026-06-07",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "4002",
        "title": "Indian Navy Civilian INCET 01/2025 Answer Key 2026",
        "organization": "Join Indian Navy",
        "department": "Defence",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-02-02",
        "examEndDate": "",
        "releaseDate": "2026-05-29",
        "objectionLastDate": "2026-06-11",
        "status": "available",
        "tags": [
            "Indian Navy",
            "INCET",
            "Civilian"
        ],
        "downloadLink": "https://akc.cbt-exam.in/",
        "objectionLink": "https://akc.cbt-exam.in/",
        "detailPage": "../Job_Details/HTML/2032-UPSC-IAS-IFS.html",
        "updatedAt": "2026-06-06",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "4008",
        "title": "UPPSC Assistant Professor GDC Answer Key 2026 for 1253 Post",
        "organization": "Uttar Pradesh Public Service Commission",
        "department": "UPPSC",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-05-31",
        "examEndDate": "",
        "releaseDate": "2026-06-03",
        "objectionLastDate": "2026-06-09",
        "status": "available",
        "tags": [
            "UPPSC",
            "Assistant Professor",
            "GDC",
            "Answer Key"
        ],
        "downloadLink": "https://uppsc.up.nic.in/CandidatePages/Status/ViewAnswerKey.aspx?ID=5",
        "objectionLink": "",
        "detailPage": "../AnswerKey_Details/HTML/UPPSC-Assistant-Acharya-Answer-Key-2026.html",
        "updatedAt": "2026-06-04",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "4001",
        "title": "UPSC Civil Services IAS IFS Answer Key 2026",
        "organization": "Union Public Service Commission",
        "department": "Civil Services",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-05-24",
        "examEndDate": "",
        "releaseDate": "2026-05-27",
        "objectionLastDate": "",
        "status": "available",
        "tags": [
            "UPSC",
            "CSE Pre",
            "IAS",
            "IFS"
        ],
        "downloadLink": "https://www.upsc.gov.in/sites/default/files/ProvAnsKey%E2%80%93GS-I-CSP-Exam-2026-270526.pdf",
        "objectionLink": "#",
        "detailPage": "../Job_Details/HTML/2032-UPSC-IAS-IFS.html",
        "updatedAt": "2026-05-29",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "4000",
        "title": "UPSSSC Lekhpal Answer Key 2026",
        "organization": "Uttar Pradesh Subordinate Services Selection Commission",
        "department": "Revenue",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-05-21",
        "examEndDate": "",
        "releaseDate": "2026-05-22",
        "objectionLastDate": "",
        "status": "available",
        "tags": [
            "UPSSSC",
            "Lekhpal",
            "Revenue"
        ],
        "downloadLink": "https://drive.google.com/file/d/13w6WvB7OLcx1l0Clntsv3DPqIfXGwnyR/view",
        "objectionLink": "#",
        "detailPage": "../HTML/answer-key.html",
        "updatedAt": "2026-05-27",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "fallback",
        "detailPageNeedsReview": "yes"
    },
    {
        "id": "answerkey-4032",
        "title": "Madhya Pradesh MP Police Subedar Stenographer & ASI Ministerial Answer Key 2025",
        "organization": "Madhya Pradesh Employees Selection Board",
        "department": "Police",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "",
        "examEndDate": "",
        "releaseDate": "2026-04-30",
        "objectionLastDate": "2026-05-03",
        "status": "not available",
        "tags": [
            "MPESB",
            "Police",
            "Steno",
            "ASI"
        ],
        "downloadLink": "https://subsi2025mains.cbtexam.in/Home/ListofExam.aspx",
        "objectionLink": "https://subsi2025mains.cbtexam.in/Home/ListofExam.aspx",
        "detailPage": "../HTML/answer-key.html",
        "updatedAt": "2026-05-07",
        "telegramStatus": "draft",
        "telegramReady": "no",
        "detailPageSource": "fallback",
        "detailPageNeedsReview": "yes"
    },
    {
        "id": "answerkey-4031",
        "title": "UPSSSC Junior Engineer Civi Answer Key 2026",
        "organization": "Uttar Pradesh Subordinate Services Selection Commission",
        "department": "Public Works",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-03-05",
        "examEndDate": "",
        "releaseDate": "2026-05-04",
        "objectionLastDate": "2026-05-10",
        "status": "not available",
        "tags": [
            "UPSSC",
            "JE"
        ],
        "downloadLink": "https://www.adda247.com/jobs/wp-content/uploads/sites/12/2026/05/04191714/UPSSSC-Junior-Engineer-Answer-Key-2026-PDF.pdf",
        "objectionLink": "https://examqp.com/upssscLekhv02n/",
        "detailPage": "../HTML/answer-key.html",
        "updatedAt": "2026-05-07",
        "telegramStatus": "draft",
        "telegramReady": "no",
        "detailPageSource": "fallback",
        "detailPageNeedsReview": "yes"
    },
    {
        "id": "2425",
        "title": "UPSSSC Technical Assistant Group C Answer Key 2026",
        "organization": "Uttar Pradesh Subordinate Services Selection Commission",
        "department": "Agriculture",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "",
        "examEndDate": "",
        "releaseDate": "2025-07-14",
        "objectionLastDate": "",
        "status": "available",
        "tags": [
            "UPSSSC",
            "Technical Assistant",
            "Group C"
        ],
        "downloadLink": "#",
        "objectionLink": "#",
        "detailPage": "../HTML/answer-key.html",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no",
        "detailPageSource": "fallback",
        "detailPageNeedsReview": "yes"
    },
    {
        "id": "answerkey-4027",
        "title": "Rajasthan RSMSSB CHO Answer Key 2026",
        "organization": "Rajasthan Staff Selection Board",
        "department": "Health",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "",
        "examEndDate": "",
        "releaseDate": "2026-05-01",
        "objectionLastDate": "",
        "status": "available",
        "tags": [
            "RSMSSB",
            "CHO",
            "Health"
        ],
        "downloadLink": "#",
        "objectionLink": "#",
        "detailPage": "../HTML/answer-key.html",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no",
        "detailPageSource": "fallback",
        "detailPageNeedsReview": "yes"
    },
    {
        "id": "answerkey-4028",
        "title": "Rajasthan HC Clerk Answer Key 2026",
        "organization": "Rajasthan High Court",
        "department": "Court",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "",
        "examEndDate": "",
        "releaseDate": "2026-05-01",
        "objectionLastDate": "",
        "status": "available",
        "tags": [
            "Rajasthan High Court",
            "Clerk",
            "Answer Key"
        ],
        "downloadLink": "#",
        "objectionLink": "#",
        "detailPage": "../HTML/answer-key.html",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no",
        "detailPageSource": "fallback",
        "detailPageNeedsReview": "yes"
    },
    {
        "id": "answerkey-4029",
        "title": "SSC Junior Hindi Translator JHT Answer Key 2026",
        "organization": "Staff Selection Commission",
        "department": "Staff Selection Commission",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "",
        "examEndDate": "",
        "releaseDate": "2026-05-01",
        "objectionLastDate": "",
        "status": "available",
        "tags": [
            "SSC",
            "JHT",
            "Translator"
        ],
        "downloadLink": "#",
        "objectionLink": "#",
        "detailPage": "../HTML/answer-key.html",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no",
        "detailPageSource": "fallback",
        "detailPageNeedsReview": "yes"
    },
    {
        "id": "answerkey-4030",
        "title": "Rajasthan RPSC FSO Answer Key 2026",
        "organization": "Rajasthan Public Service Commission",
        "department": "Food Safety",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "",
        "examEndDate": "",
        "releaseDate": "2026-05-01",
        "objectionLastDate": "",
        "status": "available",
        "tags": [
            "RPSC",
            "FSO",
            "Food Safety"
        ],
        "downloadLink": "#",
        "objectionLink": "#",
        "detailPage": "../HTML/answer-key.html",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no",
        "detailPageSource": "fallback",
        "detailPageNeedsReview": "yes"
    }
];
