// Auto-generated from Google Sheet through Apps Script.
// Source: Answer Keys
// Do not edit manually when sync is enabled.

window.GovJobUpdatesAnswerKeys = [
    {
        "id": "answerkey-sheet-0037-20260712085340-7448f6fc",
        "title": "RRB Junior Engineer JE CBT-2 Answer Key 2026",
        "organization": "Railway Recruitment Board",
        "department": "RRB",
        "category": "Central Government",
        "year": "2026",
        "examDate": "2026-07-02",
        "examEndDate": "",
        "releaseDate": "2026-07-10",
        "objectionLastDate": "",
        "status": "objection-closed",
        "tags": [],
        "downloadLink": "https://rrb.digialm.com//EForms/configuredHtml/33128/97996/login.html",
        "objectionLink": "https://rrb.digialm.com//EForms/configuredHtml/33128/97996/login.html",
        "detailPage": "../AnswerKey_Details/HTML/RRB-JE-CBT-2-Answer-Key-2026.html",
        "updatedAt": "2026-07-12",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0033-20260710212232-f8feb54f",
        "title": "MPESB Hospital Assistant Answer Key 2026 for 1200 Post",
        "organization": "Madhya Pradesh Employee Selection Board",
        "department": "MPESB",
        "category": "State Government",
        "year": "2026",
        "examDate": "2026-06-24",
        "examEndDate": "",
        "releaseDate": "2026-07-10",
        "objectionLastDate": "2026-07-13",
        "status": "available",
        "tags": [],
        "downloadLink": "https://hospassist2026.cbtexam.in/Home/ListofExam.aspx",
        "objectionLink": "https://hospassist2026.cbtexam.in/Home/ListofExam.aspx",
        "detailPage": "../AnswerKey_Details/HTML/MPESB-Hospital-Assistant-Answer-Key-2026.html",
        "updatedAt": "2026-07-10",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0034-20260710212655-7f411f53",
        "title": "BSNL Senior Executive Trainee SET Answer Key 2026 for 120 Post",
        "organization": "Bhartiya Sanchar Nigam Limited",
        "department": "BSNL",
        "category": "Public Sector",
        "year": "2026",
        "examDate": "2026-07-05",
        "examEndDate": "",
        "releaseDate": "2026-07-10",
        "objectionLastDate": "2026-07-17",
        "status": "available",
        "tags": [],
        "downloadLink": "https://bsnl.examresponse.in/",
        "objectionLink": "https://bsnl.examresponse.in/",
        "detailPage": "../AnswerKey_Details/HTML/BSNL-Senior-Executive-Trainee-SET-Answer-Key-2026.html",
        "updatedAt": "2026-07-10",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0031-20260709122054-03f48df4",
        "title": "SSB Head Constable Answer Key 2026",
        "organization": "Sashastra Seema Bal",
        "department": "SSB",
        "category": "Defence",
        "year": "2026",
        "examDate": "2026-07-07",
        "examEndDate": "",
        "releaseDate": "2026-07-09",
        "objectionLastDate": "2026-07-12",
        "status": "available",
        "tags": [],
        "downloadLink": "https://cdn.digialm.com//EForms/configuredHtml/1258/101413/login.html",
        "objectionLink": "https://cdn.digialm.com//EForms/configuredHtml/1258/101413/login.html",
        "detailPage": "../AnswerKey_Details/HTML/SSB-Head-Constable-Ministerial-Answer-Key-2026.html",
        "updatedAt": "2026-07-09",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0032-20260709213741-935bf6a9",
        "title": "UPPSC Assistant Town Planner Answer Key 2026",
        "organization": "Uttar Pradesh Public Service Commission (UPPSC)",
        "department": "UPPSC",
        "category": "State Government",
        "year": "2026",
        "examDate": "2026-07-07",
        "examEndDate": "",
        "releaseDate": "2026-07-09",
        "objectionLastDate": "2026-07-15",
        "status": "available",
        "tags": [],
        "downloadLink": "https://uppsc.up.nic.in/Open_PDF_DB.aspx?I4PnQ0tBagmjG3pVtCZxxLIYwjGNF6yI",
        "objectionLink": "https://uppsc.up.nic.in/",
        "detailPage": "../AnswerKey_Details/HTML/UPPSC-Assistant-Town-Planner-Answer-Key-2026.html",
        "updatedAt": "2026-07-09",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0030-20260708182144-deaf1cd5",
        "title": "Bihar BPSC Stenographer Answer Key 2026",
        "organization": "BPSC Bihar Stenographer",
        "department": "BBPSC",
        "category": "State Government",
        "year": "2026",
        "examDate": "2026-06-11",
        "examEndDate": "",
        "releaseDate": "2026-07-08",
        "objectionLastDate": "",
        "status": "objection-closed",
        "tags": [],
        "downloadLink": "https://bpsc.bihar.gov.in/wp-content/uploads/BPSC_content/Notices/Advt.-No.01-2026-Stenographer-BPSC-Provisional-Answer-Key-General-Knowledge_BPSC-20260707-erf9pc.pdf",
        "objectionLink": "",
        "detailPage": "../AnswerKey_Details/HTML/BPSC-Stenographer-Answer-Key-2026.html",
        "updatedAt": "2026-07-08",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0028-20260707195337-b16bc566",
        "title": "SSC Delhi Police Constable Executive Final Answer Key with Marks 2026",
        "organization": "Staff Selection Commission",
        "department": "SSC",
        "category": "Central Government",
        "year": "2026",
        "examDate": "2025-12-18",
        "examEndDate": "2026-01-06",
        "releaseDate": "2026-07-07",
        "objectionLastDate": "",
        "status": "objection-closed",
        "tags": [],
        "downloadLink": "https://sscexams.cbexams.com/DPCExecutivep2025EFinalkeydjfdlandingpage/loginnew.aspx",
        "objectionLink": "",
        "detailPage": "../AnswerKey_Details/HTML/Delhi-Police-Constable-Final-Answer-Key-2025.html",
        "updatedAt": "2026-07-07",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0029-20260707223716-0578a187",
        "title": "BPSC AES Assistant Environmental Scientist Answer Key 2026 Adv No 88/2025",
        "organization": "Bihar Public Service Commision",
        "department": "BPSC",
        "category": "State Government",
        "year": "2026",
        "examDate": "2026-06-11",
        "examEndDate": "",
        "releaseDate": "2026-07-07",
        "objectionLastDate": "",
        "status": "objection-closed",
        "tags": [],
        "downloadLink": "https://govjobupdates.com/AnswerKey_Details/HTML/BPSC-Assistant-Environmental-Scientist-Answer-Key-2026.html",
        "objectionLink": "",
        "detailPage": "../AnswerKey_Details/HTML/BPSC-Assistant-Environmental-Scientist-Answer-Key-2026.html",
        "updatedAt": "2026-07-07",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0025",
        "title": "UPSSSC Pharmacist Answer Key 2026 for 560 Post",
        "organization": "Uttar Pradesh Subordinate Services Selection Commission",
        "department": "UPSSSC",
        "category": "State Government",
        "year": "2026",
        "examDate": "2026-06-29",
        "examEndDate": "",
        "releaseDate": "2026-07-02",
        "objectionLastDate": "",
        "status": "objection-closed",
        "tags": [],
        "downloadLink": "https://drive.google.com/file/d/16u-9curqW4ld38YtoUWiQ0ApTcRf8jvQ/view?usp=drivesdk",
        "objectionLink": "https://pharmacist-main-exam-29062026.answer-objections.com/",
        "detailPage": "../AnswerKey_Details/HTML/125-UPSSSC-Pharmacist-Answer-Key-2026.html",
        "updatedAt": "2026-07-03",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0026",
        "title": "UPSSSC Various Post UP Pollution Answer Key 2026 for 115 Post",
        "organization": "Uttar Pradesh Subordinate Services Selection Commission",
        "department": "UPSSSC",
        "category": "State Government",
        "year": "2026",
        "examDate": "2026-06-29",
        "examEndDate": "",
        "releaseDate": "2026-07-02",
        "objectionLastDate": "",
        "status": "objection-closed",
        "tags": [],
        "downloadLink": "https://drive.google.com/file/d/1h6HP6ON2nVejr8iHeIurVrHY85Bc0TfI/view?usp=drivesdk",
        "objectionLink": "https://pollution-control-board-main-exam-29062026.answer-objections.com/",
        "detailPage": "../AnswerKey_Details/HTML/126-UPSSSC-Various-Post-UP-Pollution-Answer-Key-2026.html",
        "updatedAt": "2026-07-03",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0027",
        "title": "UPSSSC BCG Technician Answer Key 2026 for 255 Post",
        "organization": "Uttar Pradesh Subordinate Services Selection Commission",
        "department": "UPSSSC",
        "category": "State Government",
        "year": "2026",
        "examDate": "2026-06-30",
        "examEndDate": "",
        "releaseDate": "2026-07-02",
        "objectionLastDate": "",
        "status": "objection-closed",
        "tags": [],
        "downloadLink": "https://drive.google.com/file/d/1Y62tk0VEv-S3sSOa4I6TRt4NFRIscpmf/view?usp=drivesdk",
        "objectionLink": "https://bcg-technician-main-exam-30062026.answer-objections.com/",
        "detailPage": "../AnswerKey_Details/HTML/127-UPSSSC-BCG-Technician-Answer-Key-2026.html",
        "updatedAt": "2026-07-03",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0023",
        "title": "UP Police Home Guard Final Answer Key 2026",
        "organization": "Uttar Pradesh Police Recruitment and Promotion Board",
        "department": "UPPRPB",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-04-25",
        "examEndDate": "2026-04-27",
        "releaseDate": "2026-06-28",
        "objectionLastDate": "",
        "status": "objection-closed",
        "tags": [
            "UPPRPB",
            "UP Police",
            "Home Guard",
            "Answer Key"
        ],
        "downloadLink": "https://www-hgupexam2025-com.translate.goog/hg2025questionobjections/Login.aspx?_x_tr_sl=en&_x_tr_tl=hi&_x_tr_hl=hi&_x_tr_pto=tc",
        "objectionLink": "",
        "detailPage": "../AnswerKey_Details/HTML/1105-UP-Home-Guard-Answer-Key-2026.html",
        "updatedAt": "2026-06-28",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0024",
        "title": "Railway RRB NTPC 10+2 Level UG Answer Key 2026",
        "organization": "Railway Recruittment Board",
        "department": "RRB",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-05-07",
        "examEndDate": "2026-06-21",
        "releaseDate": "2026-06-27",
        "objectionLastDate": "2026-07-05",
        "status": "objection-closed",
        "tags": [
            "RRB",
            "NTPC",
            "Undergraduate",
            "Answer Key"
        ],
        "downloadLink": "https://digialm.com/EForms/loginAction.do?subAction=ViewLoginPage&formId=100181&orgId=33128",
        "objectionLink": "https://digialm.com/EForms/loginAction.do?subAction=ViewLoginPage&formId=100181&orgId=33128",
        "detailPage": "../AnswerKey_Details/HTML/1106-RRB-NTPC-Undergraduate-Answer-Key-2026.html",
        "updatedAt": "2026-06-28",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0022",
        "title": "UPSC ISS Answer Key 2026 for 44 Post",
        "organization": "Union Public Service Commission",
        "department": "IES ISS",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-06-19",
        "examEndDate": "",
        "releaseDate": "2026-06-24",
        "objectionLastDate": "",
        "status": "objection-closed",
        "tags": [
            "UPSC",
            "IES ISS",
            "Answer Key"
        ],
        "downloadLink": "https://www.upsc.gov.in/sites/default/files/ProvAnsKey-Statistics-I-ISS-Examination-2026-240626.pdf",
        "objectionLink": "",
        "detailPage": "../AnswerKey_Details/HTML/1105-UPSC-ISS-Statistics-Answer-Key-2026.html",
        "updatedAt": "2026-06-24",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0020",
        "title": "SSC Delhi Police Head Constable Ministerial Result 2026 | Marks | Final Answer Key",
        "organization": "Staff Selection Commission",
        "department": "SSC",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-01-07",
        "examEndDate": "2026-01-12",
        "releaseDate": "2026-06-22",
        "objectionLastDate": "",
        "status": "objection-closed",
        "tags": [
            "SSC",
            "Delhi Police",
            "Head Constable Ministerial",
            "Answer Key"
        ],
        "downloadLink": "https://ssc.gov.in/home/answer-key",
        "objectionLink": "",
        "detailPage": "../AnswerKey_Details/HTML/1105-SSC-Delhi-Police-Head-Constable-Answer-Key-2026.html",
        "updatedAt": "2026-06-22",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0021",
        "title": "MPESB Van Rakshak, Jail Prahari Answer Key 2026 for 1679 Post",
        "organization": "Madhya Pradesh Employee Selection Board (MPESB)",
        "department": "MPESB",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-06-04",
        "examEndDate": "",
        "releaseDate": "2026-06-22",
        "objectionLastDate": "2026-06-25",
        "status": "objection-closed",
        "tags": [
            "MPESB",
            "Van Rakshak",
            "Jail Prahari",
            "Answer Key"
        ],
        "downloadLink": "https://jailvancrt2026.cbtexam.in/Home/ListofExam.aspx",
        "objectionLink": "https://jailvancrt2026.cbtexam.in/Home/ListofExam.aspx",
        "detailPage": "../AnswerKey_Details/HTML/1106-MPESB-Van-Rakshak-Jail-Prahari-Answer-Key-2026.html",
        "updatedAt": "2026-06-22",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0019",
        "title": "UP Police Constable Answer Key 2026 for 32679 Post",
        "organization": "Uttar Pradesh Police Recruitment & Promotion Board",
        "department": "UPPRPB",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-06-08",
        "examEndDate": "2026-06-10",
        "releaseDate": "2026-06-20",
        "objectionLastDate": "2026-06-23",
        "status": "objection-closed",
        "tags": [
            "UPPRPB",
            "UP Police",
            "Constable",
            "Answer Key"
        ],
        "downloadLink": "https://upcons2025.com/con2025questionobjections/Login.aspx",
        "objectionLink": "https://upcons2025.com/con2025questionobjections/Login.aspx",
        "detailPage": "../AnswerKey_Details/HTML/1105-UP-Police-Constable-Answer-Key-2025.html",
        "updatedAt": "2026-06-20",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0017",
        "title": "SSC CGL 2025 Graduate Level Tier II Marks 2026 & Answer Key",
        "organization": "Staff Selection Commission",
        "department": "SSC",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-01-18",
        "examEndDate": "2026-01-19",
        "releaseDate": "2026-06-18",
        "objectionLastDate": "",
        "status": "objection-closed",
        "tags": [
            "SSC",
            "CGL",
            "Tier II",
            "Answer Key"
        ],
        "downloadLink": "https://ssc.gov.in/login",
        "objectionLink": "",
        "detailPage": "../AnswerKey_Details/HTML/13059-SSC-CGL-Tier-2-Final-Answer-Key-2025.html",
        "updatedAt": "2026-06-18",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0018",
        "title": "UPPSC GIC Lecturer Government Inter College Answer Key 2026",
        "organization": "Uttar Pradesh Public Service Commission",
        "department": "UPPSC",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-06-14",
        "examEndDate": "2026-06-17",
        "releaseDate": "2026-06-18",
        "objectionLastDate": "",
        "status": "objection-closed",
        "tags": [
            "UPPSC",
            "GIC Lecturer",
            "Answer Key"
        ],
        "downloadLink": "https://uppsc.up.nic.in/CandidatePages/Status/ViewAnswerKey.aspx?ID=5",
        "objectionLink": "",
        "detailPage": "../AnswerKey_Details/HTML/3007-UPPSC-GIC-Lecturer-Answer-Key-2026.html",
        "updatedAt": "2026-06-18",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0013",
        "title": "SSC Delhi Police Head Constable AWO / TPO Final Answer Key with Marks 2026",
        "organization": "Staff Selection Commission",
        "department": "SSC",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-01-15",
        "examEndDate": "2026-01-22",
        "releaseDate": "2026-06-16",
        "objectionLastDate": "",
        "status": "objection-closed",
        "tags": [
            "SSC",
            "Delhi Police",
            "AWO TPO",
            "Answer Key"
        ],
        "downloadLink": "https://ssc.gov.in/home/answer-key",
        "objectionLink": "",
        "detailPage": "../Job_Details/HTML/1000-SSC-DP-AWO-TPO-2025.html",
        "updatedAt": "2026-06-16",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0014",
        "title": "Rajasthan RSSB Lab Assistant Answer Key 2026",
        "organization": "Rajasthan Staff Selection Board",
        "department": "RSSB",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-05-09",
        "examEndDate": "2026-05-10",
        "releaseDate": "2026-06-16",
        "objectionLastDate": "2026-06-20",
        "status": "objection-closed",
        "tags": [
            "RSSB",
            "Lab Assistant",
            "Answer Key"
        ],
        "downloadLink": "https://rssb.rajasthan.gov.in/answerkeys",
        "objectionLink": "",
        "detailPage": "../AnswerKey_Details/HTML/RSSB-Lab-Assistant-Answer-Key-2026.html",
        "updatedAt": "2026-06-16",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0012",
        "title": "SSC GD Constable Answer Key 2026 for 25487 Post",
        "organization": "Staff Selection Commission",
        "department": "SSC",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-04-27",
        "examEndDate": "2026-05-30",
        "releaseDate": "2026-06-15",
        "objectionLastDate": "2026-06-20",
        "status": "objection-closed",
        "tags": [
            "SSC",
            "GD Constable",
            "Answer Key"
        ],
        "downloadLink": "",
        "objectionLink": "",
        "detailPage": "../AnswerKey_Details/HTML/1104-SSC-GD-Constable-Answer-Key-2026.html",
        "updatedAt": "2026-06-15",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0015",
        "title": "UPSSSC Junior Assistant Revised Answer Key 2026 | Advt No 12-Exam/2024",
        "organization": "Uttar Pradesh Subordinate Services Selection Commission",
        "department": "UPSSSC",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-02-01",
        "examEndDate": "",
        "releaseDate": "2026-06-13",
        "objectionLastDate": "",
        "status": "objection-closed",
        "tags": [
            "UPSSSC",
            "Junior Assistant",
            "Revised Answer Key"
        ],
        "downloadLink": "https://upsssc.gov.in//ViewPdf.aspx?Th5pjtpsOqjEsS8JwaHQwIv7OWMDoSsFY1/GMj346y4=",
        "objectionLink": "",
        "detailPage": "../AnswerKey_Details/HTML/UPSSSC-Junior-Assistant-Revised-Answer-Key-2026.html",
        "updatedAt": "2026-06-15",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0011",
        "title": "UP TGT Answer Key",
        "organization": "UP Secondary Education Service Selection Board",
        "department": "Education",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-06-03",
        "examEndDate": "2026-06-04",
        "releaseDate": "2026-06-07",
        "objectionLastDate": "2026-06-12",
        "status": "objection-closed",
        "tags": [
            "UPSESSB UP TGT"
        ],
        "downloadLink": "https://www.upessc.net/tgtqsobj2026/Login.aspx",
        "objectionLink": "#",
        "detailPage": "../AnswerKey_Details/HTML/UP-TGT-2022-Answer-Key-2026.html",
        "updatedAt": "2026-06-07",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0010",
        "title": "Indian Navy Civilian INCET 01/2025 Answer Key 2026",
        "organization": "Join Indian Navy",
        "department": "Defence",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-02-02",
        "examEndDate": "",
        "releaseDate": "2026-05-29",
        "objectionLastDate": "2026-06-11",
        "status": "objection-closed",
        "tags": [
            "Indian Navy",
            "INCET",
            "Civilian"
        ],
        "downloadLink": "https://akc.cbt-exam.in/",
        "objectionLink": "https://akc.cbt-exam.in/",
        "detailPage": "../Job_Details/HTML/2032-UPSC-IAS-IFS.html",
        "updatedAt": "2026-06-06",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0016",
        "title": "UPPSC Assistant Professor GDC Answer Key 2026 for 1253 Post",
        "organization": "Uttar Pradesh Public Service Commission",
        "department": "UPPSC",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-05-31",
        "examEndDate": "",
        "releaseDate": "2026-06-03",
        "objectionLastDate": "2026-06-09",
        "status": "objection-closed",
        "tags": [
            "UPPSC",
            "Assistant Professor",
            "GDC",
            "Answer Key"
        ],
        "downloadLink": "https://uppsc.up.nic.in/CandidatePages/Status/ViewAnswerKey.aspx?ID=5",
        "objectionLink": "",
        "detailPage": "../AnswerKey_Details/HTML/UPPSC-Assistant-Acharya-Answer-Key-2026.html",
        "updatedAt": "2026-06-04",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0009",
        "title": "UPSC Civil Services IAS IFS Answer Key 2026",
        "organization": "Union Public Service Commission",
        "department": "Civil Services",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-05-24",
        "examEndDate": "",
        "releaseDate": "2026-05-27",
        "objectionLastDate": "",
        "status": "objection-closed",
        "tags": [
            "UPSC",
            "CSE Pre",
            "IAS",
            "IFS"
        ],
        "downloadLink": "https://sarkariresult.com.im/wp-content/uploads/2026/05/UPSC-Civil-Services-Answer-GS-Paper-1.pdf",
        "objectionLink": "#",
        "detailPage": "../Job_Details/HTML/2032-UPSC-IAS-IFS.html",
        "updatedAt": "2026-05-29",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    },
    {
        "id": "answerkey-sheet-0008",
        "title": "UPSSSC Lekhpal Answer Key 2026",
        "organization": "Uttar Pradesh Subordinate Services Selection Commission",
        "department": "Revenue",
        "category": "Answer Key",
        "year": "2026",
        "examDate": "2026-05-21",
        "examEndDate": "",
        "releaseDate": "2026-05-22",
        "objectionLastDate": "",
        "status": "objection-closed",
        "tags": [
            "UPSSSC",
            "Lekhpal",
            "Revenue"
        ],
        "downloadLink": "https://drive.google.com/file/d/13w6WvB7OLcx1l0Clntsv3DPqIfXGwnyR/view",
        "objectionLink": "#",
        "detailPage": "../Job_Details/HTML/1004-UPSSSC-Lekhpal-job-detail.html",
        "updatedAt": "2026-05-27",
        "telegramStatus": "ready",
        "telegramReady": "yes",
        "detailPageSource": "sheet",
        "detailPageNeedsReview": "no"
    }
];
