// Auto-generated from Google Sheet through Apps Script.
// Source: Latest Jobs
// Do not edit manually when sync is enabled.

window.GovJobUpdatesJobs = [
    {
        "id": "2426",
        "title": "RSSB Computer Instructor Online Form 2026 for 3951 Post",
        "organization": "Rajasthan Staff Selection Board",
        "department": "Education",
        "category": "State Government",
        "year": "2026",
        "qualification": "Graduate and Masters (View Details for More Information)",
        "totalPosts": "3951",
        "startDate": "2026-05-25",
        "lastDate": "2026-06-23",
        "status": "active",
        "tags": [
            "Education",
            "Rajsthan",
            "Teacher",
            "RPSC",
            "Computer"
        ],
        "applyLink": "https://sso.rajasthan.gov.in/signin?encq=6JkTF7D/fPuyiLpqlTuv+tsssIL22cKEce/qYZMZKsM=",
        "officialNotification": "https://rssb.rajasthan.gov.in/storage/advertisement_item/1779453807.pdf",
        "detailPage": "./Job_Details/HTML/2426-RSSB-Computer-Instructor-Online-Form-2026.html",
        "updatedAt": "2026-05-25",
        "telegramStatus": "ready",
        "telegramReady": "yes"
    },
    {
        "id": "2428",
        "title": "NALCO Non Executive Online Form 2026 for 268 Post",
        "organization": "National Aluminium Company Limited",
        "department": "Metals",
        "category": "Public Sector",
        "year": "2026",
        "qualification": "ITI / Diploma / Graduation Passed form any Recognized University/Institute in India (View Details for more Information)",
        "totalPosts": "268",
        "startDate": "2026-05-21",
        "lastDate": "2026-06-10",
        "status": "active",
        "tags": [
            "almunium",
            "Public Sector",
            "Metal"
        ],
        "applyLink": "https://recruitment.nhidcl.com/login",
        "officialNotification": "https://mudira.nalcoindia.co.in/iorms/Uploaded_Data/Advertisement/639144655968105605_Final%20Adv%2010260213%2014%20May2026.pdf",
        "detailPage": "./Job_Details/HTML/2428-NALCO-Non-Executive-Recruitment-2026.html",
        "updatedAt": "2026-05-25",
        "telegramStatus": "ready",
        "telegramReady": "yes"
    },
    {
        "id": "2429",
        "title": "EDCIL Various Post Online Form 2026 for 879 Post",
        "organization": "EDCIL India Limited",
        "department": "Medical Education",
        "category": "Central Government",
        "year": "",
        "qualification": "10+2 (View Details for more Information)",
        "totalPosts": "879",
        "startDate": "2026-05-22",
        "lastDate": "2026-06-04",
        "status": "active",
        "tags": [
            "Medical",
            "Physiotherapy"
        ],
        "applyLink": "https://tsgrecruitment.edcil.co.in/login",
        "officialNotification": "https://www.edcilindia.co.in/Default/ViewFile/?id=1779401966084_Deatailed%20Advertisment%20for%20the%20Recruitment%20of%20875%20Multidisciplinary%20Staff%20(Inclusive%20Education-AP).pdf&path=TCareer",
        "detailPage": "./Job_Details/HTML/2429-EDCIL-Various-Posts-Recruitment-2026.html",
        "updatedAt": "2026-05-25",
        "telegramStatus": "ready",
        "telegramReady": "yes"
    },
    {
        "id": "2424",
        "title": "Indian Navy 10+2 B.Tech Cadet Entry Online Form 2026",
        "organization": "Join Indian Navy",
        "department": "Defence",
        "category": "Central Government",
        "year": "2026",
        "qualification": "Passed Senior Secondary Examination (10+2 Pattern) or its Equivalent Examination from any Recognized Board with at least 70% aggregate marks in Physics, Chemistry and Mathematics (PCM) and at least 50% marks in English (either in Class X or Class XII)",
        "totalPosts": "60",
        "startDate": "2026-05-29",
        "lastDate": "2026-06-18",
        "status": "upcoming",
        "tags": [
            "Navy",
            "Defence",
            "Indian Army"
        ],
        "applyLink": "#",
        "officialNotification": "https://www.joinindiannavy.gov.in/files/Advertisement_10+2_B.Tech_Jan_27.pdf",
        "detailPage": "./Job_Details/HTML/2424-Indian-Navy-10-2-BTech-Cadet-Entry-2026.html",
        "updatedAt": "2026-05-24",
        "telegramStatus": "ready",
        "telegramReady": "yes"
    },
    {
        "id": "2425",
        "title": "UPSSSC Technical Assistant Group C Online Form 2026 for 2759 Post",
        "organization": "Uttar Pradesh Subordinate Services Selection Commission",
        "department": "Engineering",
        "category": "State Government",
        "year": "2026",
        "qualification": "UPSSSC PET 2025 Score Card.\nGraduation Degree In Agriculture B.Sc Agriculture / Horticulture /Home Science / Forestery OR B.E / B.Tech Engineering Degree In Agriculture",
        "totalPosts": "2759",
        "startDate": "2026-05-22",
        "lastDate": "2026-06-11",
        "status": "active",
        "tags": [
            "Engineering",
            "Assistant",
            "UPSSSC"
        ],
        "applyLink": "https://upsssc.gov.in/AllNotifications.aspx",
        "officialNotification": "https://upsssc.gov.in/ViewPdf.aspx?tOQhA8AoFpWKZKwi+DnPk65dPKCM/WfAewISjjqbPGo=",
        "detailPage": "./Job_Details/HTML/2425-UPSSSC-Technical-Assistant-Group-C-2026.html",
        "updatedAt": "2026-05-24",
        "telegramStatus": "ready",
        "telegramReady": "yes"
    },
    {
        "id": "2422",
        "title": "Punjab & Sindh Bank Apprentice Online Form 2026 for 635",
        "organization": "Punjab and Sindh Bank",
        "department": "Banking",
        "category": "Banking",
        "year": "2026",
        "qualification": "Graduation (View Details for more Information)",
        "totalPosts": "635",
        "startDate": "2026-05-21",
        "lastDate": "2026-06-06",
        "status": "active",
        "tags": [
            "Banking",
            "Punjab and Singh Bank",
            "IBPS"
        ],
        "applyLink": "https://ibpsreg.ibps.in/psbeoaapr26/",
        "officialNotification": "",
        "detailPage": "./Job_Details/HTML/2422-P&S-Apprentice-2026.html",
        "updatedAt": "2026-05-23",
        "telegramStatus": "ready",
        "telegramReady": "yes"
    },
    {
        "id": "2423",
        "title": "RPSC School Lecturer Special Education Online Form 2026 for 121 Post",
        "organization": "Rajasthan Public Service Commission",
        "department": "Education",
        "category": "State Government",
        "year": "2026",
        "qualification": "Post Graduation (View Details for more Information)",
        "totalPosts": "121",
        "startDate": "2026-06-01",
        "lastDate": "2026-06-30",
        "status": "upcoming",
        "tags": [
            "Education",
            "Rajsthan",
            "Teacher",
            "RPSC"
        ],
        "applyLink": "#",
        "officialNotification": "https://rpsc.rajasthan.gov.in/Static/RecruitmentAdvertisements/20787BD8A34D461A80CD78EE212A5723.pdf",
        "detailPage": "./Job_Details/HTML/2423-RPSC-School-Lecturer-Special-Education-2026.html",
        "updatedAt": "2026-05-23",
        "telegramStatus": "ready",
        "telegramReady": "yes"
    },
    {
        "id": "2427",
        "title": "Punjab and Haryana High Court Clerk Online Form 2026 for 1265 Post",
        "organization": "High Court of Punjab and Haryana SSSC",
        "department": "Judiciary",
        "category": "State Government",
        "year": "2026",
        "qualification": "Graduation (View Details for more Information)",
        "totalPosts": "1265",
        "startDate": "2026-05-26",
        "lastDate": "2026-06-23",
        "status": "upcoming",
        "tags": [
            "Judiciary",
            "Punjab",
            "Haryana",
            "Chandigarh"
        ],
        "applyLink": "#",
        "officialNotification": "#",
        "detailPage": "./Job_Details/HTML/job-details.html?id=2427",
        "updatedAt": "2026-05-23",
        "telegramStatus": "ready",
        "telegramReady": "yes"
    },
    {
        "id": "2418",
        "title": "AFCAT 02/2026 Online Form",
        "organization": "Indian Air Force",
        "department": "IAF",
        "category": "Central Government",
        "year": "2026",
        "qualification": "",
        "totalPosts": "361",
        "startDate": "2026-05-20",
        "lastDate": "2026-06-19",
        "status": "active",
        "tags": [
            "Indian Air Force",
            "VayuSena",
            "IAF"
        ],
        "applyLink": "https://cdn.digialm.com/EForms/configuredHtml/1258/100343/login.html",
        "officialNotification": "https://afcat.edcil.co.in/assets/images/news/AFCAT_02_2026/Notification%20for%20AFCAT%20Cycle%2002-2026.pdf",
        "detailPage": "./Job_Details/HTML/2418-Indian-Air-Force-AFCAT-02-2026",
        "updatedAt": "2026-05-21",
        "telegramStatus": "ready",
        "telegramReady": "yes"
    },
    {
        "id": "2421",
        "title": "SSC CGL 2026",
        "organization": "Staff Selection Commission",
        "department": "SSC",
        "category": "Central Government",
        "year": "2026",
        "qualification": "Graduation (View Details for more Information)",
        "totalPosts": "approx. 12256",
        "startDate": "2026-05-21",
        "lastDate": "2026-06-22",
        "status": "active",
        "tags": [
            "SSC",
            "Income Tax",
            "Revenue",
            "Excise"
        ],
        "applyLink": "https://ssc.gov.in/",
        "officialNotification": "https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/Notice_of_adv_cgl_2026.pdf",
        "detailPage": "./Job_Details/HTML/2421-SSC-CGL-2026.html",
        "updatedAt": "2026-05-21",
        "telegramStatus": "ready",
        "telegramReady": "yes"
    },
    {
        "id": "2417",
        "title": "CSIR CIMFR Technician/Grade II Online Form 2026",
        "organization": "Council of Scientific & Industrial Research",
        "department": "CSIR",
        "category": "Central Government",
        "year": "2026",
        "qualification": "Class 10 High School / Matric with 50% Marks\n(View Details for More Information)",
        "totalPosts": "30",
        "startDate": "2026-05-20",
        "lastDate": "2026-06-18",
        "status": "active",
        "tags": [
            "Scientist",
            "Central",
            "ITI"
        ],
        "applyLink": "https://devapps.ngri.res.in/CIMFR_group2_2026/index.jsp",
        "officialNotification": "https://cimfr.res.in/upload_files/current_opportunity/1779249926_Tech.pdf",
        "detailPage": "./Job_Details/HTML/2417-CSIR-CIMFR-Technician-Recruitment-2026.html",
        "updatedAt": "2026-05-20",
        "telegramStatus": "ready",
        "telegramReady": "yes"
    },
    {
        "id": "2419",
        "title": "UPSC NDA II Online Form 2026 for 394 Post",
        "organization": "Union Public Service Commission",
        "department": "Defence",
        "category": "Central Government",
        "year": "2026",
        "qualification": "10+2 (View Details for more Information)",
        "totalPosts": "394",
        "startDate": "2026-05-20",
        "lastDate": "2026-06-09",
        "status": "active",
        "tags": [
            "NDA",
            "Indian Army",
            "UPSC",
            "Defence"
        ],
        "applyLink": "https://upsconline.nic.in/ora/ora-candidate/realms/candidate-portal/protocol/openid-connect/auth?client_id=account&redirect_uri=https%3A%2F%2Fupsconline.nic.in%2Fora%2Fora-candidate%2Frealms%2Fcandidate-portal%2Faccount%2Flogin-redirect&state=0%2Fc096ae39-e65b-be28-022d-cf10ebd3c835&response_type=code&scope=openid",
        "officialNotification": "https://upsc.gov.in/sites/default/files/Notif-NDA-II-2026-Engl-200526.pdf",
        "detailPage": "./Job_Details/HTML/2419-UPSC-NDA-II-2026.html",
        "updatedAt": "2026-05-20",
        "telegramStatus": "ready",
        "telegramReady": "yes"
    },
    {
        "id": "2420",
        "title": "UPSC CDS II Online Form 2026 for 451 Post",
        "organization": "Union Public Service Commission",
        "department": "Defence",
        "category": "Central Government",
        "year": "2026",
        "qualification": "Graduation (View Details for more Information)",
        "totalPosts": "451",
        "startDate": "2026-05-20",
        "lastDate": "2026-06-09",
        "status": "active",
        "tags": [
            "CDS",
            "Defence",
            "Indian Army",
            "UPSC"
        ],
        "applyLink": "https://upsconline.nic.in/ora/ora-candidate/realms/candidate-portal/protocol/openid-connect/auth?client_id=account&redirect_uri=https%3A%2F%2Fupsconline.nic.in%2Fora%2Fora-candidate%2Frealms%2Fcandidate-portal%2Faccount%2Flogin-redirect&state=0%2Fc096ae39-e65b-be28-022d-cf10ebd3c835&response_type=code&scope=openid",
        "officialNotification": "https://upsc.gov.in/sites/default/files/Notif-CDS-II-2026-Engl-200526.pdf",
        "detailPage": "./Job_Details/HTML/2420-UPSC-CDS-II-2026.html",
        "updatedAt": "2026-05-20",
        "telegramStatus": "ready",
        "telegramReady": "yes"
    },
    {
        "id": "job-sheet-31",
        "title": "BTSC Laboratory Assistant Online Form 2026 for 1090 Post",
        "organization": "Bihar Technichal Service Commision",
        "department": "BTSC",
        "category": "State Government",
        "year": "2026",
        "qualification": "Diploma or Graduate",
        "totalPosts": "1090",
        "startDate": "2026-04-06",
        "lastDate": "2026-05-06",
        "status": "active",
        "tags": [
            "BTSC",
            "Laboratory Assistant",
            "Bihar"
        ],
        "applyLink": "https://btsc.pariksha.nic.in/Agencies.aspx?KZhCrm9B4QPkl0gO2rAMuw==",
        "officialNotification": "https://btsc.pariksha.nic.in/Online_App/Notifications.aspx",
        "detailPage": "#",
        "updatedAt": "2026-05-07",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "job-sheet-32",
        "title": "NTPC Assistant Executive Online Form 2026 for 250 Post",
        "organization": "NTPC",
        "department": "NTPC",
        "category": "Public Sector",
        "year": "2026",
        "qualification": "Engineering",
        "totalPosts": "250",
        "startDate": "2026-04-23",
        "lastDate": "2026-05-07",
        "status": "active",
        "tags": [
            "NTPC",
            "Engineering",
            "Assistant"
        ],
        "applyLink": "https://careers.ntpc.co.in/recruitment/index.php",
        "officialNotification": "https://careers.ntpc.co.in/recruitment/pdf_viewer.php?token=VHZtc0k0eU5VMTFNcFNuQ0V1MnNNUDRMLyt0VVhVeHRwK2s5Q1BTRHBxcWdzUlBPaHA1UkJmdjRSaFBxTDM3Wkp3QXMwOXdUajdTMmYvS2pac2ExdWtwcWhtUWxSOUxXZW4weStFQjlKMkE9OjpXWHZWVTBJczk4TDVNaS9tcTRvc3l3PT0%3D",
        "detailPage": "#",
        "updatedAt": "2026-05-07",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2386",
        "title": "Rajasthan RSSB Teaching Associate Online Form 2026 (3540 Posts)",
        "organization": "Rajasthan Staff Selection Board",
        "department": "Teaching",
        "category": "Teaching",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "3540",
        "startDate": "2026-05-01",
        "lastDate": "2026-06-03",
        "status": "active",
        "tags": [
            "RSSB",
            "Rajasthan",
            "Teaching"
        ],
        "applyLink": "https://sso.rajasthan.gov.in/signin?encq=6JkTF7D/fPuyiLpqlTuv+tsssIL22cKEce/qYZMZKsM=",
        "officialNotification": "https://rssb.rajasthan.gov.in/storage/advertisement_item/1777546753.pdf",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2386",
        "updatedAt": "2026-05-01",
        "telegramStatus": "ready",
        "telegramReady": "yes"
    },
    {
        "id": "2387",
        "title": "CRPF Constable Tradesman Online Form 2026 (9195 Posts)",
        "organization": "Central Reserve Police Force",
        "department": "Defence",
        "category": "Defence",
        "year": "2026",
        "qualification": "High School (View Details for More Information)",
        "totalPosts": "9195",
        "startDate": "2026-05-01",
        "lastDate": "2026-05-19",
        "status": "active",
        "tags": [
            "CRPF",
            "Constable",
            "Tradesman"
        ],
        "applyLink": "https://recruitment.crpf.gov.in/login",
        "officialNotification": "https://rect.crpf.gov.in/Upload/Recruitment/Recruitment%20Notice%20103042026-720.pdf",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2387",
        "updatedAt": "2026-05-01",
        "telegramStatus": "ready",
        "telegramReady": "yes"
    },
    {
        "id": "2388",
        "title": "Railway RRB ALP Online Form 2026 (11127 Posts)",
        "organization": "Railway Recruitment Board",
        "department": "Railway",
        "category": "Railway",
        "year": "2026",
        "qualification": "High School (View Details for More Information)",
        "totalPosts": "11127",
        "startDate": "2026-05-01",
        "lastDate": "2026-06-14",
        "status": "active",
        "tags": [
            "RRB",
            "ALP",
            "Railway"
        ],
        "applyLink": "https://www.rrbapply.gov.in/#/auth/home",
        "officialNotification": "https://rrbajmer.gov.in/Upload_PDF/CEN%2001-2026%20Eng-639143539720035538.pdf",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2388",
        "updatedAt": "2026-05-01",
        "telegramStatus": "ready",
        "telegramReady": "yes"
    },
    {
        "id": "2389",
        "title": "MPESB Nursing Officer / Sister Tutor Online Form 2026",
        "organization": "Madhya Pradesh Employee Selection Board",
        "department": "Health",
        "category": "Health",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "2317",
        "startDate": "2026-05-01",
        "lastDate": "2026-05-03",
        "status": "active",
        "tags": [
            "MPESB",
            "Nursing Officer",
            "Sister Tutor"
        ],
        "applyLink": "https://esb.mponline.gov.in/Portal/Examinations/Vyapam/examsList.aspx",
        "officialNotification": "https://esb.mp.gov.in/Rulebooks/RB_2026/Health_Nursing_2026RuleBook02_04_2026.pdf",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2389",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2390",
        "title": "MPESB Hospital Assistant Online Form 2026",
        "organization": "Madhya Pradesh Employee Selection Board",
        "department": "Health",
        "category": "Health",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "1200",
        "startDate": "2026-05-01",
        "lastDate": "2026-05-21",
        "status": "active",
        "tags": [
            "MPESB",
            "Hospital Assistant",
            "Health"
        ],
        "applyLink": "https://esb.mponline.gov.in/Portal/Examinations/Vyapam/examsList.aspx",
        "officialNotification": "https://esb.mp.gov.in/Rulebooks/RB_2026/Hospital_Assistant_rulebook_2026_30042026.pdf",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2390",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2391",
        "title": "MPESB Van Rakshak / Jail Prahari Online Form 2026",
        "organization": "Madhya Pradesh Employee Selection Board",
        "department": "Forest and Jail",
        "category": "State Government",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "1679",
        "startDate": "2026-05-01",
        "lastDate": "2026-04-30",
        "status": "closed",
        "tags": [
            "MPESB",
            "Van Rakshak",
            "Jail Prahari"
        ],
        "applyLink": "https://esb.mponline.gov.in/Portal/Examinations/Vyapam/examsList.aspx",
        "officialNotification": "https://esb.mp.gov.in/Rulebooks/RB_2026/JAIL_VAN_2026_RuleBook_Updated_PAGES_16042026.pdf",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2391",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2392",
        "title": "Bihar BPSC 33rd Judicial Services Online Form 2026",
        "organization": "Bihar Public Service Commission",
        "department": "Judiciary",
        "category": "State PSC",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "173",
        "startDate": "2026-05-01",
        "lastDate": "2026-04-30",
        "status": "closed",
        "tags": [
            "BPSC",
            "Judicial Services",
            "Bihar"
        ],
        "applyLink": "https://bpsconline.bihar.gov.in/candidate/login",
        "officialNotification": "https://bpsc.bihar.gov.in/wp-content/uploads/BPSC_content/Notices/Advertisement-122026-33rd-BJSE_BPSC-20260223-82eskn.pdf",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2392",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2393",
        "title": "Patna High Court Technical Assistant Online Form 2026",
        "organization": "Patna High Court",
        "department": "Court",
        "category": "Judiciary",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "53",
        "startDate": "2026-05-01",
        "lastDate": "2026-04-30",
        "status": "closed",
        "tags": [
            "Patna High Court",
            "Technical Assistant",
            "Bihar"
        ],
        "applyLink": "https://phc-recruitment.com/",
        "officialNotification": "https://patnahighcourt.gov.in/getfile/MTA0NTQ=-q0vlRLd1RTE=",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2393",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2394",
        "title": "NPCIL Executive Trainee Online Form 2026",
        "organization": "Nuclear Power Corporation of India Limited",
        "department": "Public Sector",
        "category": "Public Sector",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "330",
        "startDate": "2026-05-01",
        "lastDate": "2026-04-30",
        "status": "closed",
        "tags": [
            "NPCIL",
            "Executive Trainee",
            "PSU"
        ],
        "applyLink": "https://www.npcilcareers.co.in/ETHQ10042026/candidate/default.aspx",
        "officialNotification": "https://www.npcilcareers.co.in/ETHQ10042026/documents/advt.pdf",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2394",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2395",
        "title": "BSNL Senior Executive Trainee Online Form 2026",
        "organization": "Bharat Sanchar Nigam Limited",
        "department": "Telecom",
        "category": "Public Sector",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "120",
        "startDate": "2026-05-01",
        "lastDate": "2026-04-30",
        "status": "closed",
        "tags": [
            "BSNL",
            "Senior Executive Trainee",
            "Telecom"
        ],
        "applyLink": "https://bsnlregistration.ibtexamination.com/",
        "officialNotification": "https://bsnl.co.in/documents/jobs/SET_Notification_29012026.pdf",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2395",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2396",
        "title": "Bihar BCECE Senior Resident / Tutor Online Form 2026",
        "organization": "Bihar Combined Entrance Competitive Examination Board",
        "department": "Medical Education",
        "category": "Health",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "642",
        "startDate": "2026-05-01",
        "lastDate": "2026-04-30",
        "status": "closed",
        "tags": [
            "BCECE",
            "Senior Resident",
            "Tutor"
        ],
        "applyLink": "https://admissions.nic.in/Bihar/Applicant/Root/OTHome.aspx?enc=k5U5Gp8NR6abhZ8Lld4oWvvSsCkKcG+Kcizck0pVdCvJE10jNAB9fCwdCq9SngLzv5wfQK8DbPTS5JsnelmH5g==",
        "officialNotification": "https://bceceboard.bihar.gov.in/pdf_Adv/ADV_SR26_01.pdf",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2396",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2397",
        "title": "LIC HFL Junior Assistant Online Form 2026",
        "organization": "LIC Housing Finance Limited",
        "department": "Banking",
        "category": "Banking",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "180",
        "startDate": "2026-05-01",
        "lastDate": "2026-04-30",
        "status": "closed",
        "tags": [
            "LIC HFL",
            "Junior Assistant",
            "Banking"
        ],
        "applyLink": "https://ibpsreg.ibps.in/licjamar26/",
        "officialNotification": "https://cdn.lichousing.com/2026/04/Detailed-Advertisement-Recruitment-of-Junior-Assistants-2026.pdf",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2397",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2398",
        "title": "BPSSC Bihar Police Havildar Instructor Online Form 2026",
        "organization": "Bihar Police Subordinate Services Commission",
        "department": "Police",
        "category": "Police",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "1865",
        "startDate": "2026-05-01",
        "lastDate": "2026-06-01",
        "status": "active",
        "tags": [
            "BPSSC",
            "Bihar Police",
            "Havildar Instructor"
        ],
        "applyLink": "https://apply-bpssc.com/bpssc_havr_clerk_5_26_v1/applicationIndex",
        "officialNotification": "https://bpssc.bihar.gov.in/Notices/Advt.%20no.-05-2026.pdf",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2398",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2399",
        "title": "Union Bank of India Apprentice Online Form 2026",
        "organization": "Union Bank of India",
        "department": "Banking",
        "category": "Banking",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "Not specified",
        "startDate": "2026-05-01",
        "lastDate": "2026-05-19",
        "status": "active",
        "tags": [
            "Union Bank",
            "Apprentice",
            "Banking"
        ],
        "applyLink": "https://beep.bfsissc.com/candidate_register/mkt",
        "officialNotification": "https://www.unionbankofindia.bank.in/pdf/notification-final-1865-april26.pdf",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2399",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2400",
        "title": "UPTET Online Form 2026",
        "organization": "Uttar Pradesh Exam Regulatory Authority",
        "department": "Education",
        "category": "Teaching",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "Not specified",
        "startDate": "2026-05-01",
        "lastDate": "2026-05-03",
        "status": "active",
        "tags": [
            "UPTET",
            "Teacher Eligibility",
            "UP"
        ],
        "applyLink": "https://uptet.upessc.org/otr/",
        "officialNotification": "https://www.upessc.up.gov.in/Notice/334a-b177-4450-4fbc-98be.pdf",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2400",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2401",
        "title": "Bihar CET B.Ed Online Form 2026",
        "organization": "Bihar CET B.Ed",
        "department": "Admission",
        "category": "Education",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "Not specified",
        "startDate": "2026-05-01",
        "lastDate": "2026-05-18",
        "status": "active",
        "tags": [
            "Bihar",
            "CET B.Ed",
            "Education"
        ],
        "applyLink": "https://cetbed.ucanapply.com/univer/public/secure?app_id=UElZMDAwMDEwMA==",
        "officialNotification": "https://d1fij890xi0cmd.cloudfront.net/ums/cetbed-brabu/2026/notices/1777289328_prospectus-cet-bed2026.pdf",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2401",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2402",
        "title": "RBI Officer Grade-B Online Form 2026",
        "organization": "Reserve Bank of India",
        "department": "Banking",
        "category": "Banking",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "60",
        "startDate": "2026-05-01",
        "lastDate": "2026-05-20",
        "status": "active",
        "tags": [
            "RBI",
            "Grade B",
            "Officer"
        ],
        "applyLink": "https://ibpsreg.ibps.in/rbisbmar26/",
        "officialNotification": "https://rbidocs.rbi.org.in/rdocs/Content/PDFs/DEPR29042026BE94DEA85E3C4753A82B191EB6A795ED.PDF",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2402",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2403",
        "title": "UPESSC Assistant Professor B.Ed Online Form 2025",
        "organization": "Uttar Pradesh Education Service Selection Commission",
        "department": "Education",
        "category": "Teaching",
        "year": "2025",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "107",
        "startDate": "2026-05-23",
        "lastDate": "2026-05-30",
        "status": "active",
        "tags": [
            "UPESSC",
            "Assistant Professor",
            "B.Ed"
        ],
        "applyLink": "https://bed.upessc.org/otr/",
        "officialNotification": "https://upessc.up.gov.in/Advertisment/462d7ee7-86da-4c19-80cf-877e0c787c50.pdf",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2403",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2404",
        "title": "MPPSC ADPO Online Form 2026",
        "organization": "Madhya Pradesh Public Service Commission",
        "department": "State PSC",
        "category": "State PSC",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "17",
        "startDate": "2026-04-09",
        "lastDate": "2026-05-08",
        "status": "active",
        "tags": [
            "MPPSC",
            "ADPO",
            "Madhya Pradesh"
        ],
        "applyLink": "https://mppsc.mponline.gov.in/Portal/Examinations/MPPSC/2026/PO26/Declaration.aspx",
        "officialNotification": "https://mppsc.mp.gov.in/uploads/advertisement/Advt_ADPO_Exam_2026_Dated_10_03_2026.pdf",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2404",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2405",
        "title": "UPSSSC Havildar Instructor Online Form 2026",
        "organization": "Uttar Pradesh Subordinate Services Selection Commission",
        "department": "State SSC",
        "category": "State Government",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "209",
        "startDate": "2026-05-01",
        "lastDate": "2026-07-09",
        "status": "upcoming",
        "tags": [
            "UPSSSC",
            "Havildar Instructor",
            "UP"
        ],
        "applyLink": "#",
        "officialNotification": "https://upsssc.gov.in//ViewPdf.aspx?DnnJcRACgDWbxJiEHVQZfB4I2Z6BHMLb+KVay71xLuw=",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2405",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2406",
        "title": "UP Anganwadi Bharti Online Form 2026",
        "organization": "Uttar Pradesh Anganwadi",
        "department": "Women and Child Development",
        "category": "State Government",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "61601",
        "startDate": "2026-05-01",
        "lastDate": "2026-05-16",
        "status": "active",
        "tags": [
            "UP Anganwadi",
            "Bharti",
            "UP"
        ],
        "applyLink": "https://upanganwadibharti.in/",
        "officialNotification": "https://upanganwadibharti.in/",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2406",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2407",
        "title": "UP Cooperative Bank Various Post Online Form 2026",
        "organization": "Uttar Pradesh Cooperative Institution Service Board",
        "department": "Banking",
        "category": "Banking",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "116",
        "startDate": "2026-05-01",
        "lastDate": "2026-05-15",
        "status": "active",
        "tags": [
            "UP Cooperative Bank",
            "Banking",
            "Various Post"
        ],
        "applyLink": "https://ibpsreg.ibps.in/upcisbfeb26/",
        "officialNotification": "https://upcisb.upsdc.gov.in/Content/A.1_S.R_2026_English.pdf",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2407",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2408",
        "title": "SSC Stenographer Online Form 2026",
        "organization": "Staff Selection Commission",
        "department": "SSC",
        "category": "Staff Selection",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "731",
        "startDate": "2026-04-24",
        "lastDate": "2026-05-15",
        "status": "active",
        "tags": [
            "SSC",
            "Stenographer",
            "Grade C D"
        ],
        "applyLink": "https://ssc.gov.in/login",
        "officialNotification": "https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/Notice_of_adv_steno_2026.pdf",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2408",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2409",
        "title": "SSC Selection Phase 14 Online Form 2026",
        "organization": "Staff Selection Commission",
        "department": "SSC",
        "category": "Staff Selection",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "3003",
        "startDate": "2026-05-13",
        "lastDate": "2026-05-04",
        "status": "active",
        "tags": [
            "SSC",
            "Selection Phase",
            "Phase 14"
        ],
        "applyLink": "https://ssc.gov.in/login",
        "officialNotification": "https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/Notice_of_RHQ_2026_phase_xiv.pdf",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2409",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2410",
        "title": "SSC JHT Online Form 2026",
        "organization": "Staff Selection Commission",
        "department": "SSC",
        "category": "Staff Selection",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "84",
        "startDate": "2026-05-01",
        "lastDate": "2026-05-14",
        "status": "active",
        "tags": [
            "SSC",
            "JHT",
            "Translator"
        ],
        "applyLink": "https://ssc.gov.in/login",
        "officialNotification": "https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/Notice_of_adv_cht_2026.pdf",
        "detailPage": "../Job_Details/HTML/job-details.html?id=2410",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "2411",
        "title": "SSB Constable Tradesman Online Form 2026",
        "organization": "Sashastra Seema Bal",
        "department": "Defence",
        "category": "Defence",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "Not specified",
        "startDate": "2026-05-01",
        "lastDate": "2026-05-04",
        "status": "active",
        "tags": [
            "SSB",
            "Constable",
            "Tradesman"
        ],
        "applyLink": "#",
        "officialNotification": "#",
        "detailPage": "../Job_Details/HTML/job-details-job-1027.html",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "job-sheet-28",
        "title": "UPSSSC Assistant Statistical Officer ASO Online Form 2026",
        "organization": "Uttar Pradesh Subordinate Services Selection Commission",
        "department": "State SSC",
        "category": "State Government",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "Not specified",
        "startDate": "2026-05-01",
        "lastDate": "2026-05-11",
        "status": "active",
        "tags": [
            "UPSSSC",
            "ASO",
            "Assistant Statistical Officer"
        ],
        "applyLink": "#",
        "officialNotification": "#",
        "detailPage": "../Job_Details/HTML/job-details-job-1028.html",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "job-sheet-29",
        "title": "Punjab PSPCL JE Electrical Online Form 2026",
        "organization": "Punjab State Power Corporation Limited",
        "department": "Power",
        "category": "Engineering",
        "year": "2026",
        "qualification": "View Details For Educational Qualification",
        "totalPosts": "Not specified",
        "startDate": "2026-05-01",
        "lastDate": "2026-05-10",
        "status": "active",
        "tags": [
            "PSPCL",
            "Junior Engineer",
            "Electrical"
        ],
        "applyLink": "#",
        "officialNotification": "#",
        "detailPage": "../Job_Details/HTML/job-details-job-1029.html",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    },
    {
        "id": "job-sheet-30",
        "title": "UPSSSC Forest Guard / Wildlife Guard Online Form 2026",
        "organization": "Uttar Pradesh Subordinate Services Selection Commission",
        "department": "Forest",
        "category": "State Government",
        "year": "2026",
        "qualification": "Intermediate ( Kindly Read Notification (",
        "totalPosts": "708",
        "startDate": "2026-05-01",
        "lastDate": "2026-07-20",
        "status": "active",
        "tags": [
            "UPSSSC",
            "Forest Guard",
            "Wildlife Guard"
        ],
        "applyLink": "#",
        "officialNotification": "https://upsssc.gov.in/ViewPdf.aspx?ss2XKF/cntZMY/QS8H1aTFqt7TVl91dOlzlMwUgIiWk=",
        "detailPage": "../Job_Details/HTML/job-details-job-1030.html",
        "updatedAt": "2026-05-01",
        "telegramStatus": "draft",
        "telegramReady": "no"
    }
];
