window.govJobIndJobs = [
    { id: "job-1001", title: "Rajasthan RSSB Teaching Associate Online Form 2026 (3540 Posts)", organization: "Rajasthan Staff Selection Board", department: "Teaching", category: "Teaching", year: "2026", qualification: "Not specified", totalPosts: "3540", startDate: "2026-05-01", lastDate: "2026-06-03", status: "active", tags: ["RSSB", "Rajasthan", "Teaching"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1001.html", updatedAt: "2026-05-01" },

    { id: "job-1002", title: "UP Police 1 Lakh New Recruitment Notice 2026", organization: "Uttar Pradesh Police Recruitment and Promotion Board", department: "Police", category: "Police", year: "2026", qualification: "Not specified", totalPosts: "100000", startDate: "", lastDate: "", status: "upcoming", tags: ["UP Police", "Police", "Upcoming"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1002.html", updatedAt: "2026-05-01" },

    { id: "job-1003", title: "CRPF Constable Tradesman Online Form 2026 (9195 Posts)", organization: "Central Reserve Police Force", department: "Defence", category: "Defence", year: "2026", qualification: "Not specified", totalPosts: "9195", startDate: "2026-05-01", lastDate: "2026-05-19", status: "active", tags: ["CRPF", "Constable", "Tradesman"], applyLink: "https://recruitment.crpf.gov.in/login", officialNotification: "#", detailPage: "../Job_Details/HTML/1003.html", updatedAt: "2026-05-01" },

    { id: "job-1004", title: "Railway RRB ALP Online Form 2026 (11127 Posts)", organization: "Railway Recruitment Board", department: "Railway", category: "Railway", year: "2026", qualification: "Not specified", totalPosts: "11127", startDate: "2026-05-01", lastDate: "2026-06-14", status: "active", tags: ["RRB", "ALP", "Railway"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1004.html", updatedAt: "2026-05-01" },

    { id: "job-1005", title: "MPESB Nursing Officer / Sister Tutor Online Form 2026", organization: "Madhya Pradesh Employee Selection Board", department: "Health", category: "Health", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-05-03", status: "active", tags: ["MPESB", "Nursing Officer", "Sister Tutor"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/1005.html", updatedAt: "2026-05-01" },

    { id: "job-1006", title: "MPESB Hospital Assistant Online Form 2026", organization: "Madhya Pradesh Employee Selection Board", department: "Health", category: "Health", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-05-21", status: "active", tags: ["MPESB", "Hospital Assistant", "Health"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1006.html", updatedAt: "2026-05-01" },

    { id: "job-1007", title: "MPESB Van Rakshak / Jail Prahari Online Form 2026", organization: "Madhya Pradesh Employee Selection Board", department: "Forest and Jail", category: "State Government", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-04-30", status: "closed", tags: ["MPESB", "Van Rakshak", "Jail Prahari"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1007.html", updatedAt: "2026-05-01" },

    { id: "job-1008", title: "Bihar BPSC 33rd Judicial Services Online Form 2026", organization: "Bihar Public Service Commission", department: "Judiciary", category: "State PSC", year: "2026", qualification: "Graduate", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-04-30", status: "closed", tags: ["BPSC", "Judicial Services", "Bihar"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1008.html", updatedAt: "2026-05-01" },

    { id: "job-1009", title: "Patna High Court Technical Assistant Online Form 2026", organization: "Patna High Court", department: "Court", category: "Judiciary", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-04-30", status: "closed", tags: ["Patna High Court", "Technical Assistant", "Bihar"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1009.html", updatedAt: "2026-05-01" },

    { id: "job-1010", title: "NPCIL Executive Trainee Online Form 2026", organization: "Nuclear Power Corporation of India Limited", department: "Public Sector", category: "Public Sector", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-04-30", status: "closed", tags: ["NPCIL", "Executive Trainee", "PSU"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1010.html", updatedAt: "2026-05-01" },

    { id: "job-1011", title: "BSNL Senior Executive Trainee Online Form 2026", organization: "Bharat Sanchar Nigam Limited", department: "Telecom", category: "Public Sector", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-04-30", status: "closed", tags: ["BSNL", "Senior Executive Trainee", "Telecom"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1011.html", updatedAt: "2026-05-01" },

    { id: "job-1012", title: "Bihar BCECE Senior Resident / Tutor Online Form 2026", organization: "Bihar Combined Entrance Competitive Examination Board", department: "Medical Education", category: "Health", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-04-30", status: "closed", tags: ["BCECE", "Senior Resident", "Tutor"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1012.html", updatedAt: "2026-05-01" },

    { id: "job-1013", title: "LIC HFL Junior Assistant Online Form 2026", organization: "LIC Housing Finance Limited", department: "Banking", category: "Banking", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-04-30", status: "closed", tags: ["LIC HFL", "Junior Assistant", "Banking"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1013.html", updatedAt: "2026-05-01" },

    { id: "job-1014", title: "BPSSC Bihar Police Havildar Instructor Online Form 2026", organization: "Bihar Police Subordinate Services Commission", department: "Police", category: "Police", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-06-01", status: "active", tags: ["BPSSC", "Bihar Police", "Havildar Instructor"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1014.html", updatedAt: "2026-05-01" },

    { id: "job-1015", title: "Union Bank of India Apprentice Online Form 2026", organization: "Union Bank of India", department: "Banking", category: "Banking", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-05-19", status: "active", tags: ["Union Bank", "Apprentice", "Banking"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1015.html", updatedAt: "2026-05-01" },

    { id: "job-1016", title: "UPTET Online Form 2026", organization: "Uttar Pradesh Exam Regulatory Authority", department: "Education", category: "Teaching", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-05-03", status: "active", tags: ["UPTET", "Teacher Eligibility", "UP"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1016.html", updatedAt: "2026-05-01" },

    { id: "job-1017", title: "Bihar CET B.Ed Online Form 2026", organization: "Bihar CET B.Ed", department: "Admission", category: "Education", year: "2026", qualification: "Graduate", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-05-18", status: "active", tags: ["Bihar", "CET B.Ed", "Education"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1017.html", updatedAt: "2026-05-01" },

    { id: "job-1018", title: "RBI Officer Grade-B Online Form 2026", organization: "Reserve Bank of India", department: "Banking", category: "Banking", year: "2026", qualification: "Graduate", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-05-20", status: "active", tags: ["RBI", "Grade B", "Officer"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1018.html", updatedAt: "2026-05-01" },

    { id: "job-1019", title: "UPESSC Assistant Professor B.Ed Online Form 2025", organization: "Uttar Pradesh Education Service Selection Commission", department: "Education", category: "Teaching", year: "2025", qualification: "Not specified", totalPosts: "Not specified", startDate: "", lastDate: "", status: "active", tags: ["UPESSC", "Assistant Professor", "B.Ed"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1019.html", updatedAt: "2026-05-01" },

    { id: "job-1020", title: "MPPSC ADPO Online Form 2026", organization: "Madhya Pradesh Public Service Commission", department: "State PSC", category: "State PSC", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-05-08", status: "active", tags: ["MPPSC", "ADPO", "Madhya Pradesh"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1020.html", updatedAt: "2026-05-01" },

    { id: "job-1021", title: "UPSSSC Havildar Instructor Online Form 2026", organization: "Uttar Pradesh Subordinate Services Selection Commission", department: "State SSC", category: "State Government", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-07-09", status: "active", tags: ["UPSSSC", "Havildar Instructor", "UP"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1021.html", updatedAt: "2026-05-01" },

    { id: "job-1022", title: "UP Anganwadi Bharti Online Form 2026", organization: "Uttar Pradesh Anganwadi", department: "Women and Child Development", category: "State Government", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-05-16", status: "active", tags: ["UP Anganwadi", "Bharti", "UP"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1022.html", updatedAt: "2026-05-01" },

    { id: "job-1023", title: "UP Cooperative Bank Various Post Online Form 2026", organization: "Uttar Pradesh Cooperative Institution Service Board", department: "Banking", category: "Banking", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-05-15", status: "active", tags: ["UP Cooperative Bank", "Banking", "Various Post"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1023.html", updatedAt: "2026-05-01" },

    { id: "job-1024", title: "SSC Stenographer Online Form 2026", organization: "Staff Selection Commission", department: "SSC", category: "Staff Selection", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-05-15", status: "active", tags: ["SSC", "Stenographer", "Grade C D"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1024.html", updatedAt: "2026-05-01" },

    { id: "job-1025", title: "SSC Selection Phase 14 Online Form 2026", organization: "Staff Selection Commission", department: "SSC", category: "Staff Selection", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-05-04", status: "active", tags: ["SSC", "Selection Phase", "Phase 14"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1025.html", updatedAt: "2026-05-01" },

    { id: "job-1026", title: "SSC JHT Online Form 2026", organization: "Staff Selection Commission", department: "SSC", category: "Staff Selection", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-05-14", status: "active", tags: ["SSC", "JHT", "Translator"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1026.html", updatedAt: "2026-05-01" },

    { id: "job-1027", title: "SSB Constable Tradesman Online Form 2026", organization: "Sashastra Seema Bal", department: "Defence", category: "Defence", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-05-04", status: "active", tags: ["SSB", "Constable", "Tradesman"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1027.html", updatedAt: "2026-05-01" },

    { id: "job-1028", title: "UPSSSC Assistant Statistical Officer ASO Online Form 2026", organization: "Uttar Pradesh Subordinate Services Selection Commission", department: "State SSC", category: "State Government", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-05-11", status: "active", tags: ["UPSSSC", "ASO", "Assistant Statistical Officer"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1028.html", updatedAt: "2026-05-01" },

    { id: "job-1029", title: "Punjab PSPCL JE Electrical Online Form 2026", organization: "Punjab State Power Corporation Limited", department: "Power", category: "Engineering", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-05-10", status: "active", tags: ["PSPCL", "Junior Engineer", "Electrical"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1029.html", updatedAt: "2026-05-01" },

    { id: "job-1030", title: "UPSSSC Forest Guard / Wildlife Guard Online Form 2026", organization: "Uttar Pradesh Subordinate Services Selection Commission", department: "Forest", category: "State Government", year: "2026", qualification: "Not specified", totalPosts: "Not specified", startDate: "2026-05-01", lastDate: "2026-07-20", status: "active", tags: ["UPSSSC", "Forest Guard", "Wildlife Guard"], applyLink: "#", officialNotification: "#", detailPage: "../Job_Details/HTML/job-details-job-1030.html", updatedAt: "2026-05-01" }
];
