(function(){
"use strict";
const list=document.getElementById("quizLatestList"),filters=document.getElementById("quizSubjectFilters"),empty=document.getElementById("quizLatestEmpty");
if(!list)return;
const familyPages={ssc:"ssc-quizzes.html",banking:"banking-quizzes.html",police:"police-quizzes.html",rrb:"rrb-quizzes.html",railway:"rrb-quizzes.html"};
const familyNames={ssc:"SSC",banking:"Banking",police:"Police",rrb:"Railway",railway:"Railway"};
let quizzes=[],activeSubject="";
function esc(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;")}
function slugify(v){return String(v||"").trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")||"quiz"}
function sourceItems(){for(const p of[window.GJU_QUIZ_INDEX,window.GJU_ADMIN_QUIZ_INDEX,window.GJU_PUBLISHED_QUIZ_INDEX]){if(Array.isArray(p))return p;if(p&&Array.isArray(p.quizzes))return p.quizzes;if(p&&Array.isArray(p.items))return p.items;if(p&&Array.isArray(p.data))return p.data}return[]}
function family(item){return String(item.examFamilySlug||item.exam_family_slug||(item.examFamily&&item.examFamily.slug)||(item.exam_family&&item.exam_family.slug)||"").trim().toLowerCase()}
function normalize(item,index){const f=family(item),ss=slugify(item.subjectSlug||item.subject_slug||(item.subject&&item.subject.slug)||item.subject||"practice"),sn=String(item.subjectName||item.subject_name||(item.subject&&item.subject.name)||item.subject||ss).trim(),qs=slugify(item.quizSlug||item.quiz_slug||item.slug||item.id||item.title||"quiz");return{id:`admin-${ss}-${qs}`.replace(/-+/g,"-"),title:String(item.title||item.quizTitle||item.quiz_title||qs).trim(),description:String(item.description||item.summary||`${familyNames[f]||"Government exam"} practice quiz on GovJobUpdates.`).trim(),subject:sn,family:f,familyName:familyNames[f]||String(f||"Practice").toUpperCase(),duration:Number(item.durationMinutes||item.duration_minutes)||30,questions:Number(item.totalQuestions||item.total_questions||item.activeQuestions||item.active_questions)||0,order:Number(item.publishedAt||item.published_at||item.updatedAt||item.updated_at||item.createdAt||item.created_at)||index}}
function buildFilters(){if(!filters)return;const subjects=Array.from(new Set(quizzes.map(q=>q.subject).filter(Boolean))).sort((a,b)=>a.localeCompare(b));filters.innerHTML='<button class="is-active" type="button" data-subject="">All Subjects</button>'+subjects.map(s=>`<button type="button" data-subject="${esc(s)}">${esc(s)}</button>`).join("");filters.addEventListener("click",e=>{const button=e.target.closest("button[data-subject]");if(!button)return;activeSubject=button.dataset.subject||"";filters.querySelectorAll("button").forEach(b=>b.classList.toggle("is-active",b===button));render()})}
function render(){const rows=(activeSubject?quizzes.filter(q=>q.subject===activeSubject):quizzes).slice(0,6);if(!rows.length){list.innerHTML="";if(empty)empty.hidden=false;return}if(empty)empty.hidden=true;list.innerHTML=rows.map(q=>{const page=familyPages[q.family]||"quiz.html",href=`quiz-attempt.html?quiz=${encodeURIComponent(q.id)}&family=${encodeURIComponent(q.family)}`;return `<article class="quiz-latest-card"><div class="quiz-latest-top"><span class="quiz-latest-subject">${esc(q.subject)}</span><span class="quiz-latest-family">${esc(q.familyName)}</span></div><h3>${esc(q.title)}</h3><p>${esc(q.description)}</p><div class="quiz-latest-meta"><span><i class="far fa-circle-question"></i>${q.questions?q.questions+" Questions":"Practice Set"}</span><span><i class="far fa-clock"></i>${q.duration} Minutes</span></div><a class="quiz-latest-start" href="${href}" data-family-page="${page}"><span>Start Free Quiz</span><i class="fas fa-arrow-right" aria-hidden="true"></i></a></article>`}).join("")}
function load(){const allowed=new Set(Object.keys(familyPages));quizzes=sourceItems().filter(item=>item&&allowed.has(family(item))).map(normalize).reverse();buildFilters();render()}
document.addEventListener("gju:admin-quiz-index-ready",load,{once:true});
load();
window.setTimeout(()=>{if(!quizzes.length)load()},900);
}());