(function(){
  "use strict";
  const API_BASE="https://test.govjobupdates.com/live-test/store-api";
  const CART_KEY="gjuStoreCart";
  const LEGACY_CART_KEY="gjuPhysicalStoreCart";
  const PIN_KEY="gjuStoreDeliveryPin";
  const V2_CHECKOUT=true;
  const $=s=>document.querySelector(s);
  const clean=v=>String(v??"").replace(/\s+/g," ").trim();
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const money=p=>`₹${(Number(p||0)/100).toLocaleString("en-IN",{minimumFractionDigits:Number(p||0)%100?2:0,maximumFractionDigits:2})}`;
  let state={cart:[],validated:null,pin:"",delivery:null,validating:false,problemVariant:null};
  function readCart(){try{let raw=localStorage.getItem(CART_KEY);if(!raw){raw=localStorage.getItem(LEGACY_CART_KEY);if(raw)localStorage.setItem(CART_KEY,raw)}const c=JSON.parse(raw||"[]");return Array.isArray(c)?c.filter(i=>Number(i.variant_id)>0&&Number(i.quantity)>0):[]}catch{return[]}}
  function saveCart(){localStorage.setItem(CART_KEY,JSON.stringify(state.cart));renderCount();}
  function renderCount(){const n=state.cart.reduce((s,i)=>s+Number(i.quantity||0),0);const el=$("#cartItemCount");if(el)el.textContent=String(n)}
  function setAlert(msg){const el=$("#cartAlert");if(!el)return;el.textContent=msg||"";el.hidden=!msg}
  function findLocal(id){return state.cart.find(i=>Number(i.variant_id)===Number(id))||{}}
  function findValidated(id){return state.validated?.items?.find(i=>Number(i.variant_id)===Number(id))||null}
  function displayImage(local){return clean(local.image)?`<img src="${esc(local.image)}" alt="${esc(local.title||'Product')}" loading="lazy">`:'<i class="fas fa-box-open" aria-hidden="true"></i>'}
  function renderItems(){const box=$("#cartItems");if(!box)return;box.innerHTML=state.cart.map(local=>{const v=findValidated(local.variant_id);const problem=state.problemVariant===Number(local.variant_id)||(!v&&state.validated);const sell=Number(v?.selling_price_paise||0),mrp=Number(v?.mrp_paise||0),qty=Number(local.quantity||1),av=Number(v?.available_qty||0);const max=v?Math.max(1,Math.min(3,av)):3;const title=v?.product_title||local.title||"Product";const slug=v?.product_slug||local.slug||"";const size=v?.size??local.size??"";const color=v?.color??local.color??"";const stockCls=av<=0?'is-out':av<=3?'is-low':'';const stockText=v?(av<=0?'Out of stock':av<=3?`Only ${av} available`:`${av} available`):'Waiting for validation';return `<article class="cart-item ${problem?'is-problem':''}" data-variant-id="${Number(local.variant_id)}">
      <a class="cart-item-image" href="${slug?`store-product.html?slug=${encodeURIComponent(slug)}`:'#'}">${displayImage(local)}</a>
      <div class="cart-item-info">
        <div class="cart-item-top"><div><span class="cart-brand">${esc(local.brand||local.category||'GovJobUpdates Store')}</span><a class="cart-item-title" href="${slug?`store-product.html?slug=${encodeURIComponent(slug)}`:'#'}">${esc(title)}</a></div><button class="cart-remove" type="button" data-remove="${Number(local.variant_id)}" aria-label="Remove ${esc(title)}"><i class="fas fa-trash-can"></i></button></div>
        <div class="cart-variant">${size?`<span>Size: ${esc(size)}</span>`:''}${color?`<span>Colour: ${esc(color)}</span>`:''}${v?.sku||local.sku?`<span>SKU: ${esc(v?.sku||local.sku)}</span>`:''}</div>
        <span class="cart-stock-note ${stockCls}">${esc(stockText)}</span>
        <div class="cart-item-bottom"><div class="cart-price">${sell>0?`<strong>${money(sell)}</strong>${mrp>sell?`<del>${money(mrp)}</del>`:''}<span class="cart-line-total">Item total ${money(sell*qty)}</span>`:'<strong>Checking price…</strong>'}</div>
          <div class="cart-qty"><button type="button" data-qty-minus="${Number(local.variant_id)}" ${qty<=1?'disabled':''} aria-label="Decrease quantity"><i class="fas fa-minus"></i></button><span>${qty}</span><button type="button" data-qty-plus="${Number(local.variant_id)}" ${v&&qty>=max?'disabled':''} aria-label="Increase quantity"><i class="fas fa-plus"></i></button></div></div>
        ${problem?'<div class="cart-problem"><i class="fas fa-triangle-exclamation"></i><span>This item needs review. Stock, quantity or availability has changed.</span></div>':''}
      </div></article>`}).join("");bindItemActions()}
  function bindItemActions(){document.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>removeItem(Number(b.dataset.remove))));document.querySelectorAll('[data-qty-minus]').forEach(b=>b.addEventListener('click',()=>changeQty(Number(b.dataset.qtyMinus),-1)));document.querySelectorAll('[data-qty-plus]').forEach(b=>b.addEventListener('click',()=>changeQty(Number(b.dataset.qtyPlus),1)))}
  function removeItem(id){state.cart=state.cart.filter(i=>Number(i.variant_id)!==id);state.problemVariant=null;saveCart();if(!state.cart.length){showEmpty();return}renderItems();validateCart()}
  function changeQty(id,delta){const item=findLocal(id);if(!item)return;const v=findValidated(id);const max=v?Math.max(1,Math.min(3,Number(v.available_qty||0))):3;item.quantity=Math.max(1,Math.min(max,Number(item.quantity||1)+delta));state.problemVariant=null;saveCart();renderItems();validateCart()}
  function showEmpty(){state.validated=null;state.delivery=null;$("#cartLoading").hidden=true;$("#cartLayout").hidden=true;$("#cartEmpty").hidden=false;setAlert("");renderCount()}
  function showCart(){$("#cartLoading").hidden=true;$("#cartEmpty").hidden=true;$("#cartLayout").hidden=false;renderCount();renderItems()}
  async function validateCart(checkPin=false){if(!state.cart.length){showEmpty();return}state.validating=true;const text=$("#cartValidationText");if(text)text.textContent="Checking current stock and prices…";setAlert("");setCheckout(false,"Validating cart…");try{const payload={items:state.cart.map(i=>({variant_id:Number(i.variant_id),quantity:Number(i.quantity)}))};if(checkPin&&/^\d{6}$/.test(state.pin))payload.pin_code=state.pin;const r=await fetch(`${API_BASE}/cart-validate.php`,{method:"POST",mode:"cors",cache:"no-store",credentials:"omit",headers:{"Content-Type":"application/json","X-Requested-With":"XMLHttpRequest"},body:JSON.stringify(payload)});const j=await r.json().catch(()=>null);if(!r.ok||!j?.success){state.validated=null;state.problemVariant=Number(j?.variant_id||0)||null;throw new Error(j?.message||"Your cart could not be validated.")}state.validated=j;state.problemVariant=null;if(text)text.textContent="Live prices and stock verified.";syncLocalFromValidated();renderItems();renderSummary();if(j.delivery&&/^\d{6}$/.test(state.pin)){state.delivery=j.delivery;renderDelivery(j.delivery)}else if(state.pin){await checkPin()}else setCheckout(false,"Enter your delivery PIN to continue.")}catch(e){if(text)text.textContent="Cart needs review.";setAlert(e.message||"Your cart changed. Please review it.");renderItems();renderSummary();setCheckout(false,"Resolve cart availability before checkout.")}finally{state.validating=false}}
  function syncLocalFromValidated(){if(!state.validated?.items)return;state.validated.items.forEach(v=>{const l=findLocal(v.variant_id);if(!l)return;l.product_id=v.product_id;l.slug=v.product_slug;l.title=v.product_title;l.size=v.size||l.size||"";l.color=v.color||l.color||"";l.sku=v.sku||l.sku||"";if(Number(l.quantity)>Number(v.available_qty))l.quantity=Math.max(1,Math.min(3,Number(v.available_qty||1)))});saveCart()}
  function renderSummary(){const subtotal=Number(state.validated?.subtotal_paise||0);$("#summarySubtotal").textContent=state.validated?money(subtotal):"—";if(state.delivery?.serviceable){const fee=Number(state.delivery.delivery_fee_paise||0);$("#summaryDelivery").textContent=fee===0?"Free":money(fee);$("#summaryTotal").textContent=money(subtotal+fee)}else{$("#summaryDelivery").textContent="Check PIN";$("#summaryTotal").textContent=state.validated?money(subtotal):"—"}}
  async function checkPin(e){if(e)e.preventDefault();const pin=clean($("#cartPin").value);const out=$("#cartPinResult"),btn=$("#cartPinButton");out.className="pin-result";out.textContent="";if(!/^\d{6}$/.test(pin)){out.textContent="Enter a valid 6 digit PIN code.";out.className="pin-result show error";setCheckout(false,"Enter a valid delivery PIN.");return}if(!state.validated){await validateCart(false);if(!state.validated)return}state.pin=pin;localStorage.setItem(PIN_KEY,pin);btn.disabled=true;btn.textContent="Checking…";try{const r=await fetch(`${API_BASE}/delivery-check.php?pin_code=${encodeURIComponent(pin)}&subtotal_paise=${Number(state.validated.subtotal_paise||0)}`,{cache:"no-store",mode:"cors",credentials:"omit",headers:{"X-Requested-With":"XMLHttpRequest"}});const j=await r.json().catch(()=>null);if(!r.ok||!j?.success)throw new Error(j?.message||"Could not check delivery.");state.delivery=j;renderDelivery(j);renderSummary()}catch(err){state.delivery=null;out.textContent=err.message||"Could not check delivery.";out.className="pin-result show error";renderSummary();setCheckout(false,"Delivery availability could not be verified.")}finally{btn.disabled=false;btn.textContent="Check"}}
  function renderDelivery(d){const out=$("#cartPinResult"),free=$("#freeDeliveryRow");if(!d?.serviceable){out.textContent=`Delivery is not available at PIN ${state.pin} yet.`;out.className="pin-result show error";free.hidden=true;setCheckout(false,"Choose a serviceable delivery PIN.");return}const minOk=d.minimum_order_met!==false;const bits=[`Delivery available${d.city?` in ${d.city}`:""}${d.locality?`, ${d.locality}`:""}.`,V2_CHECKOUT?"Secure online payment available.":(d.cod_available?"COD available.":"COD unavailable."),Number(d.delivery_fee_paise||0)===0?"Free delivery.":`Delivery ${money(d.delivery_fee_paise)}.`,d.eta?`ETA: ${d.eta}.`:""];out.textContent=bits.filter(Boolean).join(" ");if(!minOk){out.className="pin-result show warning";setCheckout(false,`Minimum order ${money(d.minimum_order_paise||0)} required for this PIN.`);return}out.className="pin-result show success";free.hidden=Number(d.delivery_fee_paise||0)!==0;if(!free.hidden)$("#freeDeliveryText").textContent="Free";if(state.validated)setCheckout(true,V2_CHECKOUT?"Cart and delivery verified. Continue to secure online payment.":"Cart and delivery verified. You can continue.")}
  function setCheckout(enabled,help){const btn=$("#checkoutBtn");btn.classList.toggle("is-disabled",!enabled);btn.setAttribute("aria-disabled",enabled?"false":"true");btn.href=V2_CHECKOUT?"store-checkout.html?v2=1":"store-checkout.html";$("#checkoutHelp").textContent=help||""}
  function clearCart(){if(!state.cart.length)return;if(!window.confirm("Remove all items from your cart?"))return;state.cart=[];localStorage.removeItem(CART_KEY);state.validated=null;state.delivery=null;showEmpty()}
  function applyV2Copy(){if(!V2_CHECKOUT)return;const assurance=document.querySelector('.cart-assurance-card > div:nth-child(3)');if(assurance)assurance.innerHTML='<i class="fas fa-shield-halved" aria-hidden="true"></i><span><strong>Secure Online Payment</strong>Pay through Razorpay after stock and delivery are verified.</span>';const btn=$("#checkoutBtn");if(btn)btn.innerHTML='<span><i class="fas fa-lock" aria-hidden="true"></i> Proceed to Secure Checkout</span><i class="fas fa-arrow-right" aria-hidden="true"></i>'}
  function init(){state.cart=readCart();state.pin=clean(localStorage.getItem(PIN_KEY)||"");applyV2Copy();if(state.pin&&$("#cartPin"))$("#cartPin").value=state.pin;$("#clearCartBtn")?.addEventListener("click",clearCart);$("#cartPinForm")?.addEventListener("submit",checkPin);$("#checkoutBtn")?.addEventListener("click",e=>{if($("#checkoutBtn").classList.contains("is-disabled"))e.preventDefault()});if(!state.cart.length){showEmpty();return}showCart();validateCart(Boolean(state.pin))}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
}());