(function () {
  "use strict";
  const STORE_API_BASE = "https://test.govjobupdates.com/live-test/store-api";
  const CART_STORAGE_KEY = "gjuStoreCart";
  const LEGACY_CART_STORAGE_KEY = "gjuPhysicalStoreCart";
  const $ = (selector) => document.querySelector(selector);
  const $$ = (selector) => Array.from(document.querySelectorAll(selector));
  const state = { products: [], categories: [], category: "", search: "", sort: "featured", loading: true };
  const CATEGORY_ICONS = {"running-shoes":"fa-shoe-prints","running-wear":"fa-shirt","running-essentials":"fa-stopwatch","support-recovery":"fa-heart-pulse","training-equipment":"fa-dumbbell","ground-essentials":"fa-bottle-water"};
  function clean(value){return String(value||"").replace(/\s+/g," ").trim();}
  function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
  function money(paise){const amount=Math.max(0,Number(paise||0))/100;return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:amount%1===0?0:2}).format(amount);}
  function categoryIcon(category){const slug=clean(category.slug).toLowerCase(),name=clean(category.name).toLowerCase();if(CATEGORY_ICONS[slug])return CATEGORY_ICONS[slug];if(name.includes("shoe"))return "fa-shoe-prints";if(name.includes("wear")||name.includes("cloth"))return "fa-shirt";if(name.includes("book"))return "fa-book-open";if(name.includes("study")||name.includes("stationery"))return "fa-pen-ruler";if(name.includes("training"))return "fa-dumbbell";return "fa-box-open";}
  function categorySubtitle(category){const name=clean(category.name).toLowerCase();if(name.includes("shoe"))return "Practice & running";if(name.includes("wear"))return "Training apparel";if(name.includes("book"))return "Books & preparation";if(name.includes("study"))return "Study essentials";return "Explore products";}
  function readCartCount(){try{let raw=localStorage.getItem(CART_STORAGE_KEY)||localStorage.getItem(LEGACY_CART_STORAGE_KEY)||"[]";const cart=JSON.parse(raw);return Array.isArray(cart)?cart.reduce((s,i)=>s+Math.max(0,Number(i?.quantity||0)),0):0;}catch{return 0;}}
  function updateCartCount(){const count=readCartCount();const badge=$("#pasCartCount");if(badge){badge.textContent=count>99?"99+":String(count);badge.setAttribute("aria-label",`${count} cart item${count===1?"":"s"}`);}document.dispatchEvent(new CustomEvent('gju:store-cart-updated'));}
  function renderCategories(){const grid=$("#pasCategoryGrid"),mobile=$("#pasMobileFilters");if(!grid||!mobile)return;if(!state.categories.length){grid.innerHTML='<div class="pas-empty-state" style="grid-column:1/-1;min-height:130px"><p>No active store categories yet.</p></div>';mobile.innerHTML="";return;}grid.innerHTML=state.categories.map(c=>`<button class="pas-category-card${state.category===clean(c.slug)?" is-active":""}" type="button" data-category="${escapeHtml(clean(c.slug))}" aria-pressed="${state.category===clean(c.slug)}"><span class="pas-category-icon"><i class="fas ${categoryIcon(c)}"></i></span><strong>${escapeHtml(c.name||"Category")}</strong><span>${escapeHtml(categorySubtitle(c))}</span></button>`).join("");mobile.innerHTML=[`<button type="button" data-category="" class="${state.category===""?"is-active":""}">All</button>`,...state.categories.map(c=>`<button type="button" data-category="${escapeHtml(c.slug)}" class="${state.category===c.slug?"is-active":""}">${escapeHtml(c.name)}</button>`)].join("");$$('[data-category]').forEach(b=>b.addEventListener("click",()=>setCategory(b.dataset.category||"")));}
  function productPrice(p){const min=Number(p.min_price_paise),max=Number(p.max_price_paise);if(!Number.isFinite(min)||min<=0)return "Price unavailable";return Number.isFinite(max)&&max>min?`${money(min)}–${money(max)}`:money(min);}
  function filteredProducts(){const q=state.search.toLowerCase();let products=state.products.filter(p=>(!state.category||clean(p.category?.slug)===state.category)&&(!q||[p.title,p.short_description,p.category?.name,p.brand?.name].map(clean).join(" ").toLowerCase().includes(q)));return [...products].sort((a,b)=>state.sort==="price-asc"?Number(a.min_price_paise||Infinity)-Number(b.min_price_paise||Infinity):state.sort==="price-desc"?Number(b.min_price_paise||0)-Number(a.min_price_paise||0):state.sort==="name"?clean(a.title).localeCompare(clean(b.title),"en"):Number(Boolean(b.is_featured))-Number(Boolean(a.is_featured)));}
  function renderProducts(){const grid=$("#pasProductGrid"),empty=$("#pasEmptyState"),label=$("#pasResultsLabel"),active=$("#pasActiveFilter");if(!grid||!empty)return;const products=filteredProducts();grid.hidden=!products.length;empty.hidden=!!products.length;if(label)label.textContent=`${products.length} product${products.length===1?"":"s"}${state.category?" in "+(state.categories.find(c=>c.slug===state.category)?.name||"selected category"):""}`;if(active){active.hidden=!state.category;if(state.category)active.innerHTML=`<i class="fas fa-filter"></i> ${escapeHtml(state.categories.find(c=>c.slug===state.category)?.name||state.category)}`;}$$('[data-clear-filters]').forEach(b=>b.hidden=!(state.category||state.search));grid.innerHTML=products.map(p=>{const stock=Math.max(0,Number(p.available_qty||0)),stockClass=stock===0?"is-out":stock<=3?"is-low":"",stockText=stock===0?"Out of stock":stock<=3?`Only ${stock} left`:"In stock",image=clean(p.image),brand=clean(p.brand?.name),category=clean(p.category?.name),url=`store-product.html?slug=${encodeURIComponent(clean(p.slug))}`;return `<article class="pas-product-card"><a class="pas-product-image-wrap" href="${url}">${image?`<img class="pas-product-image" src="${escapeHtml(image)}" alt="${escapeHtml(p.title)}" loading="lazy">`:'<span class="pas-product-placeholder"><i class="fas fa-bag-shopping"></i></span>'}<span class="pas-product-badges">${p.is_featured?'<span class="pas-badge featured">Featured</span>':""}${stock===0?'<span class="pas-badge out">Sold Out</span>':stock<=3?'<span class="pas-badge low">Low Stock</span>':""}</span></a><div class="pas-product-body"><div class="pas-product-meta"><span>${escapeHtml(brand||"GovJobUpdates Store")}</span>${brand&&category?'<i class="fas fa-circle"></i>':""}<span>${escapeHtml(category)}</span></div><a class="pas-product-title" href="${url}">${escapeHtml(p.title||"Store Product")}</a><p class="pas-product-desc">${escapeHtml(p.short_description||"Selected for aspirants.")}</p><div class="pas-product-price-row"><div class="pas-price">${escapeHtml(productPrice(p))}</div><span class="pas-stock-text ${stockClass}">${stockText}</span></div><a class="pas-product-action ${stock===0?"is-disabled":""}" href="${stock===0?"#":url}" ${stock===0?'aria-disabled="true" tabindex="-1"':""}><i class="fas ${stock===0?"fa-ban":"fa-eye"}"></i> ${stock===0?"Unavailable":"View Product"}</a></div></article>`;}).join("");}
  function setCategory(slug){state.category=clean(slug);renderCategories();renderProducts();$("#shopProducts")?.scrollIntoView({behavior:"smooth",block:"start"});}
  function clearFilters(){state.category="";state.search="";const input=$("#pasProductSearch");if(input)input.value="";const clear=$("#pasSearchClear");if(clear)clear.hidden=true;renderCategories();renderProducts();}
  async function loadProducts(){state.loading=true;$("#pasLoadingState")?.removeAttribute("hidden");try{const r=await fetch(`${STORE_API_BASE}/products.php?limit=60`,{mode:"cors",cache:"no-store",credentials:"omit",headers:{"X-Requested-With":"XMLHttpRequest"}}),result=await r.json().catch(()=>null);if(!r.ok||!result?.success||!Array.isArray(result.products))throw new Error(result?.message||"Store products could not be loaded.");state.products=result.products;state.categories=Array.isArray(result.categories)?result.categories:[];renderCategories();renderProducts();$("#pasLoadingState")?.setAttribute("hidden","");if(state.products.length)$("#pasProductGrid")?.removeAttribute("hidden");}catch(e){$("#pasLoadingState")?.setAttribute("hidden","");$("#pasProductGrid")?.setAttribute("hidden","");$("#pasErrorState")?.removeAttribute("hidden");if($("#pasResultsLabel"))$("#pasResultsLabel").textContent="Live catalogue unavailable";console.error("GovJobUpdates Store:",e);}finally{state.loading=false;}}
  function bindControls(){const search=$("#pasProductSearch"),clear=$("#pasSearchClear");search?.addEventListener("input",()=>{state.search=clean(search.value);if(clear)clear.hidden=!state.search;renderProducts();});clear?.addEventListener("click",()=>{state.search="";search.value="";clear.hidden=true;search.focus();renderProducts();});$("#pasProductSort")?.addEventListener("change",e=>{state.sort=e.target.value;renderProducts();});$("#pasFilterButton")?.addEventListener("click",e=>{const f=$("#pasMobileFilters");if(!f)return;const open=f.hidden;f.hidden=!open;e.currentTarget.setAttribute("aria-expanded",open?"true":"false");});$$('[data-clear-filters]').forEach(b=>b.addEventListener("click",clearFilters));$("#pasRetryButton")?.addEventListener("click",loadProducts);addEventListener("storage",e=>{if(e.key===CART_STORAGE_KEY||e.key===LEGACY_CART_STORAGE_KEY)updateCartCount();});}
  function init(){const params=new URLSearchParams(location.search),q=clean(params.get("q"));if(q){state.search=q;const input=$("#pasProductSearch");if(input)input.value=q;const clear=$("#pasSearchClear");if(clear)clear.hidden=false;}updateCartCount();bindControls();loadProducts();}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
}());
