(function(){
  "use strict";
  const API_BASE="https://test.govjobupdates.com/live-test/store-api";
  const CART_KEY="gjuStoreCart";
  const LEGACY_CART_KEY="gjuPhysicalStoreCart";
  const $=(s)=>document.querySelector(s);
  const $$=(s)=>Array.from(document.querySelectorAll(s));
  const state={product:null,selectedSize:"",selectedColor:"",selectedVariant:null,quantity:1};

  function clean(v){return String(v??"").replace(/\s+/g," ").trim()}
  function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
  function money(p){const a=Math.max(0,Number(p||0))/100;return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:a%1===0?0:2}).format(a)}
  function slug(){return clean(new URLSearchParams(location.search).get("slug"))}
  function readCart(){try{let raw=localStorage.getItem(CART_KEY);if(!raw){raw=localStorage.getItem(LEGACY_CART_KEY);if(raw)localStorage.setItem(CART_KEY,raw)}const c=JSON.parse(raw||"[]");return Array.isArray(c)?c:[]}catch{return[]}}
  function saveCart(cart){localStorage.setItem(CART_KEY,JSON.stringify(cart));updateCartCount()}
  function updateCartCount(){const n=readCart().reduce((s,i)=>s+Math.max(0,Number(i.quantity||0)),0);const el=$("#storeCartCount");if(el)el.textContent=n>99?"99+":String(n)}
  function unique(arr){return [...new Set(arr.filter(v=>clean(v)!=="").map(clean))]}

  function setError(msg){$("#productLoading")?.setAttribute("hidden","");$("#productMain")?.setAttribute("hidden","");$("#productDetails")?.setAttribute("hidden","");const box=$("#productError");if(box){box.hidden=false;$("#productErrorMessage").textContent=msg||"Please try again."}}
  function calcDiscount(mrp,sell){mrp=Number(mrp||0);sell=Number(sell||0);return mrp>sell&&mrp>0?Math.round((mrp-sell)*100/mrp):0}

  function renderImages(images,title){const main=$("#productMainImage"),ph=$("#productImagePlaceholder"),thumbs=$("#productThumbnails");if(!main||!ph||!thumbs)return;const valid=(Array.isArray(images)?images:[]).filter(i=>clean(i.image_url));if(!valid.length){main.hidden=true;ph.hidden=false;thumbs.innerHTML="";return}ph.hidden=true;main.hidden=false;const set=(img)=>{main.src=img.image_url;main.alt=img.alt_text||title||"Product image";$$('.product-thumbnail').forEach(b=>b.classList.toggle('is-active',Number(b.dataset.id)===Number(img.id)))};thumbs.innerHTML=valid.map((i,idx)=>`<button class="product-thumbnail ${idx===0?'is-active':''}" type="button" data-id="${Number(i.id)}"><img src="${esc(i.image_url)}" alt="${esc(i.alt_text||title||'Product image')}" loading="lazy"></button>`).join("");thumbs.querySelectorAll('.product-thumbnail').forEach((b,idx)=>b.addEventListener('click',()=>set(valid[idx])));set(valid[0])}

  function variantMatches(v){if(state.selectedSize&&clean(v.size)!==state.selectedSize)return false;if(state.selectedColor&&clean(v.color)!==state.selectedColor)return false;return true}
  function availableForChoice(kind,val){return state.product.variants.some(v=>{if(kind==='size'&&clean(v.size)!==val)return false;if(kind==='color'&&clean(v.color)!==val)return false;if(kind==='size'&&state.selectedColor&&clean(v.color)!==state.selectedColor)return false;if(kind==='color'&&state.selectedSize&&clean(v.size)!==state.selectedSize)return false;return Number(v.available_qty)>0})}

  function chooseVariant(){const matches=state.product.variants.filter(variantMatches);state.selectedVariant=matches.length===1?matches[0]:null;if(!state.selectedVariant&&matches.length>1){const inStock=matches.find(v=>v.in_stock);if(inStock&&!unique(matches.map(v=>v.size)).length&&!unique(matches.map(v=>v.color)).length)state.selectedVariant=inStock}state.quantity=1;renderVariantUI()}

  function renderOptionGroup(kind,values,containerId,blockId){const block=$(blockId),box=$(containerId);if(!block||!box)return;if(!values.length){block.hidden=true;return}block.hidden=false;const selected=kind==='size'?state.selectedSize:state.selectedColor;box.innerHTML=values.map(v=>`<button type="button" class="variant-option ${selected===v?'is-selected':''} ${availableForChoice(kind,v)?'':'is-unavailable'}" data-value="${esc(v)}" ${availableForChoice(kind,v)?'':'disabled'}>${esc(v)}</button>`).join("");box.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{if(kind==='size')state.selectedSize=b.dataset.value||"";else state.selectedColor=b.dataset.value||"";chooseVariant();renderVariantSelectors()}))}
  function renderVariantSelectors(){const vars=state.product.variants||[];renderOptionGroup('size',unique(vars.map(v=>v.size)),'#sizeOptions','#sizeBlock');renderOptionGroup('color',unique(vars.map(v=>v.color)),'#colorOptions','#colorBlock')}

  function renderVariantUI(){const v=state.selectedVariant;const price=$("#productSellingPrice"),mrp=$("#productMrp"),disc=$("#productDiscount"),note=$("#productPriceNote"),line=$("#selectedVariantLine"),text=$("#selectedVariantText"),stock=$("#selectedStock"),badge=$("#productStockBadge"),btn=$("#addToCartBtn"),qty=$("#productQuantity");qty.value=String(state.quantity);
    if(!v){price.textContent="Select a variant";mrp.hidden=true;disc.hidden=true;note.textContent="Price and availability update when you select a variant.";line.hidden=true;btn.disabled=true;btn.querySelector('span').textContent="Select a Variant";badge.textContent="Choose variant";badge.className='product-stock-badge';return}
    const sell=Number(v.selling_price_paise||0),m=Number(v.mrp_paise||0),av=Number(v.available_qty||0),d=calcDiscount(m,sell);price.textContent=sell>0?money(sell):"Price unavailable";mrp.hidden=!(m>sell&&sell>0);if(!mrp.hidden)mrp.textContent=money(m);disc.hidden=d<=0;if(d>0)disc.textContent=`${d}% OFF`;note.textContent=v.sku?`SKU: ${v.sku}`:"Live variant pricing";line.hidden=false;text.textContent=[v.size,v.color].filter(Boolean).join(' / ')||v.sku||'Selected variant';stock.textContent=av<=0?'Out of stock':av<=3?`Only ${av} left`:`${av} in stock`;stock.className=`selected-stock ${av<=0?'is-out':av<=3?'is-low':''}`.trim();badge.textContent=av<=0?'Sold out':av<=3?`Only ${av} left`:'In stock';badge.className=`product-stock-badge ${av<=0?'is-out':av<=3?'is-low':''}`.trim();const ok=av>0&&sell>0;btn.disabled=!ok;btn.querySelector('span').textContent=ok?'Add to Cart':av<=0?'Out of Stock':'Unavailable';}

  function autoSelect(){const vars=state.product.variants||[];const sizes=unique(vars.map(v=>v.size)),colors=unique(vars.map(v=>v.color));if(sizes.length===1)state.selectedSize=sizes[0];if(colors.length===1)state.selectedColor=colors[0];if(vars.length===1){state.selectedSize=clean(vars[0].size);state.selectedColor=clean(vars[0].color);state.selectedVariant=vars[0]}else chooseVariant();renderVariantSelectors();renderVariantUI()}

  function renderProduct(p){state.product=p;document.title=`${p.title||'Product'} | GovJobUpdates Store`;const meta=document.querySelector('meta[name="description"]');if(meta&&p.meta_description)meta.content=p.meta_description;$("#productBreadcrumb").textContent=p.title||"Product";$("#productBrand").textContent=p.brand?.name||"GovJobUpdates Store";$("#productCategory").textContent=p.category?.name||"";$("#productTitle").textContent=p.title||"Product";$("#productShortDescription").textContent=p.short_description||"";$("#productDescription").textContent=p.description||p.short_description||"Product details will be updated soon.";if(p.care_instructions){$("#careCard").hidden=false;$("#careInstructions").textContent=p.care_instructions}if(p.size_guide){$("#sizeGuideBtn").hidden=false;$("#sizeGuideContent").textContent=p.size_guide}renderImages(p.images,p.title);autoSelect();$("#productLoading").hidden=true;$("#productMain").hidden=false;$("#productDetails").hidden=false}

  async function loadProduct(){const s=slug();if(!s){setError("Missing product link.");return}try{const r=await fetch(`${API_BASE}/product.php?slug=${encodeURIComponent(s)}`,{cache:"no-store",mode:"cors",credentials:"omit",headers:{"X-Requested-With":"XMLHttpRequest"}});const j=await r.json().catch(()=>null);if(!r.ok||!j?.success||!j.product)throw new Error(j?.message||"Product could not be loaded.");renderProduct(j.product)}catch(e){setError(e.message||"Product could not be loaded.")}}

  function maxQty(){const v=state.selectedVariant;if(!v)return 1;return Math.max(1,Math.min(3,Number(v.max_order_qty||3),Number(v.available_qty||0)||1))}
  function changeQty(delta){if(!state.selectedVariant)return;state.quantity=Math.max(1,Math.min(maxQty(),state.quantity+delta));renderVariantUI()}
  function feedback(msg,error=false){const el=$("#cartFeedback");el.textContent=msg||"";el.className=`cart-feedback ${msg?'show':''} ${error?'error':''}`.trim();if(msg)setTimeout(()=>{if(el.textContent===msg){el.textContent="";el.className='cart-feedback'}},3500)}
  function addToCart(){const v=state.selectedVariant;if(!v||!v.in_stock||Number(v.available_qty)<=0){feedback("Please select an available variant.",true);return}const cart=readCart();const existing=cart.find(i=>Number(i.variant_id)===Number(v.id));const allowed=maxQty();if(existing){const next=Math.min(allowed,Number(existing.quantity||0)+state.quantity);if(next===Number(existing.quantity||0)){feedback(`Maximum ${allowed} allowed for this variant.`,true);return}existing.quantity=next}else{cart.push({product_id:Number(state.product.id),variant_id:Number(v.id),slug:state.product.slug,title:state.product.title,brand:state.product.brand?.name||"",category:state.product.category?.name||"",size:v.size||"",color:v.color||"",sku:v.sku||"",quantity:state.quantity,image:state.product.images?.[0]?.image_url||""})}saveCart(cart);feedback(`${state.product.title} added to cart.`)}

  async function checkDelivery(e){e.preventDefault();const pin=clean($("#deliveryPin").value);const out=$("#deliveryResult"),btn=$("#deliveryCheckBtn");out.className='delivery-result';out.textContent="";if(!/^\d{6}$/.test(pin)){out.textContent="Enter a valid 6 digit PIN code.";out.classList.add('error');return}btn.disabled=true;btn.textContent='Checking...';try{const subtotal=state.selectedVariant?Number(state.selectedVariant.selling_price_paise||0)*state.quantity:0;const r=await fetch(`${API_BASE}/delivery-check.php?pin_code=${encodeURIComponent(pin)}&subtotal_paise=${subtotal}`,{cache:'no-store',mode:'cors',credentials:'omit',headers:{"X-Requested-With":"XMLHttpRequest"}});const j=await r.json().catch(()=>null);if(!r.ok||!j?.success)throw new Error(j?.message||'Could not check delivery.');if(!j.serviceable){out.textContent=`Delivery is not available at PIN ${pin} yet.`;out.classList.add('error');return}const bits=[`Delivery available${j.city?` in ${j.city}`:''}.`,j.cod_available?'COD available.':'COD not available.',Number(j.delivery_fee_paise||0)===0?'Free delivery.':`Delivery charge ${money(j.delivery_fee_paise)}.`,j.eta?`ETA: ${j.eta}.`:''].filter(Boolean);out.textContent=bits.join(' ');out.classList.add('success')}catch(err){out.textContent=err.message||'Could not check delivery.';out.classList.add('error')}finally{btn.disabled=false;btn.textContent='Check'}}

  function bind(){$("#quantityMinus")?.addEventListener('click',()=>changeQty(-1));$("#quantityPlus")?.addEventListener('click',()=>changeQty(1));$("#addToCartBtn")?.addEventListener('click',addToCart);$("#deliveryCheckForm")?.addEventListener('submit',checkDelivery);$("#sizeGuideBtn")?.addEventListener('click',()=>{$("#sizeGuideModal").hidden=false});$$('[data-close-size-guide]').forEach(el=>el.addEventListener('click',()=>{$("#sizeGuideModal").hidden=true}));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$("#sizeGuideModal"))$("#sizeGuideModal").hidden=true})}
  function init(){updateCartCount();bind();loadProduct()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
}());
