(function () {
  "use strict";

  window.GJU_TYPING_PASSAGE_BANK = window.GJU_TYPING_PASSAGE_BANK || [];

  const paragraph = (parts) => parts.join("\n\n");

  const easyStory1TheVillageLibrary = paragraph([
    `A young student helps revive a quiet village library and turns it into a welcoming place for readers. The events began on a day that seemed unremarkable. Aman became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `A little later, Rohan looked around and tried to understand what should happen next. Nobody wanted to hurry, because a careful choice was better than a quick mistake. Kiran asked a few questions, listened to the answers, and wrote down the most useful points. The experience showed that useful change often begins with one practical step. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `The next morning, Kiran looked around and tried to understand what should happen next. People nearby noticed what was happening and offered help in their own way. Vijay asked a few questions, listened to the answers, and wrote down the most useful points. The experience showed that useful change often begins with one practical step. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `For a while, Rohan looked around and tried to understand what should happen next. The place felt ordinary, yet every small detail seemed important to the people who were there. Meera asked a few questions, listened to the answers, and wrote down the most useful points. The place felt ordinary, yet every small detail seemed important to the people who were there. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `After that, Sonia looked around and tried to understand what should happen next. The work was not difficult, but it needed time, attention, and cooperation. Vijay asked a few questions, listened to the answers, and wrote down the most useful points. They spoke in simple words and made sure that everyone understood the plan. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `After that, Riya looked around and tried to understand what should happen next. The experience showed that useful change often begins with one practical step. Vijay asked a few questions, listened to the answers, and wrote down the most useful points. They spoke in simple words and made sure that everyone understood the plan. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `After that, Meera looked around and tried to understand what should happen next. Nobody wanted to hurry, because a careful choice was better than a quick mistake. Rohan asked a few questions, listened to the answers, and wrote down the most useful points. The experience showed that useful change often begins with one practical step. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `After that, Meera looked around and tried to understand what should happen next. They spoke in simple words and made sure that everyone understood the plan. Neha asked a few questions, listened to the answers, and wrote down the most useful points. The experience showed that useful change often begins with one practical step. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `After that, Neha looked around and tried to understand what should happen next. Nobody wanted to hurry, because a careful choice was better than a quick mistake. Kiran asked a few questions, listened to the answers, and wrote down the most useful points. The work was not difficult, but it needed time, attention, and cooperation. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `A little later, Kiran looked around and tried to understand what should happen next. People nearby noticed what was happening and offered help in their own way. Meera asked a few questions, listened to the answers, and wrote down the most useful points. The work was not difficult, but it needed time, attention, and cooperation. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the end, the result mattered, but the way people treated one another mattered just as much. The story was remembered because an ordinary day became a lesson in patience, honesty, and shared effort.`
  ]);

  const easyStory2ADayAtTheRailwayStation = paragraph([
    `A family journey begins at a busy railway station filled with small observations and helpful strangers. The events began on a day that seemed unremarkable. Kiran became involved almost by accident, but soon realized that the situation deserved more attention than expected. In the evening, Rohan looked around and tried to understand what should happen next. They spoke in simple words and made sure that everyone understood the plan. Riya asked a few questions, listened to the answers, and wrote down the most useful points. A small problem appeared, and the group solved it without blaming anyone. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `The next morning, Neha looked around and tried to understand what should happen next. Nobody wanted to hurry, because a careful choice was better than a quick mistake. Vijay asked a few questions, listened to the answers, and wrote down the most useful points. The experience showed that useful change often begins with one practical step. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the evening, Aman looked around and tried to understand what should happen next. The work was not difficult, but it needed time, attention, and cooperation. Riya asked a few questions, listened to the answers, and wrote down the most useful points. The place felt ordinary, yet every small detail seemed important to the people who were there. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. By noon, Aman looked around and tried to understand what should happen next. They spoke in simple words and made sure that everyone understood the plan. Meera asked a few questions, listened to the answers, and wrote down the most useful points. They spoke in simple words and made sure that everyone understood the plan. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `The next morning, Sonia looked around and tried to understand what should happen next. A small problem appeared, and the group solved it without blaming anyone. Kiran asked a few questions, listened to the answers, and wrote down the most useful points. Nobody wanted to hurry, because a careful choice was better than a quick mistake. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `After that, Sonia looked around and tried to understand what should happen next. A small problem appeared, and the group solved it without blaming anyone. Meera asked a few questions, listened to the answers, and wrote down the most useful points. Nobody wanted to hurry, because a careful choice was better than a quick mistake. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the evening, Kiran looked around and tried to understand what should happen next. Nobody wanted to hurry, because a careful choice was better than a quick mistake. Vijay asked a few questions, listened to the answers, and wrote down the most useful points. Nobody wanted to hurry, because a careful choice was better than a quick mistake. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `After that, Vijay looked around and tried to understand what should happen next. They spoke in simple words and made sure that everyone understood the plan. Kiran asked a few questions, listened to the answers, and wrote down the most useful points. The experience showed that useful change often begins with one practical step. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `After that, Sonia looked around and tried to understand what should happen next. They spoke in simple words and made sure that everyone understood the plan. Aman asked a few questions, listened to the answers, and wrote down the most useful points. The place felt ordinary, yet every small detail seemed important to the people who were there. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the end, the result mattered, but the way people treated one another mattered just as much. The story was remembered because an ordinary day became a lesson in patience, honesty, and shared effort.`
  ]);

  const easyStory3TheSchoolGarden = paragraph([
    `Students work together to create a garden behind their school and learn patience from the changing seasons. The events began on a day that seemed unremarkable. Sonia became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `The next morning, Vijay looked around and tried to understand what should happen next. By sharing the work, they finished more quickly and enjoyed the task as well. Riya asked a few questions, listened to the answers, and wrote down the most useful points. By sharing the work, they finished more quickly and enjoyed the task as well. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `After that, Sonia looked around and tried to understand what should happen next. The place felt ordinary, yet every small detail seemed important to the people who were there. Rohan asked a few questions, listened to the answers, and wrote down the most useful points. People nearby noticed what was happening and offered help in their own way. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. By noon, Sonia looked around and tried to understand what should happen next. By sharing the work, they finished more quickly and enjoyed the task as well. Meera asked a few questions, listened to the answers, and wrote down the most useful points. Nobody wanted to hurry, because a careful choice was better than a quick mistake. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `For a while, Vijay looked around and tried to understand what should happen next. The place felt ordinary, yet every small detail seemed important to the people who were there. Meera asked a few questions, listened to the answers, and wrote down the most useful points. The work was not difficult, but it needed time, attention, and cooperation. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `A little later, Aman looked around and tried to understand what should happen next. The work was not difficult, but it needed time, attention, and cooperation. Neha asked a few questions, listened to the answers, and wrote down the most useful points. The place felt ordinary, yet every small detail seemed important to the people who were there. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `For a while, Kiran looked around and tried to understand what should happen next. The place felt ordinary, yet every small detail seemed important to the people who were there. Neha asked a few questions, listened to the answers, and wrote down the most useful points. The work was not difficult, but it needed time, attention, and cooperation. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `A little later, Kiran looked around and tried to understand what should happen next. A small problem appeared, and the group solved it without blaming anyone. Aman asked a few questions, listened to the answers, and wrote down the most useful points. The experience showed that useful change often begins with one practical step. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `A little later, Meera looked around and tried to understand what should happen next. The experience showed that useful change often begins with one practical step. Rohan asked a few questions, listened to the answers, and wrote down the most useful points. The work was not difficult, but it needed time, attention, and cooperation. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `A little later, Meera looked around and tried to understand what should happen next. The work was not difficult, but it needed time, attention, and cooperation. Rohan asked a few questions, listened to the answers, and wrote down the most useful points. They spoke in simple words and made sure that everyone understood the plan. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the end, the result mattered, but the way people treated one another mattered just as much. The story was remembered because an ordinary day became a lesson in patience, honesty, and shared effort.`
  ]);

  const easyStory4TheLostWallet = paragraph([
    `A shop assistant finds a wallet on the road and makes a careful effort to return it to its owner. The events began on a day that seemed unremarkable. Kiran became involved almost by accident, but soon realized that the situation deserved more attention than expected. By noon, Riya looked around and tried to understand what should happen next. The work was not difficult, but it needed time, attention, and cooperation. Vijay asked a few questions, listened to the answers, and wrote down the most useful points. The work was not difficult, but it needed time, attention, and cooperation. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `After that, Aman looked around and tried to understand what should happen next. They spoke in simple words and made sure that everyone understood the plan. Vijay asked a few questions, listened to the answers, and wrote down the most useful points. People nearby noticed what was happening and offered help in their own way. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `For a while, Rohan looked around and tried to understand what should happen next. The place felt ordinary, yet every small detail seemed important to the people who were there. Vijay asked a few questions, listened to the answers, and wrote down the most useful points. They spoke in simple words and made sure that everyone understood the plan. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `The next morning, Aman looked around and tried to understand what should happen next. They spoke in simple words and made sure that everyone understood the plan. Riya asked a few questions, listened to the answers, and wrote down the most useful points. Nobody wanted to hurry, because a careful choice was better than a quick mistake. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `After that, Vijay looked around and tried to understand what should happen next. A small problem appeared, and the group solved it without blaming anyone. Rohan asked a few questions, listened to the answers, and wrote down the most useful points. The place felt ordinary, yet every small detail seemed important to the people who were there. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. By noon, Kiran looked around and tried to understand what should happen next. By sharing the work, they finished more quickly and enjoyed the task as well. Aman asked a few questions, listened to the answers, and wrote down the most useful points. The place felt ordinary, yet every small detail seemed important to the people who were there. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. By noon, Aman looked around and tried to understand what should happen next. The place felt ordinary, yet every small detail seemed important to the people who were there. Riya asked a few questions, listened to the answers, and wrote down the most useful points. The experience showed that useful change often begins with one practical step. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the evening, Sonia looked around and tried to understand what should happen next. They spoke in simple words and made sure that everyone understood the plan. Aman asked a few questions, listened to the answers, and wrote down the most useful points. By sharing the work, they finished more quickly and enjoyed the task as well. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `A little later, Sonia looked around and tried to understand what should happen next. The experience showed that useful change often begins with one practical step. Kiran asked a few questions, listened to the answers, and wrote down the most useful points. By sharing the work, they finished more quickly and enjoyed the task as well. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the end, the result mattered, but the way people treated one another mattered just as much. The story was remembered because an ordinary day became a lesson in patience, honesty, and shared effort.`
  ]);

  const easyStory5TheRainyDayPicnic = paragraph([
    `A planned picnic changes when rain arrives, but friends find a cheerful way to enjoy the day indoors. The events began on a day that seemed unremarkable. Sonia became involved almost by accident, but soon realized that the situation deserved more attention than expected. By noon, Kiran looked around and tried to understand what should happen next. The experience showed that useful change often begins with one practical step. Meera asked a few questions, listened to the answers, and wrote down the most useful points. A small problem appeared, and the group solved it without blaming anyone. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. By noon, Neha looked around and tried to understand what should happen next. Nobody wanted to hurry, because a careful choice was better than a quick mistake. Rohan asked a few questions, listened to the answers, and wrote down the most useful points. People nearby noticed what was happening and offered help in their own way. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. By noon, Rohan looked around and tried to understand what should happen next. The place felt ordinary, yet every small detail seemed important to the people who were there. Kiran asked a few questions, listened to the answers, and wrote down the most useful points. The place felt ordinary, yet every small detail seemed important to the people who were there. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. By noon, Aman looked around and tried to understand what should happen next. By sharing the work, they finished more quickly and enjoyed the task as well. Neha asked a few questions, listened to the answers, and wrote down the most useful points. Nobody wanted to hurry, because a careful choice was better than a quick mistake. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the evening, Rohan looked around and tried to understand what should happen next. A small problem appeared, and the group solved it without blaming anyone. Aman asked a few questions, listened to the answers, and wrote down the most useful points. Nobody wanted to hurry, because a careful choice was better than a quick mistake. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `For a while, Rohan looked around and tried to understand what should happen next. The experience showed that useful change often begins with one practical step. Kiran asked a few questions, listened to the answers, and wrote down the most useful points. People nearby noticed what was happening and offered help in their own way. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the evening, Aman looked around and tried to understand what should happen next. A small problem appeared, and the group solved it without blaming anyone. Neha asked a few questions, listened to the answers, and wrote down the most useful points. A small problem appeared, and the group solved it without blaming anyone. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `The next morning, Sonia looked around and tried to understand what should happen next. By sharing the work, they finished more quickly and enjoyed the task as well. Rohan asked a few questions, listened to the answers, and wrote down the most useful points. People nearby noticed what was happening and offered help in their own way. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. By noon, Meera looked around and tried to understand what should happen next. Nobody wanted to hurry, because a careful choice was better than a quick mistake. Sonia asked a few questions, listened to the answers, and wrote down the most useful points. The place felt ordinary, yet every small detail seemed important to the people who were there. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the end, the result mattered, but the way people treated one another mattered just as much. The story was remembered because an ordinary day became a lesson in patience, honesty, and shared effort.`
  ]);

  const easyStory6TheHelpfulBusDriver = paragraph([
    `A bus driver notices a confused elderly passenger and quietly helps him reach the right stop. The events began on a day that seemed unremarkable. Vijay became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `A little later, Aman looked around and tried to understand what should happen next. By sharing the work, they finished more quickly and enjoyed the task as well. Riya asked a few questions, listened to the answers, and wrote down the most useful points. The place felt ordinary, yet every small detail seemed important to the people who were there. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `The next morning, Vijay looked around and tried to understand what should happen next. The place felt ordinary, yet every small detail seemed important to the people who were there. Sonia asked a few questions, listened to the answers, and wrote down the most useful points. The work was not difficult, but it needed time, attention, and cooperation. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the evening, Meera looked around and tried to understand what should happen next. They spoke in simple words and made sure that everyone understood the plan. Vijay asked a few questions, listened to the answers, and wrote down the most useful points. Nobody wanted to hurry, because a careful choice was better than a quick mistake. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `After that, Aman looked around and tried to understand what should happen next. The place felt ordinary, yet every small detail seemed important to the people who were there. Neha asked a few questions, listened to the answers, and wrote down the most useful points. A small problem appeared, and the group solved it without blaming anyone. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. By noon, Meera looked around and tried to understand what should happen next. The place felt ordinary, yet every small detail seemed important to the people who were there. Vijay asked a few questions, listened to the answers, and wrote down the most useful points. The place felt ordinary, yet every small detail seemed important to the people who were there. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `The next morning, Meera looked around and tried to understand what should happen next. Nobody wanted to hurry, because a careful choice was better than a quick mistake. Kiran asked a few questions, listened to the answers, and wrote down the most useful points. Nobody wanted to hurry, because a careful choice was better than a quick mistake. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the evening, Kiran looked around and tried to understand what should happen next. By sharing the work, they finished more quickly and enjoyed the task as well. Aman asked a few questions, listened to the answers, and wrote down the most useful points. The experience showed that useful change often begins with one practical step. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `The next morning, Vijay looked around and tried to understand what should happen next. The experience showed that useful change often begins with one practical step. Neha asked a few questions, listened to the answers, and wrote down the most useful points. Nobody wanted to hurry, because a careful choice was better than a quick mistake. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. By noon, Kiran looked around and tried to understand what should happen next. They spoke in simple words and made sure that everyone understood the plan. Vijay asked a few questions, listened to the answers, and wrote down the most useful points. By sharing the work, they finished more quickly and enjoyed the task as well. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the end, the result mattered, but the way people treated one another mattered just as much. The story was remembered because an ordinary day became a lesson in patience, honesty, and shared effort.`
  ]);

  const easyStory7TheOldBicycle = paragraph([
    `A teenager repairs an old bicycle that belonged to his father and discovers the pleasure of fixing things by hand. The events began on a day that seemed unremarkable. Aman became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `The next morning, Neha looked around and tried to understand what should happen next. They spoke in simple words and made sure that everyone understood the plan. Sonia asked a few questions, listened to the answers, and wrote down the most useful points. The work was not difficult, but it needed time, attention, and cooperation. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the evening, Aman looked around and tried to understand what should happen next. The work was not difficult, but it needed time, attention, and cooperation. Vijay asked a few questions, listened to the answers, and wrote down the most useful points. The place felt ordinary, yet every small detail seemed important to the people who were there. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the evening, Meera looked around and tried to understand what should happen next. The place felt ordinary, yet every small detail seemed important to the people who were there. Vijay asked a few questions, listened to the answers, and wrote down the most useful points. The place felt ordinary, yet every small detail seemed important to the people who were there. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `For a while, Rohan looked around and tried to understand what should happen next. Nobody wanted to hurry, because a careful choice was better than a quick mistake. Riya asked a few questions, listened to the answers, and wrote down the most useful points. Nobody wanted to hurry, because a careful choice was better than a quick mistake. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. By noon, Aman looked around and tried to understand what should happen next. The experience showed that useful change often begins with one practical step. Neha asked a few questions, listened to the answers, and wrote down the most useful points. A small problem appeared, and the group solved it without blaming anyone. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `The next morning, Rohan looked around and tried to understand what should happen next. The place felt ordinary, yet every small detail seemed important to the people who were there. Vijay asked a few questions, listened to the answers, and wrote down the most useful points. People nearby noticed what was happening and offered help in their own way. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `After that, Vijay looked around and tried to understand what should happen next. The work was not difficult, but it needed time, attention, and cooperation. Aman asked a few questions, listened to the answers, and wrote down the most useful points. The place felt ordinary, yet every small detail seemed important to the people who were there. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. By noon, Sonia looked around and tried to understand what should happen next. By sharing the work, they finished more quickly and enjoyed the task as well. Aman asked a few questions, listened to the answers, and wrote down the most useful points. The experience showed that useful change often begins with one practical step. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. By noon, Kiran looked around and tried to understand what should happen next. The place felt ordinary, yet every small detail seemed important to the people who were there. Neha asked a few questions, listened to the answers, and wrote down the most useful points. The experience showed that useful change often begins with one practical step. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the end, the result mattered, but the way people treated one another mattered just as much. The story was remembered because an ordinary day became a lesson in patience, honesty, and shared effort.`
  ]);

  const easyStory8TheMorningMarket = paragraph([
    `A child visits the town market with her mother and learns how sellers prepare before the streets become crowded. The events began on a day that seemed unremarkable. Sonia became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `For a while, Vijay looked around and tried to understand what should happen next. Nobody wanted to hurry, because a careful choice was better than a quick mistake. Aman asked a few questions, listened to the answers, and wrote down the most useful points. The place felt ordinary, yet every small detail seemed important to the people who were there. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `For a while, Neha looked around and tried to understand what should happen next. Nobody wanted to hurry, because a careful choice was better than a quick mistake. Kiran asked a few questions, listened to the answers, and wrote down the most useful points. People nearby noticed what was happening and offered help in their own way. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `A little later, Aman looked around and tried to understand what should happen next. People nearby noticed what was happening and offered help in their own way. Meera asked a few questions, listened to the answers, and wrote down the most useful points. A small problem appeared, and the group solved it without blaming anyone. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `A little later, Sonia looked around and tried to understand what should happen next. The place felt ordinary, yet every small detail seemed important to the people who were there. Riya asked a few questions, listened to the answers, and wrote down the most useful points. The work was not difficult, but it needed time, attention, and cooperation. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `After that, Riya looked around and tried to understand what should happen next. The experience showed that useful change often begins with one practical step. Sonia asked a few questions, listened to the answers, and wrote down the most useful points. People nearby noticed what was happening and offered help in their own way. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `A little later, Riya looked around and tried to understand what should happen next. The work was not difficult, but it needed time, attention, and cooperation. Sonia asked a few questions, listened to the answers, and wrote down the most useful points. People nearby noticed what was happening and offered help in their own way. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `For a while, Rohan looked around and tried to understand what should happen next. Nobody wanted to hurry, because a careful choice was better than a quick mistake. Kiran asked a few questions, listened to the answers, and wrote down the most useful points. By sharing the work, they finished more quickly and enjoyed the task as well. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the evening, Sonia looked around and tried to understand what should happen next. People nearby noticed what was happening and offered help in their own way. Neha asked a few questions, listened to the answers, and wrote down the most useful points. They spoke in simple words and made sure that everyone understood the plan. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `For a while, Vijay looked around and tried to understand what should happen next. People nearby noticed what was happening and offered help in their own way. Rohan asked a few questions, listened to the answers, and wrote down the most useful points. The experience showed that useful change often begins with one practical step. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the end, the result mattered, but the way people treated one another mattered just as much. The story was remembered because an ordinary day became a lesson in patience, honesty, and shared effort.`
  ]);

  const easyStory9TheNewNeighbor = paragraph([
    `A family welcomes a new neighbor, and a simple shared meal begins a lasting friendship. The events began on a day that seemed unremarkable. Neha became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `A little later, Aman looked around and tried to understand what should happen next. Nobody wanted to hurry, because a careful choice was better than a quick mistake. Rohan asked a few questions, listened to the answers, and wrote down the most useful points. By sharing the work, they finished more quickly and enjoyed the task as well. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `After that, Rohan looked around and tried to understand what should happen next. A small problem appeared, and the group solved it without blaming anyone. Riya asked a few questions, listened to the answers, and wrote down the most useful points. Nobody wanted to hurry, because a careful choice was better than a quick mistake. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `A little later, Rohan looked around and tried to understand what should happen next. Nobody wanted to hurry, because a careful choice was better than a quick mistake. Riya asked a few questions, listened to the answers, and wrote down the most useful points. By sharing the work, they finished more quickly and enjoyed the task as well. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `After that, Riya looked around and tried to understand what should happen next. People nearby noticed what was happening and offered help in their own way. Meera asked a few questions, listened to the answers, and wrote down the most useful points. By sharing the work, they finished more quickly and enjoyed the task as well. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `A little later, Neha looked around and tried to understand what should happen next. People nearby noticed what was happening and offered help in their own way. Kiran asked a few questions, listened to the answers, and wrote down the most useful points. They spoke in simple words and made sure that everyone understood the plan. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `After that, Sonia looked around and tried to understand what should happen next. The work was not difficult, but it needed time, attention, and cooperation. Kiran asked a few questions, listened to the answers, and wrote down the most useful points. The experience showed that useful change often begins with one practical step. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. By noon, Neha looked around and tried to understand what should happen next. By sharing the work, they finished more quickly and enjoyed the task as well. Rohan asked a few questions, listened to the answers, and wrote down the most useful points. A small problem appeared, and the group solved it without blaming anyone. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. By noon, Meera looked around and tried to understand what should happen next. The experience showed that useful change often begins with one practical step. Riya asked a few questions, listened to the answers, and wrote down the most useful points. People nearby noticed what was happening and offered help in their own way. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. By noon, Vijay looked around and tried to understand what should happen next. By sharing the work, they finished more quickly and enjoyed the task as well. Aman asked a few questions, listened to the answers, and wrote down the most useful points. A small problem appeared, and the group solved it without blaming anyone. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the end, the result mattered, but the way people treated one another mattered just as much. The story was remembered because an ordinary day became a lesson in patience, honesty, and shared effort.`
  ]);

  const easyStory10TheLittleTeaShop = paragraph([
    `A small tea shop near a college becomes a place where students exchange ideas, jokes, and everyday kindness. The events began on a day that seemed unremarkable. Rohan became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `A little later, Riya looked around and tried to understand what should happen next. The experience showed that useful change often begins with one practical step. Rohan asked a few questions, listened to the answers, and wrote down the most useful points. The experience showed that useful change often begins with one practical step. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `For a while, Neha looked around and tried to understand what should happen next. The work was not difficult, but it needed time, attention, and cooperation. Rohan asked a few questions, listened to the answers, and wrote down the most useful points. Nobody wanted to hurry, because a careful choice was better than a quick mistake. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the evening, Vijay looked around and tried to understand what should happen next. They spoke in simple words and made sure that everyone understood the plan. Neha asked a few questions, listened to the answers, and wrote down the most useful points. The experience showed that useful change often begins with one practical step. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `The next morning, Vijay looked around and tried to understand what should happen next. Nobody wanted to hurry, because a careful choice was better than a quick mistake. Meera asked a few questions, listened to the answers, and wrote down the most useful points. The place felt ordinary, yet every small detail seemed important to the people who were there. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `The next morning, Meera looked around and tried to understand what should happen next. They spoke in simple words and made sure that everyone understood the plan. Vijay asked a few questions, listened to the answers, and wrote down the most useful points. They spoke in simple words and made sure that everyone understood the plan. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the evening, Neha looked around and tried to understand what should happen next. The place felt ordinary, yet every small detail seemed important to the people who were there. Kiran asked a few questions, listened to the answers, and wrote down the most useful points. The work was not difficult, but it needed time, attention, and cooperation. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `After that, Riya looked around and tried to understand what should happen next. The place felt ordinary, yet every small detail seemed important to the people who were there. Vijay asked a few questions, listened to the answers, and wrote down the most useful points. The place felt ordinary, yet every small detail seemed important to the people who were there. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `A little later, Aman looked around and tried to understand what should happen next. The place felt ordinary, yet every small detail seemed important to the people who were there. Meera asked a few questions, listened to the answers, and wrote down the most useful points. A small problem appeared, and the group solved it without blaming anyone. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `The next morning, Rohan looked around and tried to understand what should happen next. The work was not difficult, but it needed time, attention, and cooperation. Aman asked a few questions, listened to the answers, and wrote down the most useful points. A small problem appeared, and the group solved it without blaming anyone. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the end, the result mattered, but the way people treated one another mattered just as much. The story was remembered because an ordinary day became a lesson in patience, honesty, and shared effort.`
  ]);

  const easyStory11TheRiverCleanUp = paragraph([
    `Local children and adults spend a Sunday cleaning the riverbank and decide how to keep it clean. The events began on a day that seemed unremarkable. Vijay became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `For a while, Meera looked around and tried to understand what should happen next. The experience showed that useful change often begins with one practical step. Aman asked a few questions, listened to the answers, and wrote down the most useful points. They spoke in simple words and made sure that everyone understood the plan. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `A little later, Sonia looked around and tried to understand what should happen next. By sharing the work, they finished more quickly and enjoyed the task as well. Rohan asked a few questions, listened to the answers, and wrote down the most useful points. A small problem appeared, and the group solved it without blaming anyone. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `The next morning, Riya looked around and tried to understand what should happen next. A small problem appeared, and the group solved it without blaming anyone. Rohan asked a few questions, listened to the answers, and wrote down the most useful points. The experience showed that useful change often begins with one practical step. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the evening, Riya looked around and tried to understand what should happen next. The work was not difficult, but it needed time, attention, and cooperation. Neha asked a few questions, listened to the answers, and wrote down the most useful points. Nobody wanted to hurry, because a careful choice was better than a quick mistake. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `A little later, Vijay looked around and tried to understand what should happen next. The place felt ordinary, yet every small detail seemed important to the people who were there. Rohan asked a few questions, listened to the answers, and wrote down the most useful points. By sharing the work, they finished more quickly and enjoyed the task as well. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `For a while, Aman looked around and tried to understand what should happen next. A small problem appeared, and the group solved it without blaming anyone. Vijay asked a few questions, listened to the answers, and wrote down the most useful points. They spoke in simple words and made sure that everyone understood the plan. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. By noon, Riya looked around and tried to understand what should happen next. By sharing the work, they finished more quickly and enjoyed the task as well. Neha asked a few questions, listened to the answers, and wrote down the most useful points. The work was not difficult, but it needed time, attention, and cooperation. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `For a while, Sonia looked around and tried to understand what should happen next. They spoke in simple words and made sure that everyone understood the plan. Kiran asked a few questions, listened to the answers, and wrote down the most useful points. By sharing the work, they finished more quickly and enjoyed the task as well. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. By noon, Riya looked around and tried to understand what should happen next. The experience showed that useful change often begins with one practical step. Sonia asked a few questions, listened to the answers, and wrote down the most useful points. The work was not difficult, but it needed time, attention, and cooperation. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the end, the result mattered, but the way people treated one another mattered just as much. The story was remembered because an ordinary day became a lesson in patience, honesty, and shared effort.`
  ]);

  const easyStory12TheFirstDayAtWork = paragraph([
    `A young man starts his first office job, makes a few harmless mistakes, and slowly gains confidence. The events began on a day that seemed unremarkable. Vijay became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `The next morning, Neha looked around and tried to understand what should happen next. The experience showed that useful change often begins with one practical step. Riya asked a few questions, listened to the answers, and wrote down the most useful points. The work was not difficult, but it needed time, attention, and cooperation. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `The next morning, Aman looked around and tried to understand what should happen next. A small problem appeared, and the group solved it without blaming anyone. Neha asked a few questions, listened to the answers, and wrote down the most useful points. The experience showed that useful change often begins with one practical step. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the evening, Rohan looked around and tried to understand what should happen next. They spoke in simple words and made sure that everyone understood the plan. Vijay asked a few questions, listened to the answers, and wrote down the most useful points. By sharing the work, they finished more quickly and enjoyed the task as well. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the evening, Aman looked around and tried to understand what should happen next. By sharing the work, they finished more quickly and enjoyed the task as well. Rohan asked a few questions, listened to the answers, and wrote down the most useful points. Nobody wanted to hurry, because a careful choice was better than a quick mistake. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `A little later, Rohan looked around and tried to understand what should happen next. By sharing the work, they finished more quickly and enjoyed the task as well. Sonia asked a few questions, listened to the answers, and wrote down the most useful points. People nearby noticed what was happening and offered help in their own way. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the evening, Rohan looked around and tried to understand what should happen next. The experience showed that useful change often begins with one practical step. Meera asked a few questions, listened to the answers, and wrote down the most useful points. They spoke in simple words and made sure that everyone understood the plan. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `After that, Meera looked around and tried to understand what should happen next. Nobody wanted to hurry, because a careful choice was better than a quick mistake. Riya asked a few questions, listened to the answers, and wrote down the most useful points. They spoke in simple words and made sure that everyone understood the plan. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `A little later, Meera looked around and tried to understand what should happen next. Nobody wanted to hurry, because a careful choice was better than a quick mistake. Vijay asked a few questions, listened to the answers, and wrote down the most useful points. The place felt ordinary, yet every small detail seemed important to the people who were there. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement.`,
    `After that, Neha looked around and tried to understand what should happen next. The work was not difficult, but it needed time, attention, and cooperation. Sonia asked a few questions, listened to the answers, and wrote down the most useful points. The work was not difficult, but it needed time, attention, and cooperation. They agreed to complete one clear task before moving to another. This kept the work calm and prevented confusion. At the end of the hour, everyone could see a small but real improvement. In the end, the result mattered, but the way people treated one another mattered just as much. The story was remembered because an ordinary day became a lesson in patience, honesty, and shared effort. Medium Level`
  ]);

  [
    ['general-english', 'general', 'general'],
    ['ssc-chsl-english', 'ssc', 'chsl'],
    ['ssc-cgl-dest-english', 'ssc', 'cgl-dest'],
    ['ssc-delhi-police-hc-ministerial-english', 'ssc', 'delhi-police-hc-ministerial'],
    ['ssc-stenographer-english', 'ssc', 'stenographer'],
    ['ssc-selection-post-english', 'ssc', 'selection-post'],
    ['railway-rrb-ntpc-english', 'railway', 'rrb-ntpc'],
    ['railway-junior-clerk-english', 'railway', 'junior-clerk'],
    ['railway-accounts-clerk-english', 'railway', 'accounts-clerk'],
    ['upsssc-junior-assistant-english', 'up-government', 'upsssc-junior-assistant'],
    ['up-police-computer-operator-english', 'up-government', 'up-police-computer-operator'],
    ['up-clerical-english', 'up-government', 'up-clerical'],
    ['banking-language-practice-english', 'banking', 'language-practice'],
    ['ibps-clerk-english', 'banking', 'ibps-clerk'],
    ['sbi-clerk-english', 'banking', 'sbi-clerk'],
    ['rbi-assistant-english', 'banking', 'rbi-assistant']
  ].forEach(([id, category, exam]) => {
    window.GJU_TYPING_PASSAGE_BANK.push({
      id,
      language: "english",
      category,
      exam,
      levels: {
        easy: [easyStory1TheVillageLibrary, easyStory2ADayAtTheRailwayStation, easyStory3TheSchoolGarden, easyStory4TheLostWallet, easyStory5TheRainyDayPicnic, easyStory6TheHelpfulBusDriver, easyStory7TheOldBicycle, easyStory8TheMorningMarket, easyStory9TheNewNeighbor, easyStory10TheLittleTeaShop, easyStory11TheRiverCleanUp, easyStory12TheFirstDayAtWork],
        medium: [],
        hard: []
      }
    });
  });
})();
