(function () {
  "use strict";

  window.GJU_TYPING_PASSAGE_BANK = window.GJU_TYPING_PASSAGE_BANK || [];

  const paragraph = (parts) => parts.join("\n\n");

  const hardStory25TheArchiveBeneathTheCourthouse = paragraph([
    `A researcher examining neglected municipal records uncovers a complicated story about land, memory, and public responsibility. The events began on a day that seemed unremarkable. Nandita became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `Nevertheless, Raghav and Sameer examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The episode demonstrated how difficult public choices often involve tradeoffs among legitimate goals rather than a simple contest between right and wrong. Historical records complicated the discussion by showing that earlier decisions had produced consequences their authors had neither intended nor predicted. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `Nevertheless, Ananya and Ishaan examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. Historical records complicated the discussion by showing that earlier decisions had produced consequences their authors had neither intended nor predicted. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `During the subsequent review, Nandita and Aditya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The argument became more precise once the group separated factual uncertainty from genuine disagreement about values and priorities. Rather than searching for a perfect answer, the team developed safeguards, review procedures, and criteria for revising the decision when new evidence appeared. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `Against this background, Ishaan and Ananya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The episode demonstrated how difficult public choices often involve tradeoffs among legitimate goals rather than a simple contest between right and wrong. The argument became more precise once the group separated factual uncertainty from genuine disagreement about values and priorities. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `As the implications became clearer, Zoya and Nandita examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The available evidence was substantial but incomplete, requiring the participants to distinguish confident conclusions from plausible interpretation. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `During the subsequent review, Sameer and Ishaan examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. The argument became more precise once the group separated factual uncertainty from genuine disagreement about values and priorities. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `The final decision remained open to revision, which some observers initially regarded as weakness. Over time, however, that openness proved to be a strength: it acknowledged uncertainty while preserving accountability, allowing future evidence to improve rather than merely defend the original choice.`
  ]);

  const hardStory26TheLastWeatherObserver = paragraph([
    `An experienced observer at a remote station confronts automation while documenting subtle environmental changes. The events began on a day that seemed unremarkable. Sameer became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `Against this background, Aditya and Mira examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The argument became more precise once the group separated factual uncertainty from genuine disagreement about values and priorities. Rather than searching for a perfect answer, the team developed safeguards, review procedures, and criteria for revising the decision when new evidence appeared. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `As the implications became clearer, Sameer and Aditya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The argument became more precise once the group separated factual uncertainty from genuine disagreement about values and priorities. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `By contrast, Zoya and Raghav examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. The argument became more precise once the group separated factual uncertainty from genuine disagreement about values and priorities. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `As the implications became clearer, Nandita and Ananya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. Several participants warned that a solution optimized for immediate performance might create less visible costs that would emerge only over time. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `During the subsequent review, Sameer and Ananya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `As the implications became clearer, Nandita and Raghav examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The argument became more precise once the group separated factual uncertainty from genuine disagreement about values and priorities. Historical records complicated the discussion by showing that earlier decisions had produced consequences their authors had neither intended nor predicted. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `The final decision remained open to revision, which some observers initially regarded as weakness. Over time, however, that openness proved to be a strength: it acknowledged uncertainty while preserving accountability, allowing future evidence to improve rather than merely defend the original choice.`
  ]);

  const hardStory27TheAlgorithmAndTheApplicant = paragraph([
    `A hiring system produces efficient rankings, but an analyst discovers patterns that raise difficult questions about fairness. The events began on a day that seemed unremarkable. Ananya became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `Against this background, Aditya and Raghav examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. Historical records complicated the discussion by showing that earlier decisions had produced consequences their authors had neither intended nor predicted. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `As the implications became clearer, Raghav and Nandita examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The argument became more precise once the group separated factual uncertainty from genuine disagreement about values and priorities. The episode demonstrated how difficult public choices often involve tradeoffs among legitimate goals rather than a simple contest between right and wrong. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `During the subsequent review, Nandita and Zoya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Historical records complicated the discussion by showing that earlier decisions had produced consequences their authors had neither intended nor predicted. The argument became more precise once the group separated factual uncertainty from genuine disagreement about values and priorities. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `In retrospect, Mira and Aditya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Several participants warned that a solution optimized for immediate performance might create less visible costs that would emerge only over time. Several participants warned that a solution optimized for immediate performance might create less visible costs that would emerge only over time. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `During the subsequent review, Raghav and Zoya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The episode demonstrated how difficult public choices often involve tradeoffs among legitimate goals rather than a simple contest between right and wrong. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `During the subsequent review, Ananya and Zoya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The episode demonstrated how difficult public choices often involve tradeoffs among legitimate goals rather than a simple contest between right and wrong. The episode demonstrated how difficult public choices often involve tradeoffs among legitimate goals rather than a simple contest between right and wrong. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `The final decision remained open to revision, which some observers initially regarded as weakness. Over time, however, that openness proved to be a strength: it acknowledged uncertainty while preserving accountability, allowing future evidence to improve rather than merely defend the original choice.`
  ]);

  const hardStory28TheCityWithoutMaps = paragraph([
    `After a data failure disrupts digital navigation, residents rediscover informal knowledge of streets and neighborhoods. The events began on a day that seemed unremarkable. Ishaan became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `By contrast, Raghav and Ishaan examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Historical records complicated the discussion by showing that earlier decisions had produced consequences their authors had neither intended nor predicted. Rather than searching for a perfect answer, the team developed safeguards, review procedures, and criteria for revising the decision when new evidence appeared. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `By contrast, Raghav and Sameer examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The episode demonstrated how difficult public choices often involve tradeoffs among legitimate goals rather than a simple contest between right and wrong. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `Nevertheless, Ananya and Sameer examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Rather than searching for a perfect answer, the team developed safeguards, review procedures, and criteria for revising the decision when new evidence appeared. The available evidence was substantial but incomplete, requiring the participants to distinguish confident conclusions from plausible interpretation. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `As the implications became clearer, Raghav and Ishaan examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Several participants warned that a solution optimized for immediate performance might create less visible costs that would emerge only over time. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `By contrast, Zoya and Ananya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The argument became more precise once the group separated factual uncertainty from genuine disagreement about values and priorities. Several participants warned that a solution optimized for immediate performance might create less visible costs that would emerge only over time. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `By contrast, Aditya and Ishaan examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. Historical records complicated the discussion by showing that earlier decisions had produced consequences their authors had neither intended nor predicted. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `The final decision remained open to revision, which some observers initially regarded as weakness. Over time, however, that openness proved to be a strength: it acknowledged uncertainty while preserving accountability, allowing future evidence to improve rather than merely defend the original choice.`
  ]);

  const hardStory29TheRestorationOfBellTower = paragraph([
    `Engineers, historians, and residents disagree about how to restore a damaged landmark without erasing evidence of its age. The events began on a day that seemed unremarkable. Mira became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `As the implications became clearer, Nandita and Zoya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The available evidence was substantial but incomplete, requiring the participants to distinguish confident conclusions from plausible interpretation. The argument became more precise once the group separated factual uncertainty from genuine disagreement about values and priorities. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `As the implications became clearer, Mira and Ishaan examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Historical records complicated the discussion by showing that earlier decisions had produced consequences their authors had neither intended nor predicted. The available evidence was substantial but incomplete, requiring the participants to distinguish confident conclusions from plausible interpretation. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `Against this background, Nandita and Ananya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The episode demonstrated how difficult public choices often involve tradeoffs among legitimate goals rather than a simple contest between right and wrong. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `During the subsequent review, Zoya and Mira examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. The episode demonstrated how difficult public choices often involve tradeoffs among legitimate goals rather than a simple contest between right and wrong. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `Nevertheless, Nandita and Aditya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Rather than searching for a perfect answer, the team developed safeguards, review procedures, and criteria for revising the decision when new evidence appeared. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `During the subsequent review, Nandita and Aditya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `The final decision remained open to revision, which some observers initially regarded as weakness. Over time, however, that openness proved to be a strength: it acknowledged uncertainty while preserving accountability, allowing future evidence to improve rather than merely defend the original choice.`
  ]);

  const hardStory30TheTranslatorSDilemma = paragraph([
    `A literary translator must choose between literal accuracy and cultural meaning while working on an ambiguous manuscript. The events began on a day that seemed unremarkable. Sameer became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `Against this background, Ishaan and Raghav examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The argument became more precise once the group separated factual uncertainty from genuine disagreement about values and priorities. Rather than searching for a perfect answer, the team developed safeguards, review procedures, and criteria for revising the decision when new evidence appeared. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `During the subsequent review, Mira and Sameer examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The available evidence was substantial but incomplete, requiring the participants to distinguish confident conclusions from plausible interpretation. The argument became more precise once the group separated factual uncertainty from genuine disagreement about values and priorities. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `By contrast, Nandita and Ananya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The argument became more precise once the group separated factual uncertainty from genuine disagreement about values and priorities. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `By contrast, Ananya and Raghav examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Historical records complicated the discussion by showing that earlier decisions had produced consequences their authors had neither intended nor predicted. The argument became more precise once the group separated factual uncertainty from genuine disagreement about values and priorities. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `During the subsequent review, Zoya and Raghav examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. The episode demonstrated how difficult public choices often involve tradeoffs among legitimate goals rather than a simple contest between right and wrong. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `Against this background, Sameer and Ananya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Several participants warned that a solution optimized for immediate performance might create less visible costs that would emerge only over time. The episode demonstrated how difficult public choices often involve tradeoffs among legitimate goals rather than a simple contest between right and wrong. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `The final decision remained open to revision, which some observers initially regarded as weakness. Over time, however, that openness proved to be a strength: it acknowledged uncertainty while preserving accountability, allowing future evidence to improve rather than merely defend the original choice.`
  ]);

  const hardStory31TheSilentReservoir = paragraph([
    `A declining reservoir forces neighboring districts to negotiate water use, ecological protection, and uncertain forecasts. The events began on a day that seemed unremarkable. Nandita became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `In retrospect, Zoya and Ananya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Rather than searching for a perfect answer, the team developed safeguards, review procedures, and criteria for revising the decision when new evidence appeared. Rather than searching for a perfect answer, the team developed safeguards, review procedures, and criteria for revising the decision when new evidence appeared. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `In retrospect, Mira and Sameer examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The argument became more precise once the group separated factual uncertainty from genuine disagreement about values and priorities. Historical records complicated the discussion by showing that earlier decisions had produced consequences their authors had neither intended nor predicted. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `During the subsequent review, Raghav and Sameer examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Historical records complicated the discussion by showing that earlier decisions had produced consequences their authors had neither intended nor predicted. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `By contrast, Zoya and Ishaan examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. Several participants warned that a solution optimized for immediate performance might create less visible costs that would emerge only over time. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `By contrast, Sameer and Mira examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The episode demonstrated how difficult public choices often involve tradeoffs among legitimate goals rather than a simple contest between right and wrong. Historical records complicated the discussion by showing that earlier decisions had produced consequences their authors had neither intended nor predicted. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `In retrospect, Zoya and Nandita examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. Several participants warned that a solution optimized for immediate performance might create less visible costs that would emerge only over time. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `The final decision remained open to revision, which some observers initially regarded as weakness. Over time, however, that openness proved to be a strength: it acknowledged uncertainty while preserving accountability, allowing future evidence to improve rather than merely defend the original choice.`
  ]);

  const hardStory32TheMuseumAfterMidnight = paragraph([
    `A curator preparing a controversial exhibition reflects on ownership, interpretation, and the stories museums choose to tell. The events began on a day that seemed unremarkable. Mira became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `By contrast, Zoya and Aditya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `In retrospect, Zoya and Sameer examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The available evidence was substantial but incomplete, requiring the participants to distinguish confident conclusions from plausible interpretation. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `Nevertheless, Ananya and Nandita examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The argument became more precise once the group separated factual uncertainty from genuine disagreement about values and priorities. Rather than searching for a perfect answer, the team developed safeguards, review procedures, and criteria for revising the decision when new evidence appeared. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `As the implications became clearer, Zoya and Ishaan examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. The available evidence was substantial but incomplete, requiring the participants to distinguish confident conclusions from plausible interpretation. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `During the subsequent review, Zoya and Raghav examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Historical records complicated the discussion by showing that earlier decisions had produced consequences their authors had neither intended nor predicted. The available evidence was substantial but incomplete, requiring the participants to distinguish confident conclusions from plausible interpretation. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `During the subsequent review, Mira and Ishaan examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Historical records complicated the discussion by showing that earlier decisions had produced consequences their authors had neither intended nor predicted. Several participants warned that a solution optimized for immediate performance might create less visible costs that would emerge only over time. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `The final decision remained open to revision, which some observers initially regarded as weakness. Over time, however, that openness proved to be a strength: it acknowledged uncertainty while preserving accountability, allowing future evidence to improve rather than merely defend the original choice.`
  ]);

  const hardStory33TheObservatoryDebate = paragraph([
    `Scientists debate whether limited telescope time should favor a risky new hypothesis or established research programs. The events began on a day that seemed unremarkable. Raghav became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `By contrast, Zoya and Sameer examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The argument became more precise once the group separated factual uncertainty from genuine disagreement about values and priorities. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `Nevertheless, Zoya and Raghav examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. Rather than searching for a perfect answer, the team developed safeguards, review procedures, and criteria for revising the decision when new evidence appeared. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `During the subsequent review, Zoya and Mira examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The argument became more precise once the group separated factual uncertainty from genuine disagreement about values and priorities. Rather than searching for a perfect answer, the team developed safeguards, review procedures, and criteria for revising the decision when new evidence appeared. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `As the implications became clearer, Ishaan and Mira examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. Rather than searching for a perfect answer, the team developed safeguards, review procedures, and criteria for revising the decision when new evidence appeared. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `As the implications became clearer, Ishaan and Aditya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Historical records complicated the discussion by showing that earlier decisions had produced consequences their authors had neither intended nor predicted. Several participants warned that a solution optimized for immediate performance might create less visible costs that would emerge only over time. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `During the subsequent review, Raghav and Ananya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `The final decision remained open to revision, which some observers initially regarded as weakness. Over time, however, that openness proved to be a strength: it acknowledged uncertainty while preserving accountability, allowing future evidence to improve rather than merely defend the original choice.`
  ]);

  const hardStory34TheUnfinishedConstitution = paragraph([
    `Students discover an abandoned fictional constitution draft and analyze how its compromises shaped a divided society. The events began on a day that seemed unremarkable. Sameer became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `By contrast, Ishaan and Ananya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The available evidence was substantial but incomplete, requiring the participants to distinguish confident conclusions from plausible interpretation. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `Nevertheless, Ishaan and Ananya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Historical records complicated the discussion by showing that earlier decisions had produced consequences their authors had neither intended nor predicted. Several participants warned that a solution optimized for immediate performance might create less visible costs that would emerge only over time. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `By contrast, Ananya and Nandita examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. Historical records complicated the discussion by showing that earlier decisions had produced consequences their authors had neither intended nor predicted. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `Nevertheless, Sameer and Zoya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The episode demonstrated how difficult public choices often involve tradeoffs among legitimate goals rather than a simple contest between right and wrong. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `Against this background, Mira and Raghav examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The available evidence was substantial but incomplete, requiring the participants to distinguish confident conclusions from plausible interpretation. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `Nevertheless, Sameer and Ishaan examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The available evidence was substantial but incomplete, requiring the participants to distinguish confident conclusions from plausible interpretation. The episode demonstrated how difficult public choices often involve tradeoffs among legitimate goals rather than a simple contest between right and wrong. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `The final decision remained open to revision, which some observers initially regarded as weakness. Over time, however, that openness proved to be a strength: it acknowledged uncertainty while preserving accountability, allowing future evidence to improve rather than merely defend the original choice.`
  ]);

  const hardStory35TheMemoryOfTheForest = paragraph([
    `A conservation team combines satellite data with local knowledge to understand why a forest is changing unexpectedly. The events began on a day that seemed unremarkable. Nandita became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `By contrast, Sameer and Aditya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. Historical records complicated the discussion by showing that earlier decisions had produced consequences their authors had neither intended nor predicted. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `As the implications became clearer, Nandita and Ishaan examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The available evidence was substantial but incomplete, requiring the participants to distinguish confident conclusions from plausible interpretation. Rather than searching for a perfect answer, the team developed safeguards, review procedures, and criteria for revising the decision when new evidence appeared. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `Nevertheless, Sameer and Mira examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The episode demonstrated how difficult public choices often involve tradeoffs among legitimate goals rather than a simple contest between right and wrong. Historical records complicated the discussion by showing that earlier decisions had produced consequences their authors had neither intended nor predicted. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `By contrast, Raghav and Nandita examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Several participants warned that a solution optimized for immediate performance might create less visible costs that would emerge only over time. Several participants warned that a solution optimized for immediate performance might create less visible costs that would emerge only over time. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `Nevertheless, Nandita and Ananya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `As the implications became clearer, Nandita and Ishaan examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Rather than searching for a perfect answer, the team developed safeguards, review procedures, and criteria for revising the decision when new evidence appeared. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `The final decision remained open to revision, which some observers initially regarded as weakness. Over time, however, that openness proved to be a strength: it acknowledged uncertainty while preserving accountability, allowing future evidence to improve rather than merely defend the original choice.`
  ]);

  const hardStory36TheTrialOfTheAutonomousFerry = paragraph([
    `A coastal town tests an autonomous ferry, prompting arguments about safety, employment, accountability, and public trust. The events began on a day that seemed unremarkable. Sameer became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `Against this background, Sameer and Mira examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. Historical records complicated the discussion by showing that earlier decisions had produced consequences their authors had neither intended nor predicted. The available evidence was substantial but incomplete, requiring the participants to distinguish confident conclusions from plausible interpretation. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `In retrospect, Nandita and Zoya examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The argument became more precise once the group separated factual uncertainty from genuine disagreement about values and priorities. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `In retrospect, Ananya and Raghav examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. The episode demonstrated how difficult public choices often involve tradeoffs among legitimate goals rather than a simple contest between right and wrong. Efficiency alone could not resolve the dispute because the competing proposals embodied different ideas about responsibility and acceptable risk. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `Nevertheless, Nandita and Raghav examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. The episode demonstrated how difficult public choices often involve tradeoffs among legitimate goals rather than a simple contest between right and wrong. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `As the implications became clearer, Ananya and Sameer examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. Rather than searching for a perfect answer, the team developed safeguards, review procedures, and criteria for revising the decision when new evidence appeared. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `By contrast, Aditya and Raghav examined the competing explanations and questioned whether the evidence justified the confidence with which several claims had been presented. What initially appeared to be a technical difficulty gradually revealed institutional assumptions that had rarely been examined explicitly. Historical records complicated the discussion by showing that earlier decisions had produced consequences their authors had neither intended nor predicted. They proposed a limited trial accompanied by transparent documentation, independent review, and a predetermined point at which the policy would be reconsidered. This approach did not eliminate uncertainty; instead, it made uncertainty visible and therefore easier to govern responsibly.`,
    `The final decision remained open to revision, which some observers initially regarded as weakness. Over time, however, that openness proved to be a strength: it acknowledged uncertainty while preserving accountability, allowing future evidence to improve rather than merely defend the original choice.`
  ]);

  [
    ['general-english', 'general', 'general'],
    ['ssc-chsl-english', 'ssc', 'chsl'],
    ['ssc-cgl-dest-english', 'ssc', 'cgl-dest'],
    ['ssc-delhi-police-hc-ministerial-english', 'ssc', 'delhi-police-hc-ministerial'],
    ['ssc-stenographer-english', 'ssc', 'stenographer'],
    ['ssc-selection-post-english', 'ssc', 'selection-post'],
    ['railway-rrb-ntpc-english', 'railway', 'rrb-ntpc'],
    ['railway-junior-clerk-english', 'railway', 'junior-clerk'],
    ['railway-accounts-clerk-english', 'railway', 'accounts-clerk'],
    ['upsssc-junior-assistant-english', 'up-government', 'upsssc-junior-assistant'],
    ['up-police-computer-operator-english', 'up-government', 'up-police-computer-operator'],
    ['up-clerical-english', 'up-government', 'up-clerical'],
    ['banking-language-practice-english', 'banking', 'language-practice'],
    ['ibps-clerk-english', 'banking', 'ibps-clerk'],
    ['sbi-clerk-english', 'banking', 'sbi-clerk'],
    ['rbi-assistant-english', 'banking', 'rbi-assistant']
  ].forEach(([id, category, exam]) => {
    window.GJU_TYPING_PASSAGE_BANK.push({
      id,
      language: "english",
      category,
      exam,
      levels: {
        easy: [],
        medium: [],
        hard: [hardStory25TheArchiveBeneathTheCourthouse, hardStory26TheLastWeatherObserver, hardStory27TheAlgorithmAndTheApplicant, hardStory28TheCityWithoutMaps, hardStory29TheRestorationOfBellTower, hardStory30TheTranslatorSDilemma, hardStory31TheSilentReservoir, hardStory32TheMuseumAfterMidnight, hardStory33TheObservatoryDebate, hardStory34TheUnfinishedConstitution, hardStory35TheMemoryOfTheForest, hardStory36TheTrialOfTheAutonomousFerry]
      }
    });
  });
})();
