(function () {
  "use strict";

  window.GJU_TYPING_PASSAGE_BANK = window.GJU_TYPING_PASSAGE_BANK || [];

  const paragraph = (parts) => parts.join("\n\n");

  const mediumStory13TheCommunityRadioProject = paragraph([
    `A group of college students starts a community radio program to share useful local information. The events began on a day that seemed unremarkable. Arjun became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `Meanwhile, Arjun reviewed the information with Naina and compared what they had observed. Different people understood the problem differently because each person had access to a different part of the information. Different people understood the problem differently because each person had access to a different part of the information. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Over the next few days, Kabir reviewed the information with Arjun and compared what they had observed. The first solution looked convenient, although closer examination revealed several practical weaknesses. Different people understood the problem differently because each person had access to a different part of the information. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Meanwhile, Mohan reviewed the information with Farah and compared what they had observed. The first solution looked convenient, although closer examination revealed several practical weaknesses. Different people understood the problem differently because each person had access to a different part of the information. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `At the same time, Naina reviewed the information with Dev and compared what they had observed. Different people understood the problem differently because each person had access to a different part of the information. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Later that afternoon, Arjun reviewed the information with Naina and compared what they had observed. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. Instead of treating disagreement as an obstacle, the group used it to identify assumptions that had gone unnoticed. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Meanwhile, Farah reviewed the information with Kabir and compared what they had observed. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. Instead of treating disagreement as an obstacle, the group used it to identify assumptions that had gone unnoticed. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `At the same time, Farah reviewed the information with Arjun and compared what they had observed. Instead of treating disagreement as an obstacle, the group used it to identify assumptions that had gone unnoticed. The first solution looked convenient, although closer examination revealed several practical weaknesses. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `When the project finally settled into a workable routine, the participants understood that success had come from revision rather than from a flawless first plan. Their experience became a useful example of practical cooperation under changing conditions.`
  ]);

  const mediumStory14TheForgottenPhotograph = paragraph([
    `An old photograph leads a woman to search for a childhood friend and revisit memories of a changing town. The events began on a day that seemed unremarkable. Dev became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `Meanwhile, Tara reviewed the information with Mohan and compared what they had observed. Although progress was uneven, the group continued because the purpose of the project remained clear. The discussion became more productive when participants separated urgent concerns from questions that could wait. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Later that afternoon, Leena reviewed the information with Farah and compared what they had observed. The discussion became more productive when participants separated urgent concerns from questions that could wait. The discussion became more productive when participants separated urgent concerns from questions that could wait. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Over the next few days, Farah reviewed the information with Tara and compared what they had observed. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. The discussion became more productive when participants separated urgent concerns from questions that could wait. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Before making a decision, Kabir reviewed the information with Mohan and compared what they had observed. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Before making a decision, Tara reviewed the information with Leena and compared what they had observed. The first solution looked convenient, although closer examination revealed several practical weaknesses. They documented what had worked and what had failed so that the next attempt would begin with better evidence. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Before making a decision, Kabir reviewed the information with Dev and compared what they had observed. The discussion became more productive when participants separated urgent concerns from questions that could wait. Instead of treating disagreement as an obstacle, the group used it to identify assumptions that had gone unnoticed. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Later that afternoon, Kabir reviewed the information with Arjun and compared what they had observed. Although progress was uneven, the group continued because the purpose of the project remained clear. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `When the project finally settled into a workable routine, the participants understood that success had come from revision rather than from a flawless first plan. Their experience became a useful example of practical cooperation under changing conditions.`
  ]);

  const mediumStory15TheMountainRescue = paragraph([
    `Hikers face sudden fog on a mountain trail and must make calm decisions while helping an injured companion. The events began on a day that seemed unremarkable. Dev became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `At the same time, Farah reviewed the information with Arjun and compared what they had observed. The first solution looked convenient, although closer examination revealed several practical weaknesses. The plan required clear communication, realistic expectations, and enough flexibility to respond to unexpected events. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Over the next few days, Mohan reviewed the information with Farah and compared what they had observed. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. The first solution looked convenient, although closer examination revealed several practical weaknesses. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Over the next few days, Arjun reviewed the information with Dev and compared what they had observed. The plan required clear communication, realistic expectations, and enough flexibility to respond to unexpected events. The plan required clear communication, realistic expectations, and enough flexibility to respond to unexpected events. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `As the situation developed, Arjun reviewed the information with Mohan and compared what they had observed. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. Different people understood the problem differently because each person had access to a different part of the information. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Later that afternoon, Mohan reviewed the information with Arjun and compared what they had observed. Although progress was uneven, the group continued because the purpose of the project remained clear. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Meanwhile, Leena reviewed the information with Kabir and compared what they had observed. They documented what had worked and what had failed so that the next attempt would begin with better evidence. Different people understood the problem differently because each person had access to a different part of the information. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Before making a decision, Tara reviewed the information with Naina and compared what they had observed. Instead of treating disagreement as an obstacle, the group used it to identify assumptions that had gone unnoticed. The first solution looked convenient, although closer examination revealed several practical weaknesses. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `When the project finally settled into a workable routine, the participants understood that success had come from revision rather than from a flawless first plan. Their experience became a useful example of practical cooperation under changing conditions.`
  ]);

  const mediumStory16TheNightShift = paragraph([
    `A hospital receptionist working at night learns how small acts of attention can matter during stressful moments. The events began on a day that seemed unremarkable. Mohan became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `As the situation developed, Dev reviewed the information with Farah and compared what they had observed. The first solution looked convenient, although closer examination revealed several practical weaknesses. Different people understood the problem differently because each person had access to a different part of the information. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Over the next few days, Kabir reviewed the information with Mohan and compared what they had observed. Instead of treating disagreement as an obstacle, the group used it to identify assumptions that had gone unnoticed. Instead of treating disagreement as an obstacle, the group used it to identify assumptions that had gone unnoticed. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `At the same time, Arjun reviewed the information with Dev and compared what they had observed. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Before making a decision, Naina reviewed the information with Dev and compared what they had observed. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. Different people understood the problem differently because each person had access to a different part of the information. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Before making a decision, Tara reviewed the information with Mohan and compared what they had observed. The first solution looked convenient, although closer examination revealed several practical weaknesses. Although progress was uneven, the group continued because the purpose of the project remained clear. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Before making a decision, Naina reviewed the information with Farah and compared what they had observed. Although progress was uneven, the group continued because the purpose of the project remained clear. Although progress was uneven, the group continued because the purpose of the project remained clear. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Later that afternoon, Leena reviewed the information with Kabir and compared what they had observed. They documented what had worked and what had failed so that the next attempt would begin with better evidence. They documented what had worked and what had failed so that the next attempt would begin with better evidence. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `When the project finally settled into a workable routine, the participants understood that success had come from revision rather than from a flawless first plan. Their experience became a useful example of practical cooperation under changing conditions.`
  ]);

  const mediumStory17TheBrokenBridge = paragraph([
    `Heavy rain damages a village bridge, forcing residents to organize temporary transport and plan repairs. The events began on a day that seemed unremarkable. Tara became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `At the same time, Arjun reviewed the information with Farah and compared what they had observed. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. They documented what had worked and what had failed so that the next attempt would begin with better evidence. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Later that afternoon, Mohan reviewed the information with Kabir and compared what they had observed. Although progress was uneven, the group continued because the purpose of the project remained clear. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `At the same time, Leena reviewed the information with Kabir and compared what they had observed. The discussion became more productive when participants separated urgent concerns from questions that could wait. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `At the same time, Leena reviewed the information with Mohan and compared what they had observed. Instead of treating disagreement as an obstacle, the group used it to identify assumptions that had gone unnoticed. Different people understood the problem differently because each person had access to a different part of the information. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Later that afternoon, Naina reviewed the information with Leena and compared what they had observed. Different people understood the problem differently because each person had access to a different part of the information. The discussion became more productive when participants separated urgent concerns from questions that could wait. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Later that afternoon, Tara reviewed the information with Dev and compared what they had observed. Different people understood the problem differently because each person had access to a different part of the information. The first solution looked convenient, although closer examination revealed several practical weaknesses. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `As the situation developed, Naina reviewed the information with Kabir and compared what they had observed. Although progress was uneven, the group continued because the purpose of the project remained clear. They documented what had worked and what had failed so that the next attempt would begin with better evidence. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `When the project finally settled into a workable routine, the participants understood that success had come from revision rather than from a flawless first plan. Their experience became a useful example of practical cooperation under changing conditions.`
  ]);

  const mediumStory18TheYoungInventor = paragraph([
    `A student builds a low-cost device to solve a practical problem and learns from repeated failed prototypes. The events began on a day that seemed unremarkable. Leena became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `At the same time, Arjun reviewed the information with Mohan and compared what they had observed. Instead of treating disagreement as an obstacle, the group used it to identify assumptions that had gone unnoticed. Different people understood the problem differently because each person had access to a different part of the information. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Later that afternoon, Kabir reviewed the information with Naina and compared what they had observed. The first solution looked convenient, although closer examination revealed several practical weaknesses. Different people understood the problem differently because each person had access to a different part of the information. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Before making a decision, Farah reviewed the information with Leena and compared what they had observed. The plan required clear communication, realistic expectations, and enough flexibility to respond to unexpected events. They documented what had worked and what had failed so that the next attempt would begin with better evidence. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Over the next few days, Kabir reviewed the information with Tara and compared what they had observed. The discussion became more productive when participants separated urgent concerns from questions that could wait. The discussion became more productive when participants separated urgent concerns from questions that could wait. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Meanwhile, Tara reviewed the information with Farah and compared what they had observed. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. Although progress was uneven, the group continued because the purpose of the project remained clear. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Before making a decision, Leena reviewed the information with Arjun and compared what they had observed. Different people understood the problem differently because each person had access to a different part of the information. The first solution looked convenient, although closer examination revealed several practical weaknesses. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `At the same time, Tara reviewed the information with Mohan and compared what they had observed. They documented what had worked and what had failed so that the next attempt would begin with better evidence. The discussion became more productive when participants separated urgent concerns from questions that could wait. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `When the project finally settled into a workable routine, the participants understood that success had come from revision rather than from a flawless first plan. Their experience became a useful example of practical cooperation under changing conditions.`
  ]);

  const mediumStory19TheBookshopOnCornerStreet = paragraph([
    `An independent bookshop struggles with changing habits and creates new events to bring readers back. The events began on a day that seemed unremarkable. Arjun became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `Meanwhile, Arjun reviewed the information with Mohan and compared what they had observed. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. The first solution looked convenient, although closer examination revealed several practical weaknesses. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `At the same time, Tara reviewed the information with Mohan and compared what they had observed. They documented what had worked and what had failed so that the next attempt would begin with better evidence. The first solution looked convenient, although closer examination revealed several practical weaknesses. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `At the same time, Leena reviewed the information with Arjun and compared what they had observed. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. The plan required clear communication, realistic expectations, and enough flexibility to respond to unexpected events. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Meanwhile, Leena reviewed the information with Dev and compared what they had observed. The discussion became more productive when participants separated urgent concerns from questions that could wait. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Meanwhile, Farah reviewed the information with Naina and compared what they had observed. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. Instead of treating disagreement as an obstacle, the group used it to identify assumptions that had gone unnoticed. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `As the situation developed, Arjun reviewed the information with Dev and compared what they had observed. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. The plan required clear communication, realistic expectations, and enough flexibility to respond to unexpected events. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Before making a decision, Arjun reviewed the information with Dev and compared what they had observed. They documented what had worked and what had failed so that the next attempt would begin with better evidence. The plan required clear communication, realistic expectations, and enough flexibility to respond to unexpected events. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `When the project finally settled into a workable routine, the participants understood that success had come from revision rather than from a flawless first plan. Their experience became a useful example of practical cooperation under changing conditions.`
  ]);

  const mediumStory20TheLongBusJourney = paragraph([
    `Passengers on an overnight bus begin as strangers but gradually cooperate when the vehicle develops a problem. The events began on a day that seemed unremarkable. Naina became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `Over the next few days, Tara reviewed the information with Arjun and compared what they had observed. The first solution looked convenient, although closer examination revealed several practical weaknesses. Instead of treating disagreement as an obstacle, the group used it to identify assumptions that had gone unnoticed. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `As the situation developed, Dev reviewed the information with Mohan and compared what they had observed. Instead of treating disagreement as an obstacle, the group used it to identify assumptions that had gone unnoticed. Although progress was uneven, the group continued because the purpose of the project remained clear. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Before making a decision, Tara reviewed the information with Naina and compared what they had observed. The plan required clear communication, realistic expectations, and enough flexibility to respond to unexpected events. The discussion became more productive when participants separated urgent concerns from questions that could wait. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Over the next few days, Dev reviewed the information with Mohan and compared what they had observed. The first solution looked convenient, although closer examination revealed several practical weaknesses. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `As the situation developed, Tara reviewed the information with Dev and compared what they had observed. Instead of treating disagreement as an obstacle, the group used it to identify assumptions that had gone unnoticed. They documented what had worked and what had failed so that the next attempt would begin with better evidence. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `As the situation developed, Naina reviewed the information with Farah and compared what they had observed. Instead of treating disagreement as an obstacle, the group used it to identify assumptions that had gone unnoticed. Instead of treating disagreement as an obstacle, the group used it to identify assumptions that had gone unnoticed. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Meanwhile, Kabir reviewed the information with Arjun and compared what they had observed. The first solution looked convenient, although closer examination revealed several practical weaknesses. Different people understood the problem differently because each person had access to a different part of the information. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `When the project finally settled into a workable routine, the participants understood that success had come from revision rather than from a flawless first plan. Their experience became a useful example of practical cooperation under changing conditions.`
  ]);

  const mediumStory21TheFloodWarning = paragraph([
    `A local volunteer team prepares neighborhoods for rising water after receiving an uncertain weather warning. The events began on a day that seemed unremarkable. Leena became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `As the situation developed, Arjun reviewed the information with Kabir and compared what they had observed. Different people understood the problem differently because each person had access to a different part of the information. They documented what had worked and what had failed so that the next attempt would begin with better evidence. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Meanwhile, Arjun reviewed the information with Leena and compared what they had observed. Different people understood the problem differently because each person had access to a different part of the information. The first solution looked convenient, although closer examination revealed several practical weaknesses. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Later that afternoon, Arjun reviewed the information with Farah and compared what they had observed. The first solution looked convenient, although closer examination revealed several practical weaknesses. They documented what had worked and what had failed so that the next attempt would begin with better evidence. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Before making a decision, Mohan reviewed the information with Arjun and compared what they had observed. Instead of treating disagreement as an obstacle, the group used it to identify assumptions that had gone unnoticed. They documented what had worked and what had failed so that the next attempt would begin with better evidence. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `At the same time, Mohan reviewed the information with Arjun and compared what they had observed. They documented what had worked and what had failed so that the next attempt would begin with better evidence. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Later that afternoon, Kabir reviewed the information with Naina and compared what they had observed. They documented what had worked and what had failed so that the next attempt would begin with better evidence. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Later that afternoon, Kabir reviewed the information with Dev and compared what they had observed. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. The first solution looked convenient, although closer examination revealed several practical weaknesses. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `When the project finally settled into a workable routine, the participants understood that success had come from revision rather than from a flawless first plan. Their experience became a useful example of practical cooperation under changing conditions.`
  ]);

  const mediumStory22TheDebateCompetition = paragraph([
    `Two students with very different speaking styles prepare for a debate and discover the value of listening. The events began on a day that seemed unremarkable. Tara became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `Over the next few days, Arjun reviewed the information with Farah and compared what they had observed. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. They documented what had worked and what had failed so that the next attempt would begin with better evidence. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Meanwhile, Kabir reviewed the information with Naina and compared what they had observed. The discussion became more productive when participants separated urgent concerns from questions that could wait. Instead of treating disagreement as an obstacle, the group used it to identify assumptions that had gone unnoticed. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `As the situation developed, Naina reviewed the information with Mohan and compared what they had observed. The plan required clear communication, realistic expectations, and enough flexibility to respond to unexpected events. They documented what had worked and what had failed so that the next attempt would begin with better evidence. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `At the same time, Mohan reviewed the information with Naina and compared what they had observed. Instead of treating disagreement as an obstacle, the group used it to identify assumptions that had gone unnoticed. The plan required clear communication, realistic expectations, and enough flexibility to respond to unexpected events. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `At the same time, Mohan reviewed the information with Leena and compared what they had observed. Different people understood the problem differently because each person had access to a different part of the information. Although progress was uneven, the group continued because the purpose of the project remained clear. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Before making a decision, Dev reviewed the information with Naina and compared what they had observed. The first solution looked convenient, although closer examination revealed several practical weaknesses. Different people understood the problem differently because each person had access to a different part of the information. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Over the next few days, Arjun reviewed the information with Kabir and compared what they had observed. The plan required clear communication, realistic expectations, and enough flexibility to respond to unexpected events. The plan required clear communication, realistic expectations, and enough flexibility to respond to unexpected events. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `When the project finally settled into a workable routine, the participants understood that success had come from revision rather than from a flawless first plan. Their experience became a useful example of practical cooperation under changing conditions.`
  ]);

  const mediumStory23TheEmptyFactory = paragraph([
    `Residents discuss how an abandoned factory could be reused without losing the history connected to it. The events began on a day that seemed unremarkable. Dev became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `Before making a decision, Dev reviewed the information with Tara and compared what they had observed. The first solution looked convenient, although closer examination revealed several practical weaknesses. The first solution looked convenient, although closer examination revealed several practical weaknesses. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `As the situation developed, Dev reviewed the information with Mohan and compared what they had observed. The first solution looked convenient, although closer examination revealed several practical weaknesses. Different people understood the problem differently because each person had access to a different part of the information. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Over the next few days, Tara reviewed the information with Arjun and compared what they had observed. The first solution looked convenient, although closer examination revealed several practical weaknesses. The plan required clear communication, realistic expectations, and enough flexibility to respond to unexpected events. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `At the same time, Farah reviewed the information with Tara and compared what they had observed. Although progress was uneven, the group continued because the purpose of the project remained clear. Although progress was uneven, the group continued because the purpose of the project remained clear. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Meanwhile, Farah reviewed the information with Leena and compared what they had observed. The plan required clear communication, realistic expectations, and enough flexibility to respond to unexpected events. Although progress was uneven, the group continued because the purpose of the project remained clear. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Before making a decision, Mohan reviewed the information with Arjun and compared what they had observed. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. The discussion became more productive when participants separated urgent concerns from questions that could wait. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Later that afternoon, Farah reviewed the information with Kabir and compared what they had observed. Although progress was uneven, the group continued because the purpose of the project remained clear. Although progress was uneven, the group continued because the purpose of the project remained clear. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `When the project finally settled into a workable routine, the participants understood that success had come from revision rather than from a flawless first plan. Their experience became a useful example of practical cooperation under changing conditions.`
  ]);

  const mediumStory24TheFestivalCommittee = paragraph([
    `A diverse neighborhood committee plans a public festival while balancing budgets, traditions, and safety. The events began on a day that seemed unremarkable. Arjun became involved almost by accident, but soon realized that the situation deserved more attention than expected.`,
    `At the same time, Farah reviewed the information with Dev and compared what they had observed. The discussion became more productive when participants separated urgent concerns from questions that could wait. Instead of treating disagreement as an obstacle, the group used it to identify assumptions that had gone unnoticed. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Over the next few days, Naina reviewed the information with Arjun and compared what they had observed. The plan required clear communication, realistic expectations, and enough flexibility to respond to unexpected events. Different people understood the problem differently because each person had access to a different part of the information. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `As the situation developed, Tara reviewed the information with Naina and compared what they had observed. The first solution looked convenient, although closer examination revealed several practical weaknesses. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Before making a decision, Mohan reviewed the information with Dev and compared what they had observed. The plan required clear communication, realistic expectations, and enough flexibility to respond to unexpected events. A useful lesson emerged from the process: reliable results usually depend on ordinary habits repeated consistently. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Later that afternoon, Dev reviewed the information with Tara and compared what they had observed. Although progress was uneven, the group continued because the purpose of the project remained clear. The discussion became more productive when participants separated urgent concerns from questions that could wait. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Later that afternoon, Naina reviewed the information with Leena and compared what they had observed. Different people understood the problem differently because each person had access to a different part of the information. The first solution looked convenient, although closer examination revealed several practical weaknesses. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `Over the next few days, Naina reviewed the information with Tara and compared what they had observed. The discussion became more productive when participants separated urgent concerns from questions that could wait. Instead of treating disagreement as an obstacle, the group used it to identify assumptions that had gone unnoticed. They considered cost, time, available skills, and the effect on people who had not attended the meeting. A revised plan divided responsibilities and included a simple method for checking progress. When a new difficulty appeared, they adjusted the sequence rather than abandoning the objective.`,
    `When the project finally settled into a workable routine, the participants understood that success had come from revision rather than from a flawless first plan. Their experience became a useful example of practical cooperation under changing conditions. Hard Level`
  ]);

  [
    ['general-english', 'general', 'general'],
    ['ssc-chsl-english', 'ssc', 'chsl'],
    ['ssc-cgl-dest-english', 'ssc', 'cgl-dest'],
    ['ssc-delhi-police-hc-ministerial-english', 'ssc', 'delhi-police-hc-ministerial'],
    ['ssc-stenographer-english', 'ssc', 'stenographer'],
    ['ssc-selection-post-english', 'ssc', 'selection-post'],
    ['railway-rrb-ntpc-english', 'railway', 'rrb-ntpc'],
    ['railway-junior-clerk-english', 'railway', 'junior-clerk'],
    ['railway-accounts-clerk-english', 'railway', 'accounts-clerk'],
    ['upsssc-junior-assistant-english', 'up-government', 'upsssc-junior-assistant'],
    ['up-police-computer-operator-english', 'up-government', 'up-police-computer-operator'],
    ['up-clerical-english', 'up-government', 'up-clerical'],
    ['banking-language-practice-english', 'banking', 'language-practice'],
    ['ibps-clerk-english', 'banking', 'ibps-clerk'],
    ['sbi-clerk-english', 'banking', 'sbi-clerk'],
    ['rbi-assistant-english', 'banking', 'rbi-assistant']
  ].forEach(([id, category, exam]) => {
    window.GJU_TYPING_PASSAGE_BANK.push({
      id,
      language: "english",
      category,
      exam,
      levels: {
        easy: [],
        medium: [mediumStory13TheCommunityRadioProject, mediumStory14TheForgottenPhotograph, mediumStory15TheMountainRescue, mediumStory16TheNightShift, mediumStory17TheBrokenBridge, mediumStory18TheYoungInventor, mediumStory19TheBookshopOnCornerStreet, mediumStory20TheLongBusJourney, mediumStory21TheFloodWarning, mediumStory22TheDebateCompetition, mediumStory23TheEmptyFactory, mediumStory24TheFestivalCommittee],
        hard: []
      }
    });
  });
})();
