(function () {
  "use strict";

  const disclaimer = "Exam typing/skill-test requirements may vary according to the latest official recruitment notification. Always verify the latest official notification before relying on these settings.";

  const difficulties = ["easy", "medium", "hard"];
  const durations = [1, 2, 5, 10, 15, 30];

  const presets = [
    {
      id: "general-english",
      category: "general",
      name: "General English Typing Test",
      shortName: "English Typing",
      mode: "practice",
      languages: ["english"],
      defaultLanguage: "english",
      duration: 10,
      targetWPM: 35,
      targetAccuracy: 95,
      difficulty: "medium",
      passageCategory: "general",
      passageExam: "general",
      description: "Flexible English typing practice with custom duration, speed target, accuracy target, and difficulty."
    },
    {
      id: "general-hindi",
      category: "general",
      name: "General Hindi Typing Test",
      shortName: "Hindi Typing",
      mode: "practice",
      languages: ["hindi"],
      defaultLanguage: "hindi",
      duration: 10,
      targetWPM: 30,
      targetAccuracy: 95,
      difficulty: "medium",
      passageCategory: "general",
      passageExam: "general",
      description: "Hindi Unicode typing practice with custom duration, speed target, accuracy target, and difficulty.",
      keyboardNote: "Hindi Unicode input is supported through the browser and your selected keyboard/IME."
    },
    {
      id: "ssc-chsl",
      category: "ssc",
      name: "SSC CHSL Typing Test",
      shortName: "SSC CHSL",
      mode: "exam",
      languages: ["english", "hindi"],
      defaultLanguage: "english",
      duration: 10,
      targetWPM: 35,
      targetAccuracy: 95,
      difficulty: "medium",
      passageCategory: "ssc",
      passageExam: "chsl",
      disclaimer
    },
    {
      id: "ssc-cgl-dest",
      category: "ssc",
      name: "SSC CGL DEST Practice",
      shortName: "SSC CGL DEST",
      mode: "exam",
      languages: ["english"],
      defaultLanguage: "english",
      duration: 15,
      targetWPM: 35,
      targetAccuracy: 95,
      difficulty: "medium",
      passageCategory: "ssc",
      passageExam: "cgl-dest",
      disclaimer
    },
    {
      id: "ssc-stenographer",
      category: "ssc",
      name: "SSC Stenographer Practice",
      shortName: "SSC Steno",
      mode: "exam",
      languages: ["english", "hindi"],
      defaultLanguage: "english",
      duration: 10,
      targetWPM: 40,
      targetAccuracy: 95,
      difficulty: "hard",
      passageCategory: "ssc",
      passageExam: "stenographer",
      disclaimer: "This is paragraph typing practice for SSC Stenographer preparation. Official stenography skill-test standards and transcription rules must be verified from the latest SSC notification."
    },
    {
      id: "ssc-selection-post",
      category: "ssc",
      name: "SSC Selection Post Skill Practice",
      shortName: "SSC Selection Post",
      mode: "exam",
      languages: ["english", "hindi"],
      defaultLanguage: "english",
      duration: 10,
      targetWPM: 30,
      targetAccuracy: 95,
      difficulty: "medium",
      passageCategory: "ssc",
      passageExam: "selection-post",
      disclaimer
    },
    {
      id: "rrb-ntpc",
      category: "railway",
      name: "RRB NTPC Typing Test",
      shortName: "RRB NTPC",
      mode: "exam",
      languages: ["english", "hindi"],
      defaultLanguage: "english",
      duration: 10,
      targetWPM: 30,
      targetAccuracy: 95,
      difficulty: "medium",
      passageCategory: "railway",
      passageExam: "rrb-ntpc",
      disclaimer
    },
    {
      id: "railway-junior-clerk",
      category: "railway",
      name: "Railway Junior Clerk cum Typist Practice",
      shortName: "Railway Junior Clerk",
      mode: "exam",
      languages: ["english", "hindi"],
      defaultLanguage: "english",
      duration: 10,
      targetWPM: 30,
      targetAccuracy: 95,
      difficulty: "medium",
      passageCategory: "railway",
      passageExam: "junior-clerk",
      disclaimer
    },
    {
      id: "railway-accounts-clerk",
      category: "railway",
      name: "Railway Accounts Clerk cum Typist Practice",
      shortName: "Accounts Clerk",
      mode: "exam",
      languages: ["english", "hindi"],
      defaultLanguage: "english",
      duration: 10,
      targetWPM: 30,
      targetAccuracy: 95,
      difficulty: "medium",
      passageCategory: "railway",
      passageExam: "accounts-clerk",
      disclaimer
    },
    {
      id: "upsssc-junior-assistant",
      category: "up-government",
      name: "UPSSSC Junior Assistant Typing Test",
      shortName: "UPSSSC Junior Assistant",
      mode: "exam",
      languages: ["hindi", "english"],
      defaultLanguage: "hindi",
      duration: 10,
      targetWPM: 25,
      targetAccuracy: 95,
      difficulty: "medium",
      passageCategory: "up-government",
      passageExam: "upsssc-junior-assistant",
      disclaimer
    },
    {
      id: "up-police-computer-operator",
      category: "up-government",
      name: "UP Police Computer Operator Typing Practice",
      shortName: "UP Police Computer Operator",
      mode: "exam",
      languages: ["hindi", "english"],
      defaultLanguage: "hindi",
      duration: 10,
      targetWPM: 25,
      targetAccuracy: 95,
      difficulty: "medium",
      passageCategory: "up-government",
      passageExam: "up-police-computer-operator",
      disclaimer
    },
    {
      id: "up-clerical",
      category: "up-government",
      name: "UP Government Clerical Typing Practice",
      shortName: "UP Clerical",
      mode: "exam",
      languages: ["hindi", "english"],
      defaultLanguage: "hindi",
      duration: 10,
      targetWPM: 25,
      targetAccuracy: 95,
      difficulty: "medium",
      passageCategory: "up-government",
      passageExam: "up-clerical",
      disclaimer
    },
    {
      id: "banking-language-practice",
      category: "banking",
      name: "Banking Typing & Language Practice",
      shortName: "Banking Practice",
      mode: "practice",
      languages: ["english", "hindi"],
      defaultLanguage: "english",
      duration: 10,
      targetWPM: 30,
      targetAccuracy: 95,
      difficulty: "medium",
      passageCategory: "banking",
      passageExam: "language-practice",
      disclaimer: "Banking recruitment often includes language proficiency checks rather than an official typing test. Treat this as typing and language practice unless the latest official notification says otherwise."
    },
    {
      id: "ibps-clerk-csa-practice",
      category: "banking",
      name: "IBPS Clerk/CSA Typing & Language Practice",
      shortName: "IBPS Clerk/CSA Practice",
      mode: "practice",
      languages: ["english", "hindi"],
      defaultLanguage: "english",
      duration: 10,
      targetWPM: 30,
      targetAccuracy: 95,
      difficulty: "medium",
      passageCategory: "banking",
      passageExam: "ibps-clerk",
      disclaimer: "Use this as typing and language practice. Verify the latest IBPS notification for the actual selection process."
    },
    {
      id: "sbi-clerk-practice",
      category: "banking",
      name: "SBI Clerk Typing & Language Practice",
      shortName: "SBI Clerk Practice",
      mode: "practice",
      languages: ["english", "hindi"],
      defaultLanguage: "english",
      duration: 10,
      targetWPM: 30,
      targetAccuracy: 95,
      difficulty: "medium",
      passageCategory: "banking",
      passageExam: "sbi-clerk",
      disclaimer: "Use this as typing and local-language practice. Verify the latest SBI notification for the actual selection process."
    },
    {
      id: "rbi-assistant-language-practice",
      category: "banking",
      name: "RBI Assistant Language Practice",
      shortName: "RBI Assistant Practice",
      mode: "practice",
      languages: ["english", "hindi"],
      defaultLanguage: "english",
      duration: 10,
      targetWPM: 30,
      targetAccuracy: 95,
      difficulty: "medium",
      passageCategory: "banking",
      passageExam: "rbi-assistant",
      disclaimer: "RBI Assistant selection has a Language Proficiency Test. This page is practice support, not an official typing-test simulator."
    }
  ];

  window.GJU_TYPING_CONFIG = {
    version: "2026.08.11",
    difficulties,
    durations,
    defaultPresetId: "general-english",
    storagePrefix: "GovJobUpdatesTyping.",
    historyLimit: 20,
    presets,
    getPreset(id) {
      return presets.find((preset) => preset.id === id) || presets[0];
    },
    getPresetsByCategory(category) {
      return presets.filter((preset) => preset.category === category);
    }
  };
})();
