CREATE TABLE admins (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('super_admin', 'admin') NOT NULL DEFAULT 'admin',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  last_login_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_admins_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  mobile VARCHAR(20) NOT NULL,
  email VARCHAR(190) NULL,
  category VARCHAR(60) NULL,
  city VARCHAR(120) NULL,
  state VARCHAR(120) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_users_mobile (mobile),
  UNIQUE KEY uq_users_email (email),
  KEY idx_users_mobile (mobile)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE tests (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(220) NOT NULL,
  slug VARCHAR(220) NOT NULL,
  test_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  duration_minutes INT UNSIGNED NOT NULL DEFAULT 60,
  registration_start_at DATETIME NULL,
  registration_end_at DATETIME NULL,
  registration_limit INT UNSIGNED NOT NULL DEFAULT 300,
  status ENUM('upcoming', 'registration_open', 'live', 'closed', 'result_published', 'archived') NOT NULL DEFAULT 'upcoming',
  is_free TINYINT(1) NOT NULL DEFAULT 1,
  fee_amount_paise INT NOT NULL DEFAULT 500,
  result_visible TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_tests_slug (slug),
  KEY idx_tests_status (status),
  KEY idx_tests_date_status (test_date, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE test_sections (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  test_id BIGINT UNSIGNED NOT NULL,
  section_name VARCHAR(120) NOT NULL,
  section_slug VARCHAR(140) NOT NULL,
  section_order INT UNSIGNED NOT NULL,
  question_count INT UNSIGNED NOT NULL DEFAULT 20,
  duration_minutes INT UNSIGNED NOT NULL,
  is_locked_after_time TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_test_sections_test FOREIGN KEY (test_id) REFERENCES tests(id) ON DELETE CASCADE,
  UNIQUE KEY uq_test_sections_slug (test_id, section_slug),
  UNIQUE KEY uq_test_sections_order (test_id, section_order),
  KEY idx_test_sections_test_id (test_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE test_registrations (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  test_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  registration_id VARCHAR(40) NOT NULL,
  registered_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status ENUM('registered', 'cancelled') NOT NULL DEFAULT 'registered',
  payment_status VARCHAR(30) NOT NULL DEFAULT 'not_required',
  amount_paise INT NOT NULL DEFAULT 0,
  discount_paise INT NOT NULL DEFAULT 0,
  payable_paise INT NOT NULL DEFAULT 0,
  promo_code_id INT UNSIGNED NULL,
  payment_id BIGINT UNSIGNED NULL,
  payment_verified_at DATETIME NULL,
  source VARCHAR(50) NOT NULL DEFAULT 'website',
  CONSTRAINT fk_registrations_test FOREIGN KEY (test_id) REFERENCES tests(id) ON DELETE CASCADE,
  CONSTRAINT fk_registrations_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY uq_registrations_registration_id (registration_id),
  UNIQUE KEY uq_registrations_test_user (test_id, user_id),
  KEY idx_registrations_test_id (test_id),
  KEY idx_registrations_user_id (user_id),
  KEY idx_registrations_payment_status (test_id, payment_status),
  KEY idx_registrations_promo_code_id (promo_code_id),
  KEY idx_registrations_payment_id (payment_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE questions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  test_id BIGINT UNSIGNED NOT NULL,
  section_id BIGINT UNSIGNED NOT NULL,
  question_number INT UNSIGNED NOT NULL,
  question_hi TEXT NULL,
  question_en TEXT NULL,
  question_image_path VARCHAR(255) NULL,
  question_image_alt VARCHAR(255) NULL,
  option_a_hi TEXT NULL,
  option_b_hi TEXT NULL,
  option_c_hi TEXT NULL,
  option_d_hi TEXT NULL,
  option_a_en TEXT NULL,
  option_b_en TEXT NULL,
  option_c_en TEXT NULL,
  option_d_en TEXT NULL,
  option_a_image_path VARCHAR(255) NULL,
  option_b_image_path VARCHAR(255) NULL,
  option_c_image_path VARCHAR(255) NULL,
  option_d_image_path VARCHAR(255) NULL,
  correct_option ENUM('A', 'B', 'C', 'D') NOT NULL,
  explanation_hi TEXT NULL,
  explanation_en TEXT NULL,
  explanation_image_path VARCHAR(255) NULL,
  difficulty_level ENUM('easy', 'medium', 'hard') NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_questions_test FOREIGN KEY (test_id) REFERENCES tests(id) ON DELETE CASCADE,
  CONSTRAINT fk_questions_section FOREIGN KEY (section_id) REFERENCES test_sections(id) ON DELETE CASCADE,
  UNIQUE KEY uq_questions_test_section_number (test_id, section_id, question_number),
  KEY idx_questions_test_id (test_id),
  KEY idx_questions_section_id (section_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE test_attempts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  test_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  registration_id BIGINT UNSIGNED NOT NULL,
  started_at DATETIME NULL,
  submitted_at DATETIME NULL,
  status ENUM('not_started', 'in_progress', 'submitted', 'auto_submitted') NOT NULL DEFAULT 'not_started',
  violation_count INT UNSIGNED NOT NULL DEFAULT 0,
  eligibility_status ENUM('clean', 'warning', 'suspicious', 'disqualified') NOT NULL DEFAULT 'clean',
  leaderboard_eligible TINYINT(1) NOT NULL DEFAULT 1,
  prize_eligible TINYINT(1) NOT NULL DEFAULT 1,
  disqualification_reason TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_attempts_test FOREIGN KEY (test_id) REFERENCES tests(id) ON DELETE CASCADE,
  CONSTRAINT fk_attempts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_attempts_registration FOREIGN KEY (registration_id) REFERENCES test_registrations(id) ON DELETE CASCADE,
  UNIQUE KEY uq_attempts_registration (registration_id),
  KEY idx_attempts_test_id (test_id),
  KEY idx_attempts_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE user_answers (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  attempt_id BIGINT UNSIGNED NOT NULL,
  question_id BIGINT UNSIGNED NOT NULL,
  selected_option ENUM('A', 'B', 'C', 'D') NULL,
  answer_status ENUM('not_visited', 'answered', 'not_answered', 'marked_review', 'answered_marked_review') NOT NULL DEFAULT 'not_visited',
  time_spent_seconds INT UNSIGNED NOT NULL DEFAULT 0,
  change_count INT UNSIGNED NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_answers_attempt FOREIGN KEY (attempt_id) REFERENCES test_attempts(id) ON DELETE CASCADE,
  CONSTRAINT fk_user_answers_question FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE,
  UNIQUE KEY uq_user_answers_attempt_question (attempt_id, question_id),
  KEY idx_user_answers_attempt_id (attempt_id),
  KEY idx_user_answers_question_id (question_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE violation_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  attempt_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  test_id BIGINT UNSIGNED NULL,
  registration_id BIGINT UNSIGNED NULL,
  violation_type VARCHAR(80) NOT NULL,
  event_source VARCHAR(80) NULL,
  event_label VARCHAR(160) NULL,
  client_timestamp VARCHAR(80) NULL,
  metadata JSON NULL,
  event_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_violation_logs_attempt FOREIGN KEY (attempt_id) REFERENCES test_attempts(id) ON DELETE CASCADE,
  CONSTRAINT fk_violation_logs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_violation_logs_test FOREIGN KEY (test_id) REFERENCES tests(id) ON DELETE SET NULL,
  CONSTRAINT fk_violation_logs_registration FOREIGN KEY (registration_id) REFERENCES test_registrations(id) ON DELETE SET NULL,
  KEY idx_violation_logs_test_id (test_id),
  KEY idx_violation_logs_user_id (user_id),
  KEY idx_violation_logs_registration_id (registration_id),
  KEY idx_violation_logs_attempt_id (attempt_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE promo_codes (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL,
  description VARCHAR(255) NULL,
  discount_type ENUM('percent','fixed') NOT NULL DEFAULT 'percent',
  discount_value INT NOT NULL DEFAULT 100,
  starts_at DATETIME NULL,
  expires_at DATETIME NOT NULL,
  max_uses INT NULL,
  used_count INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_promo_codes_code (code),
  KEY idx_promo_codes_active_expiry (is_active, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE payments (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  test_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  registration_id VARCHAR(50) NULL,
  razorpay_order_id VARCHAR(100) NULL,
  razorpay_payment_id VARCHAR(100) NULL,
  razorpay_signature TEXT NULL,
  amount_paise INT NOT NULL DEFAULT 0,
  discount_paise INT NOT NULL DEFAULT 0,
  payable_paise INT NOT NULL DEFAULT 0,
  currency VARCHAR(10) NOT NULL DEFAULT 'INR',
  status ENUM('created','pending','paid','failed','cancelled','waived','free_promo') NOT NULL DEFAULT 'created',
  promo_code_id INT UNSIGNED NULL,
  raw_response TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  paid_at DATETIME NULL,
  verified_at DATETIME NULL,
  updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_payments_razorpay_order_id (razorpay_order_id),
  UNIQUE KEY uq_payments_razorpay_payment_id (razorpay_payment_id),
  KEY idx_payments_test_id (test_id),
  KEY idx_payments_user_id (user_id),
  KEY idx_payments_registration_id (registration_id),
  KEY idx_payments_status (status),
  KEY idx_payments_promo_code_id (promo_code_id),
  CONSTRAINT fk_payments_test FOREIGN KEY (test_id) REFERENCES tests(id) ON DELETE CASCADE,
  CONSTRAINT fk_payments_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_payments_promo FOREIGN KEY (promo_code_id) REFERENCES promo_codes(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE test_results (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  test_id BIGINT UNSIGNED NOT NULL,
  attempt_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  marks DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  correct_count INT UNSIGNED NOT NULL DEFAULT 0,
  wrong_count INT UNSIGNED NOT NULL DEFAULT 0,
  attempted_count INT UNSIGNED NOT NULL DEFAULT 0,
  not_attempted_count INT UNSIGNED NOT NULL DEFAULT 0,
  accuracy DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  overall_rank INT UNSIGNED NULL,
  section_summary JSON NULL,
  leaderboard_eligible TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_results_test FOREIGN KEY (test_id) REFERENCES tests(id) ON DELETE CASCADE,
  CONSTRAINT fk_results_attempt FOREIGN KEY (attempt_id) REFERENCES test_attempts(id) ON DELETE CASCADE,
  CONSTRAINT fk_results_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY uq_results_attempt (attempt_id),
  KEY idx_results_test_id (test_id),
  KEY idx_results_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE test_archives (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  test_id BIGINT UNSIGNED NOT NULL,
  archived_by INT UNSIGNED NULL,
  backup_path VARCHAR(255) NULL,
  notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_archives_test FOREIGN KEY (test_id) REFERENCES tests(id) ON DELETE CASCADE,
  CONSTRAINT fk_archives_admin FOREIGN KEY (archived_by) REFERENCES admins(id) ON DELETE SET NULL,
  KEY idx_archives_test_id (test_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


INSERT INTO promo_codes (
  code,
  description,
  discount_type,
  discount_value,
  starts_at,
  expires_at,
  max_uses,
  used_count,
  is_active
) VALUES (
  'GJUFREE',
  'First two weeks free live test registration',
  'percent',
  100,
  '2026-06-01 00:00:00',
  '2026-06-20 23:59:00',
  NULL,
  0,
  1
);
